// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicAggreDealsV3Api.proto
// Protobuf C++ Version: 7.35.0

#ifndef PublicAggreDealsV3Api_2eproto_2epb_2eh
#define PublicAggreDealsV3Api_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_PublicAggreDealsV3Api_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_PublicAggreDealsV3Api_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_PublicAggreDealsV3Api_2eproto;
}  // extern "C"
class PublicAggreDealsV3Api;
struct PublicAggreDealsV3ApiGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern PublicAggreDealsV3ApiGlobalsTypeInternal PublicAggreDealsV3Api_globals_;
extern const ::google::protobuf::internal::ClassDataFull PublicAggreDealsV3Api_class_data_;
#else
extern const PublicAggreDealsV3ApiGlobalsTypeInternal PublicAggreDealsV3Api_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class PublicAggreDealsV3ApiItem;
struct PublicAggreDealsV3ApiItemGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern PublicAggreDealsV3ApiItemGlobalsTypeInternal PublicAggreDealsV3ApiItem_globals_;
extern const ::google::protobuf::internal::ClassDataFull PublicAggreDealsV3ApiItem_class_data_;
#else
extern const PublicAggreDealsV3ApiItemGlobalsTypeInternal PublicAggreDealsV3ApiItem_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PublicAggreDealsV3ApiItem final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PublicAggreDealsV3ApiItem) */ {
 public:
  inline PublicAggreDealsV3ApiItem() : PublicAggreDealsV3ApiItem(nullptr) {}
  ~PublicAggreDealsV3ApiItem() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PublicAggreDealsV3ApiItem* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PublicAggreDealsV3ApiItem));
  }
#endif

  template <typename = void>
  explicit constexpr PublicAggreDealsV3ApiItem(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline PublicAggreDealsV3ApiItem(const PublicAggreDealsV3ApiItem& from) : PublicAggreDealsV3ApiItem(nullptr, from) {}
  inline PublicAggreDealsV3ApiItem(PublicAggreDealsV3ApiItem&& from) noexcept : PublicAggreDealsV3ApiItem(nullptr, ::std::move(from)) {}
  inline PublicAggreDealsV3ApiItem& operator=(const PublicAggreDealsV3ApiItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline PublicAggreDealsV3ApiItem& operator=(PublicAggreDealsV3ApiItem&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const PublicAggreDealsV3ApiItem& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<PublicAggreDealsV3ApiItem>(&PublicAggreDealsV3ApiItem_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PublicAggreDealsV3ApiItem& a, PublicAggreDealsV3ApiItem& b) { a.Swap(&b); }
  inline void Swap(PublicAggreDealsV3ApiItem* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PublicAggreDealsV3ApiItem* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PublicAggreDealsV3ApiItem* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PublicAggreDealsV3ApiItem>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PublicAggreDealsV3ApiItem& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PublicAggreDealsV3ApiItem& from) { PublicAggreDealsV3ApiItem::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PublicAggreDealsV3ApiItem* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PublicAggreDealsV3ApiItem"; }

  explicit PublicAggreDealsV3ApiItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PublicAggreDealsV3ApiItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PublicAggreDealsV3ApiItem& from);
  PublicAggreDealsV3ApiItem(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PublicAggreDealsV3ApiItem&& from) noexcept
      : PublicAggreDealsV3ApiItem(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPriceFieldNumber = 1,
    kQuantityFieldNumber = 2,
    kTimeFieldNumber = 4,
    kTradeTypeFieldNumber = 3,
  };
  // string price = 1;
  void clear_price() ;
  [[nodiscard]] const ::std::string& price() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_price(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_price();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_price();
  void set_allocated_price(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_price() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_price(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_price();

  public:
  // string quantity = 2;
  void clear_quantity() ;
  [[nodiscard]] const ::std::string& quantity() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_quantity(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_quantity();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_quantity();
  void set_allocated_quantity(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_quantity() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_quantity(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_quantity();

  public:
  // int64 time = 4;
  void clear_time() ;
  [[nodiscard]] ::int64_t time() const;
  void set_time(::int64_t value);

  private:
  ::int64_t _internal_time() const;
  void _internal_set_time(::int64_t value);

  public:
  // int32 tradeType = 3;
  void clear_tradetype() ;
  [[nodiscard]] ::int32_t tradetype() const;
  void set_tradetype(::int32_t value);

  private:
  ::int32_t _internal_tradetype() const;
  void _internal_set_tradetype(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PublicAggreDealsV3ApiItem)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 4,
                          0, 47,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PublicAggreDealsV3ApiItem& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr price_;
    ::google::protobuf::internal::ArenaStringPtr quantity_;
    ::int64_t time_;
    ::int32_t tradetype_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PublicAggreDealsV3Api_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PublicAggreDealsV3Api final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PublicAggreDealsV3Api) */ {
 public:
  inline PublicAggreDealsV3Api() : PublicAggreDealsV3Api(nullptr) {}
  ~PublicAggreDealsV3Api() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PublicAggreDealsV3Api* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PublicAggreDealsV3Api));
  }
#endif

  template <typename = void>
  explicit constexpr PublicAggreDealsV3Api(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline PublicAggreDealsV3Api(const PublicAggreDealsV3Api& from) : PublicAggreDealsV3Api(nullptr, from) {}
  inline PublicAggreDealsV3Api(PublicAggreDealsV3Api&& from) noexcept : PublicAggreDealsV3Api(nullptr, ::std::move(from)) {}
  inline PublicAggreDealsV3Api& operator=(const PublicAggreDealsV3Api& from) {
    CopyFrom(from);
    return *this;
  }
  inline PublicAggreDealsV3Api& operator=(PublicAggreDealsV3Api&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const PublicAggreDealsV3Api& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<PublicAggreDealsV3Api>(&PublicAggreDealsV3Api_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PublicAggreDealsV3Api& a, PublicAggreDealsV3Api& b) { a.Swap(&b); }
  inline void Swap(PublicAggreDealsV3Api* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PublicAggreDealsV3Api* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PublicAggreDealsV3Api* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PublicAggreDealsV3Api>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PublicAggreDealsV3Api& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PublicAggreDealsV3Api& from) { PublicAggreDealsV3Api::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PublicAggreDealsV3Api* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PublicAggreDealsV3Api"; }

  explicit PublicAggreDealsV3Api(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PublicAggreDealsV3Api(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PublicAggreDealsV3Api& from);
  PublicAggreDealsV3Api(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PublicAggreDealsV3Api&& from) noexcept
      : PublicAggreDealsV3Api(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDealsFieldNumber = 1,
    kEventTypeFieldNumber = 2,
  };
  // repeated .PublicAggreDealsV3ApiItem deals = 1;
  [[nodiscard]] int deals_size()
      const;
  private:
  int _internal_deals_size() const;

  public:
  void clear_deals() ;
  [[nodiscard]] const ::PublicAggreDealsV3ApiItem& deals(int index) const;
  [[nodiscard]] ::PublicAggreDealsV3ApiItem* PROTOBUF_NONNULL mutable_deals(int index);
  ::PublicAggreDealsV3ApiItem* PROTOBUF_NONNULL add_deals();
  [[nodiscard]] const ::google::protobuf::RepeatedPtrField<::PublicAggreDealsV3ApiItem>&
  deals() const;
  [[nodiscard]] ::google::protobuf::RepeatedPtrField<::PublicAggreDealsV3ApiItem>* PROTOBUF_NONNULL
  mutable_deals();

  private:
  const ::google::protobuf::RepeatedPtrField<::PublicAggreDealsV3ApiItem>& _internal_deals() const;
  ::google::protobuf::RepeatedPtrField<::PublicAggreDealsV3ApiItem>* PROTOBUF_NONNULL _internal_mutable_deals();

  public:
  // string eventType = 2;
  void clear_eventtype() ;
  [[nodiscard]] const ::std::string& eventtype() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_eventtype(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_eventtype();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_eventtype();
  void set_allocated_eventtype(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_eventtype() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_eventtype(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_eventtype();

  public:
  // @@protoc_insertion_point(class_scope:PublicAggreDealsV3Api)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<1, 2,
                          1, 39,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PublicAggreDealsV3Api& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::PublicAggreDealsV3ApiItem > deals_;
    ::google::protobuf::internal::ArenaStringPtr eventtype_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PublicAggreDealsV3Api_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PublicAggreDealsV3Api

// repeated .PublicAggreDealsV3ApiItem deals = 1;
inline int PublicAggreDealsV3Api::_internal_deals_size() const {
  return _internal_deals().size();
}
inline int PublicAggreDealsV3Api::deals_size() const {
  return _internal_deals_size();
}
inline void PublicAggreDealsV3Api::clear_deals() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.deals_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::PublicAggreDealsV3ApiItem& PublicAggreDealsV3Api::deals(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PublicAggreDealsV3Api.deals)
  return _internal_deals().Get(index);
}
inline ::PublicAggreDealsV3ApiItem* PROTOBUF_NONNULL PublicAggreDealsV3Api::mutable_deals(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:PublicAggreDealsV3Api.deals)
  return _internal_mutable_deals()->Mutable(index);
}
inline ::PublicAggreDealsV3ApiItem* PROTOBUF_NONNULL PublicAggreDealsV3Api::add_deals()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::PublicAggreDealsV3ApiItem* _add =
      _internal_mutable_deals()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:PublicAggreDealsV3Api.deals)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::PublicAggreDealsV3ApiItem>& PublicAggreDealsV3Api::deals() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:PublicAggreDealsV3Api.deals)
  return _internal_deals();
}
inline ::google::protobuf::RepeatedPtrField<::PublicAggreDealsV3ApiItem>* PROTOBUF_NONNULL
PublicAggreDealsV3Api::mutable_deals() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:PublicAggreDealsV3Api.deals)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_deals();
}
inline const ::google::protobuf::RepeatedPtrField<::PublicAggreDealsV3ApiItem>&
PublicAggreDealsV3Api::_internal_deals() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.deals_;
}
inline ::google::protobuf::RepeatedPtrField<::PublicAggreDealsV3ApiItem>* PROTOBUF_NONNULL
PublicAggreDealsV3Api::_internal_mutable_deals() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.deals_;
}

// string eventType = 2;
inline void PublicAggreDealsV3Api::clear_eventtype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eventtype_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& PublicAggreDealsV3Api::eventtype() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PublicAggreDealsV3Api.eventType)
  return _internal_eventtype();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PublicAggreDealsV3Api::set_eventtype(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.eventtype_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PublicAggreDealsV3Api.eventType)
}
inline ::std::string* PROTOBUF_NONNULL PublicAggreDealsV3Api::mutable_eventtype()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_eventtype();
  // @@protoc_insertion_point(field_mutable:PublicAggreDealsV3Api.eventType)
  return _s;
}
inline const ::std::string& PublicAggreDealsV3Api::_internal_eventtype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.eventtype_.Get();
}
inline void PublicAggreDealsV3Api::_internal_set_eventtype(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eventtype_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PublicAggreDealsV3Api::_internal_mutable_eventtype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.eventtype_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PublicAggreDealsV3Api::release_eventtype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PublicAggreDealsV3Api.eventType)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.eventtype_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.eventtype_.Set("", GetArena());
  }
  return released;
}
inline void PublicAggreDealsV3Api::set_allocated_eventtype(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.eventtype_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.eventtype_.IsDefault()) {
    _impl_.eventtype_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:PublicAggreDealsV3Api.eventType)
}

// -------------------------------------------------------------------

// PublicAggreDealsV3ApiItem

// string price = 1;
inline void PublicAggreDealsV3ApiItem::clear_price() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& PublicAggreDealsV3ApiItem::price() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PublicAggreDealsV3ApiItem.price)
  return _internal_price();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PublicAggreDealsV3ApiItem::set_price(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.price_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PublicAggreDealsV3ApiItem.price)
}
inline ::std::string* PROTOBUF_NONNULL PublicAggreDealsV3ApiItem::mutable_price()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_price();
  // @@protoc_insertion_point(field_mutable:PublicAggreDealsV3ApiItem.price)
  return _s;
}
inline const ::std::string& PublicAggreDealsV3ApiItem::_internal_price() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.price_.Get();
}
inline void PublicAggreDealsV3ApiItem::_internal_set_price(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.price_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PublicAggreDealsV3ApiItem::_internal_mutable_price() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.price_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PublicAggreDealsV3ApiItem::release_price() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PublicAggreDealsV3ApiItem.price)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.price_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.price_.Set("", GetArena());
  }
  return released;
}
inline void PublicAggreDealsV3ApiItem::set_allocated_price(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.price_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.price_.IsDefault()) {
    _impl_.price_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:PublicAggreDealsV3ApiItem.price)
}

// string quantity = 2;
inline void PublicAggreDealsV3ApiItem::clear_quantity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quantity_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& PublicAggreDealsV3ApiItem::quantity() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PublicAggreDealsV3ApiItem.quantity)
  return _internal_quantity();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PublicAggreDealsV3ApiItem::set_quantity(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.quantity_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PublicAggreDealsV3ApiItem.quantity)
}
inline ::std::string* PROTOBUF_NONNULL PublicAggreDealsV3ApiItem::mutable_quantity()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_quantity();
  // @@protoc_insertion_point(field_mutable:PublicAggreDealsV3ApiItem.quantity)
  return _s;
}
inline const ::std::string& PublicAggreDealsV3ApiItem::_internal_quantity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.quantity_.Get();
}
inline void PublicAggreDealsV3ApiItem::_internal_set_quantity(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.quantity_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PublicAggreDealsV3ApiItem::_internal_mutable_quantity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.quantity_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PublicAggreDealsV3ApiItem::release_quantity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PublicAggreDealsV3ApiItem.quantity)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.quantity_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.quantity_.Set("", GetArena());
  }
  return released;
}
inline void PublicAggreDealsV3ApiItem::set_allocated_quantity(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.quantity_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.quantity_.IsDefault()) {
    _impl_.quantity_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:PublicAggreDealsV3ApiItem.quantity)
}

// int32 tradeType = 3;
inline void PublicAggreDealsV3ApiItem::clear_tradetype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tradetype_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::int32_t PublicAggreDealsV3ApiItem::tradetype() const {
  // @@protoc_insertion_point(field_get:PublicAggreDealsV3ApiItem.tradeType)
  return _internal_tradetype();
}
inline void PublicAggreDealsV3ApiItem::set_tradetype(::int32_t value) {
  _internal_set_tradetype(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:PublicAggreDealsV3ApiItem.tradeType)
}
inline ::int32_t PublicAggreDealsV3ApiItem::_internal_tradetype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tradetype_;
}
inline void PublicAggreDealsV3ApiItem::_internal_set_tradetype(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tradetype_ = value;
}

// int64 time = 4;
inline void PublicAggreDealsV3ApiItem::clear_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::int64_t PublicAggreDealsV3ApiItem::time() const {
  // @@protoc_insertion_point(field_get:PublicAggreDealsV3ApiItem.time)
  return _internal_time();
}
inline void PublicAggreDealsV3ApiItem::set_time(::int64_t value) {
  _internal_set_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:PublicAggreDealsV3ApiItem.time)
}
inline ::int64_t PublicAggreDealsV3ApiItem::_internal_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.time_;
}
inline void PublicAggreDealsV3ApiItem::_internal_set_time(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // PublicAggreDealsV3Api_2eproto_2epb_2eh
