// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicDealsV3Api.proto

#include "PublicDealsV3Api.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_PublicDealsV3Api_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PublicDealsV3ApiItem_PublicDealsV3Api_2eproto;
class PublicDealsV3ApiDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PublicDealsV3Api> _instance;
} _PublicDealsV3Api_default_instance_;
class PublicDealsV3ApiItemDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PublicDealsV3ApiItem> _instance;
} _PublicDealsV3ApiItem_default_instance_;
static void InitDefaultsscc_info_PublicDealsV3Api_PublicDealsV3Api_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_PublicDealsV3Api_default_instance_;
    new (ptr) ::PublicDealsV3Api();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PublicDealsV3Api::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_PublicDealsV3Api_PublicDealsV3Api_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_PublicDealsV3Api_PublicDealsV3Api_2eproto}, {
      &scc_info_PublicDealsV3ApiItem_PublicDealsV3Api_2eproto.base,}};

static void InitDefaultsscc_info_PublicDealsV3ApiItem_PublicDealsV3Api_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_PublicDealsV3ApiItem_default_instance_;
    new (ptr) ::PublicDealsV3ApiItem();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PublicDealsV3ApiItem::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PublicDealsV3ApiItem_PublicDealsV3Api_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PublicDealsV3ApiItem_PublicDealsV3Api_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_PublicDealsV3Api_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_PublicDealsV3Api_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_PublicDealsV3Api_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_PublicDealsV3Api_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PublicDealsV3Api, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::PublicDealsV3Api, deals_),
  PROTOBUF_FIELD_OFFSET(::PublicDealsV3Api, eventtype_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PublicDealsV3ApiItem, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::PublicDealsV3ApiItem, price_),
  PROTOBUF_FIELD_OFFSET(::PublicDealsV3ApiItem, quantity_),
  PROTOBUF_FIELD_OFFSET(::PublicDealsV3ApiItem, tradetype_),
  PROTOBUF_FIELD_OFFSET(::PublicDealsV3ApiItem, time_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::PublicDealsV3Api)},
  { 7, -1, sizeof(::PublicDealsV3ApiItem)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_PublicDealsV3Api_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_PublicDealsV3ApiItem_default_instance_),
};

const char descriptor_table_protodef_PublicDealsV3Api_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026PublicDealsV3Api.proto\"K\n\020PublicDealsV"
  "3Api\022$\n\005deals\030\001 \003(\0132\025.PublicDealsV3ApiIt"
  "em\022\021\n\teventType\030\002 \001(\t\"X\n\024PublicDealsV3Ap"
  "iItem\022\r\n\005price\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\t\022\021"
  "\n\ttradeType\030\003 \001(\005\022\014\n\004time\030\004 \001(\003B9\n\034com.m"
  "xc.push.common.protobufB\025PublicDealsV3Ap"
  "iProtoH\001P\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_PublicDealsV3Api_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_PublicDealsV3Api_2eproto_sccs[2] = {
  &scc_info_PublicDealsV3Api_PublicDealsV3Api_2eproto.base,
  &scc_info_PublicDealsV3ApiItem_PublicDealsV3Api_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_PublicDealsV3Api_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PublicDealsV3Api_2eproto = {
  false, false, descriptor_table_protodef_PublicDealsV3Api_2eproto, "PublicDealsV3Api.proto", 258,
  &descriptor_table_PublicDealsV3Api_2eproto_once, descriptor_table_PublicDealsV3Api_2eproto_sccs, descriptor_table_PublicDealsV3Api_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_PublicDealsV3Api_2eproto::offsets,
  file_level_metadata_PublicDealsV3Api_2eproto, 2, file_level_enum_descriptors_PublicDealsV3Api_2eproto, file_level_service_descriptors_PublicDealsV3Api_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_PublicDealsV3Api_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_PublicDealsV3Api_2eproto)), true);

// ===================================================================

void PublicDealsV3Api::InitAsDefaultInstance() {
}
class PublicDealsV3Api::_Internal {
 public:
};

PublicDealsV3Api::PublicDealsV3Api(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  deals_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:PublicDealsV3Api)
}
PublicDealsV3Api::PublicDealsV3Api(const PublicDealsV3Api& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      deals_(from.deals_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  eventtype_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_eventtype().empty()) {
    eventtype_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_eventtype(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:PublicDealsV3Api)
}

void PublicDealsV3Api::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PublicDealsV3Api_PublicDealsV3Api_2eproto.base);
  eventtype_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

PublicDealsV3Api::~PublicDealsV3Api() {
  // @@protoc_insertion_point(destructor:PublicDealsV3Api)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PublicDealsV3Api::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  eventtype_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PublicDealsV3Api::ArenaDtor(void* object) {
  PublicDealsV3Api* _this = reinterpret_cast< PublicDealsV3Api* >(object);
  (void)_this;
}
void PublicDealsV3Api::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PublicDealsV3Api::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PublicDealsV3Api& PublicDealsV3Api::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PublicDealsV3Api_PublicDealsV3Api_2eproto.base);
  return *internal_default_instance();
}


void PublicDealsV3Api::Clear() {
// @@protoc_insertion_point(message_clear_start:PublicDealsV3Api)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  deals_.Clear();
  eventtype_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PublicDealsV3Api::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .PublicDealsV3ApiItem deals = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_deals(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      // string eventType = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_eventtype();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "PublicDealsV3Api.eventType"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PublicDealsV3Api::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PublicDealsV3Api)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .PublicDealsV3ApiItem deals = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_deals_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_deals(i), target, stream);
  }

  // string eventType = 2;
  if (this->eventtype().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_eventtype().data(), static_cast<int>(this->_internal_eventtype().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicDealsV3Api.eventType");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_eventtype(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PublicDealsV3Api)
  return target;
}

size_t PublicDealsV3Api::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PublicDealsV3Api)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .PublicDealsV3ApiItem deals = 1;
  total_size += 1UL * this->_internal_deals_size();
  for (const auto& msg : this->deals_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string eventType = 2;
  if (this->eventtype().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_eventtype());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PublicDealsV3Api::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PublicDealsV3Api)
  GOOGLE_DCHECK_NE(&from, this);
  const PublicDealsV3Api* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PublicDealsV3Api>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PublicDealsV3Api)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PublicDealsV3Api)
    MergeFrom(*source);
  }
}

void PublicDealsV3Api::MergeFrom(const PublicDealsV3Api& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PublicDealsV3Api)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  deals_.MergeFrom(from.deals_);
  if (from.eventtype().size() > 0) {
    _internal_set_eventtype(from._internal_eventtype());
  }
}

void PublicDealsV3Api::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PublicDealsV3Api)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PublicDealsV3Api::CopyFrom(const PublicDealsV3Api& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PublicDealsV3Api)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PublicDealsV3Api::IsInitialized() const {
  return true;
}

void PublicDealsV3Api::InternalSwap(PublicDealsV3Api* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  deals_.InternalSwap(&other->deals_);
  eventtype_.Swap(&other->eventtype_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata PublicDealsV3Api::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void PublicDealsV3ApiItem::InitAsDefaultInstance() {
}
class PublicDealsV3ApiItem::_Internal {
 public:
};

PublicDealsV3ApiItem::PublicDealsV3ApiItem(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:PublicDealsV3ApiItem)
}
PublicDealsV3ApiItem::PublicDealsV3ApiItem(const PublicDealsV3ApiItem& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  price_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_price().empty()) {
    price_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_price(),
      GetArena());
  }
  quantity_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_quantity().empty()) {
    quantity_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_quantity(),
      GetArena());
  }
  ::memcpy(&time_, &from.time_,
    static_cast<size_t>(reinterpret_cast<char*>(&tradetype_) -
    reinterpret_cast<char*>(&time_)) + sizeof(tradetype_));
  // @@protoc_insertion_point(copy_constructor:PublicDealsV3ApiItem)
}

void PublicDealsV3ApiItem::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PublicDealsV3ApiItem_PublicDealsV3Api_2eproto.base);
  price_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  quantity_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&tradetype_) -
      reinterpret_cast<char*>(&time_)) + sizeof(tradetype_));
}

PublicDealsV3ApiItem::~PublicDealsV3ApiItem() {
  // @@protoc_insertion_point(destructor:PublicDealsV3ApiItem)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PublicDealsV3ApiItem::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  price_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  quantity_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PublicDealsV3ApiItem::ArenaDtor(void* object) {
  PublicDealsV3ApiItem* _this = reinterpret_cast< PublicDealsV3ApiItem* >(object);
  (void)_this;
}
void PublicDealsV3ApiItem::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PublicDealsV3ApiItem::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PublicDealsV3ApiItem& PublicDealsV3ApiItem::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PublicDealsV3ApiItem_PublicDealsV3Api_2eproto.base);
  return *internal_default_instance();
}


void PublicDealsV3ApiItem::Clear() {
// @@protoc_insertion_point(message_clear_start:PublicDealsV3ApiItem)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  price_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  quantity_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&tradetype_) -
      reinterpret_cast<char*>(&time_)) + sizeof(tradetype_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PublicDealsV3ApiItem::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string price = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_price();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "PublicDealsV3ApiItem.price"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string quantity = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_quantity();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "PublicDealsV3ApiItem.quantity"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 tradeType = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          tradetype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 time = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PublicDealsV3ApiItem::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PublicDealsV3ApiItem)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string price = 1;
  if (this->price().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_price().data(), static_cast<int>(this->_internal_price().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicDealsV3ApiItem.price");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_price(), target);
  }

  // string quantity = 2;
  if (this->quantity().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_quantity().data(), static_cast<int>(this->_internal_quantity().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PublicDealsV3ApiItem.quantity");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_quantity(), target);
  }

  // int32 tradeType = 3;
  if (this->tradetype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_tradetype(), target);
  }

  // int64 time = 4;
  if (this->time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(4, this->_internal_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PublicDealsV3ApiItem)
  return target;
}

size_t PublicDealsV3ApiItem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PublicDealsV3ApiItem)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string price = 1;
  if (this->price().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_price());
  }

  // string quantity = 2;
  if (this->quantity().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_quantity());
  }

  // int64 time = 4;
  if (this->time() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_time());
  }

  // int32 tradeType = 3;
  if (this->tradetype() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_tradetype());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PublicDealsV3ApiItem::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PublicDealsV3ApiItem)
  GOOGLE_DCHECK_NE(&from, this);
  const PublicDealsV3ApiItem* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PublicDealsV3ApiItem>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PublicDealsV3ApiItem)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PublicDealsV3ApiItem)
    MergeFrom(*source);
  }
}

void PublicDealsV3ApiItem::MergeFrom(const PublicDealsV3ApiItem& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PublicDealsV3ApiItem)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.price().size() > 0) {
    _internal_set_price(from._internal_price());
  }
  if (from.quantity().size() > 0) {
    _internal_set_quantity(from._internal_quantity());
  }
  if (from.time() != 0) {
    _internal_set_time(from._internal_time());
  }
  if (from.tradetype() != 0) {
    _internal_set_tradetype(from._internal_tradetype());
  }
}

void PublicDealsV3ApiItem::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PublicDealsV3ApiItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PublicDealsV3ApiItem::CopyFrom(const PublicDealsV3ApiItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PublicDealsV3ApiItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PublicDealsV3ApiItem::IsInitialized() const {
  return true;
}

void PublicDealsV3ApiItem::InternalSwap(PublicDealsV3ApiItem* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  price_.Swap(&other->price_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  quantity_.Swap(&other->quantity_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PublicDealsV3ApiItem, tradetype_)
      + sizeof(PublicDealsV3ApiItem::tradetype_)
      - PROTOBUF_FIELD_OFFSET(PublicDealsV3ApiItem, time_)>(
          reinterpret_cast<char*>(&time_),
          reinterpret_cast<char*>(&other->time_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PublicDealsV3ApiItem::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PublicDealsV3Api* Arena::CreateMaybeMessage< ::PublicDealsV3Api >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PublicDealsV3Api >(arena);
}
template<> PROTOBUF_NOINLINE ::PublicDealsV3ApiItem* Arena::CreateMaybeMessage< ::PublicDealsV3ApiItem >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PublicDealsV3ApiItem >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
