// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicIncreaseDepthsV3Api.proto
// Protobuf C++ Version: 7.35.0

#include "PublicIncreaseDepthsV3Api.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::PublicIncreaseDepthsV3Api
        {&::_pbi::kDescriptorMethods, &::descriptor_table_PublicIncreaseDepthsV3Api_2eproto, /* tracker*/ nullptr,},
        // ::PublicIncreaseDepthV3ApiItem
        {&::_pbi::kDescriptorMethods, &::descriptor_table_PublicIncreaseDepthsV3Api_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
class PublicIncreaseDepthV3ApiItem::_Internal {
 public:
  using HasBits = decltype(::std::declval<PublicIncreaseDepthV3ApiItem>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthV3ApiItem, _impl_._has_bits_);
};

constexpr PublicIncreaseDepthV3ApiItem::ParseTableT_ PublicIncreaseDepthV3ApiItem::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthV3ApiItem, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::PublicIncreaseDepthV3ApiItem>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // string quantity = 2;
      {::_pbi::TcParser::FastUS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthV3ApiItem, _impl_.quantity_)}},
      // string price = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthV3ApiItem, _impl_.price_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string price = 1;
      {PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthV3ApiItem, _impl_.price_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string quantity = 2;
      {PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthV3ApiItem, _impl_.quantity_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
      "\34\5\10\0\0\0\0\0"
      "PublicIncreaseDepthV3ApiItem"
      "price"
      "quantity"
    }},
  };
}


inline constexpr PublicIncreaseDepthV3ApiItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        price_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        quantity_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr PublicIncreaseDepthV3ApiItem::PublicIncreaseDepthV3ApiItem(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL PublicIncreaseDepthV3ApiItem::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PublicIncreaseDepthV3ApiItem(arena);
}
constexpr auto PublicIncreaseDepthV3ApiItem::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PublicIncreaseDepthV3ApiItem), alignof(PublicIncreaseDepthV3ApiItem));
}
constexpr auto PublicIncreaseDepthV3ApiItem::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &PublicIncreaseDepthV3ApiItem::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PublicIncreaseDepthV3ApiItem>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PublicIncreaseDepthV3ApiItem::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PublicIncreaseDepthV3ApiItem>(), &PublicIncreaseDepthV3ApiItem::ByteSizeLong,
              &PublicIncreaseDepthV3ApiItem::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthV3ApiItem, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_PublicIncreaseDepthsV3Api_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct PublicIncreaseDepthV3ApiItemGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr PublicIncreaseDepthV3ApiItemGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 PublicIncreaseDepthV3ApiItem_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(PublicIncreaseDepthV3ApiItem::InternalGenerateClassData_(
            _default, &PublicIncreaseDepthV3ApiItem_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<PublicIncreaseDepthV3ApiItem>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~PublicIncreaseDepthV3ApiItemGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) PublicIncreaseDepthV3ApiItem _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<PublicIncreaseDepthV3ApiItem>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthV3ApiItemGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST PublicIncreaseDepthV3ApiItemGlobalsTypeInternal PublicIncreaseDepthV3ApiItem_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* PublicIncreaseDepthV3ApiItem_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return PublicIncreaseDepthV3ApiItem_globals_.GetClassData();
#else
  return PublicIncreaseDepthV3ApiItem_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class PublicIncreaseDepthsV3Api::_Internal {
 public:
  using HasBits = decltype(::std::declval<PublicIncreaseDepthsV3Api>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthsV3Api, _impl_._has_bits_);
};

constexpr PublicIncreaseDepthsV3Api::ParseTableT_ PublicIncreaseDepthsV3Api::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthsV3Api, _impl_._has_bits_),
      0, // no _extensions_
      4, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967280,  // skipmap
      offsetof(ParseTableT_, field_entries),
      4,  // num_field_entries
      2,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::PublicIncreaseDepthsV3Api>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // string version = 4;
      {::_pbi::TcParser::FastUS1,
       {34, 3, 0,
        PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthsV3Api, _impl_.version_)}},
      // repeated .PublicIncreaseDepthV3ApiItem asks = 1;
      {::_pbi::TcParser::FastMtR1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthsV3Api, _impl_.asks_)}},
      // repeated .PublicIncreaseDepthV3ApiItem bids = 2;
      {::_pbi::TcParser::FastMtR1,
       {18, 1, 1,
        PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthsV3Api, _impl_.bids_)}},
      // string eventType = 3;
      {::_pbi::TcParser::FastUS1,
       {26, 2, 0,
        PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthsV3Api, _impl_.eventtype_)}},
    }}, {{
      65535, 65535
    }}, {{
      // repeated .PublicIncreaseDepthV3ApiItem asks = 1;
      {PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthsV3Api, _impl_.asks_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
      // repeated .PublicIncreaseDepthV3ApiItem bids = 2;
      {PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthsV3Api, _impl_.bids_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
      // string eventType = 3;
      {PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthsV3Api, _impl_.eventtype_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string version = 4;
      {PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthsV3Api, _impl_.version_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicIncreaseDepthV3ApiItem>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicIncreaseDepthV3ApiItem_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicIncreaseDepthV3ApiItem>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicIncreaseDepthV3ApiItem_globals_},
        #endif
    }},
    {{
      "\31\0\0\11\7\0\0\0"
      "PublicIncreaseDepthsV3Api"
      "eventType"
      "version"
    }},
  };
}


inline constexpr PublicIncreaseDepthsV3Api::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        asks_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::PublicIncreaseDepthsV3Api,
            PROTOBUF_FIELD_OFFSET(::PublicIncreaseDepthsV3Api, _impl_.asks_)>()
         }
        ,
        bids_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::PublicIncreaseDepthsV3Api,
            PROTOBUF_FIELD_OFFSET(::PublicIncreaseDepthsV3Api, _impl_.bids_)>()
         }
        ,
        eventtype_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr PublicIncreaseDepthsV3Api::PublicIncreaseDepthsV3Api(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL PublicIncreaseDepthsV3Api::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PublicIncreaseDepthsV3Api(arena);
}
constexpr auto PublicIncreaseDepthsV3Api::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PublicIncreaseDepthsV3Api), alignof(PublicIncreaseDepthsV3Api));
}
constexpr auto PublicIncreaseDepthsV3Api::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &PublicIncreaseDepthsV3Api::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PublicIncreaseDepthsV3Api>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PublicIncreaseDepthsV3Api::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PublicIncreaseDepthsV3Api>(), &PublicIncreaseDepthsV3Api::ByteSizeLong,
              &PublicIncreaseDepthsV3Api::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthsV3Api, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_PublicIncreaseDepthsV3Api_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct PublicIncreaseDepthsV3ApiGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr PublicIncreaseDepthsV3ApiGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 PublicIncreaseDepthsV3Api_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(PublicIncreaseDepthsV3Api::InternalGenerateClassData_(
            _default, &PublicIncreaseDepthsV3Api_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<PublicIncreaseDepthsV3Api>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~PublicIncreaseDepthsV3ApiGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) PublicIncreaseDepthsV3Api _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<PublicIncreaseDepthsV3Api>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(PublicIncreaseDepthsV3ApiGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST PublicIncreaseDepthsV3ApiGlobalsTypeInternal PublicIncreaseDepthsV3Api_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* PublicIncreaseDepthsV3Api_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return PublicIncreaseDepthsV3Api_globals_.GetClassData();
#else
  return PublicIncreaseDepthsV3Api_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_PublicIncreaseDepthsV3Api_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_PublicIncreaseDepthsV3Api_2eproto = nullptr;
const ::uint32_t
    TableStruct_PublicIncreaseDepthsV3Api_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::PublicIncreaseDepthsV3Api, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::PublicIncreaseDepthsV3Api, _impl_.asks_),
        PROTOBUF_FIELD_OFFSET(::PublicIncreaseDepthsV3Api, _impl_.bids_),
        PROTOBUF_FIELD_OFFSET(::PublicIncreaseDepthsV3Api, _impl_.eventtype_),
        PROTOBUF_FIELD_OFFSET(::PublicIncreaseDepthsV3Api, _impl_.version_),
        0,
        1,
        2,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::PublicIncreaseDepthV3ApiItem, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::PublicIncreaseDepthV3ApiItem, _impl_.price_),
        PROTOBUF_FIELD_OFFSET(::PublicIncreaseDepthV3ApiItem, _impl_.quantity_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::PublicIncreaseDepthsV3Api)},
        {11, sizeof(::PublicIncreaseDepthV3ApiItem)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::PublicIncreaseDepthsV3Api_globals_,
        &::PublicIncreaseDepthV3ApiItem_globals_,
};
const char descriptor_table_protodef_PublicIncreaseDepthsV3Api_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\037PublicIncreaseDepthsV3Api.proto\"\231\001\n\031Pu"
    "blicIncreaseDepthsV3Api\022+\n\004asks\030\001 \003(\0132\035."
    "PublicIncreaseDepthV3ApiItem\022+\n\004bids\030\002 \003"
    "(\0132\035.PublicIncreaseDepthV3ApiItem\022\021\n\teve"
    "ntType\030\003 \001(\t\022\017\n\007version\030\004 \001(\t\"\?\n\034PublicI"
    "ncreaseDepthV3ApiItem\022\r\n\005price\030\001 \001(\t\022\020\n\010"
    "quantity\030\002 \001(\tBB\n\034com.mxc.push.common.pr"
    "otobufB\036PublicIncreaseDepthsV3ApiProtoH\001"
    "P\001b\006proto3"
};
static ::absl::once_flag descriptor_table_PublicIncreaseDepthsV3Api_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_PublicIncreaseDepthsV3Api_2eproto = {
    false,
    false,
    330,
    descriptor_table_protodef_PublicIncreaseDepthsV3Api_2eproto,
    "PublicIncreaseDepthsV3Api.proto",
    &descriptor_table_PublicIncreaseDepthsV3Api_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_message_globals,
    TableStruct_PublicIncreaseDepthsV3Api_2eproto::offsets,
    file_level_enum_descriptors_PublicIncreaseDepthsV3Api_2eproto,
    file_level_service_descriptors_PublicIncreaseDepthsV3Api_2eproto,
};
// ===================================================================

PublicIncreaseDepthsV3Api::PublicIncreaseDepthsV3Api(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PublicIncreaseDepthsV3Api_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PublicIncreaseDepthsV3Api)
}
PROTOBUF_NDEBUG_INLINE PublicIncreaseDepthsV3Api::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::PublicIncreaseDepthsV3Api& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        asks_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::PublicIncreaseDepthsV3Api,
              PROTOBUF_FIELD_OFFSET(::PublicIncreaseDepthsV3Api, _impl_.asks_)>()
          , from.asks_
        }
        ,
        bids_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::PublicIncreaseDepthsV3Api,
              PROTOBUF_FIELD_OFFSET(::PublicIncreaseDepthsV3Api, _impl_.bids_)>()
          , from.bids_
        }
        ,
        eventtype_(arena, from.eventtype_),
        version_(arena, from.version_) {}

PublicIncreaseDepthsV3Api::PublicIncreaseDepthsV3Api(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PublicIncreaseDepthsV3Api& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PublicIncreaseDepthsV3Api_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PublicIncreaseDepthsV3Api* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:PublicIncreaseDepthsV3Api)
}
PROTOBUF_NDEBUG_INLINE PublicIncreaseDepthsV3Api::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        asks_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::PublicIncreaseDepthsV3Api,
            PROTOBUF_FIELD_OFFSET(::PublicIncreaseDepthsV3Api, _impl_.asks_)>()
         }
        ,
        bids_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::PublicIncreaseDepthsV3Api,
            PROTOBUF_FIELD_OFFSET(::PublicIncreaseDepthsV3Api, _impl_.bids_)>()
         }
        ,
        eventtype_(arena),
        version_(arena) {}

inline void PublicIncreaseDepthsV3Api::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PublicIncreaseDepthsV3Api::~PublicIncreaseDepthsV3Api() {
  // @@protoc_insertion_point(destructor:PublicIncreaseDepthsV3Api)
  SharedDtor(*this);
}
inline void PublicIncreaseDepthsV3Api::SharedDtor(MessageLite& self) {
  PublicIncreaseDepthsV3Api& this_ = static_cast<PublicIncreaseDepthsV3Api&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.eventtype_.Destroy();
  this_._impl_.version_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PublicIncreaseDepthsV3Api_class_data_ =
        PublicIncreaseDepthsV3Api::InternalGenerateClassData_(PublicIncreaseDepthsV3Api_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PublicIncreaseDepthsV3Api::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PublicIncreaseDepthsV3Api_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PublicIncreaseDepthsV3Api_class_data_.tc_table);
  return PublicIncreaseDepthsV3Api_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PublicIncreaseDepthsV3Api::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PublicIncreaseDepthsV3Api_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&PublicIncreaseDepthsV3Api_globals_));
  return PublicIncreaseDepthsV3Api_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const PublicIncreaseDepthsV3Api::ParseTableT_
    PublicIncreaseDepthsV3Api::_table_ =
        PublicIncreaseDepthsV3Api::InternalGenerateParseTable_(PublicIncreaseDepthsV3Api_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void PublicIncreaseDepthsV3Api::Clear() {
// @@protoc_insertion_point(message_clear_start:PublicIncreaseDepthsV3Api)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.asks_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.bids_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.eventtype_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.version_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PublicIncreaseDepthsV3Api::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PublicIncreaseDepthsV3Api& this_ = static_cast<const PublicIncreaseDepthsV3Api&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PublicIncreaseDepthsV3Api::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PublicIncreaseDepthsV3Api& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:PublicIncreaseDepthsV3Api)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .PublicIncreaseDepthV3ApiItem asks = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_asks_size());
         i < n; i++) {
      const auto& repfield = this_._internal_asks().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // repeated .PublicIncreaseDepthV3ApiItem bids = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_bids_size());
         i < n; i++) {
      const auto& repfield = this_._internal_bids().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // string eventType = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_eventtype().empty()) {
      const ::std::string& _s = this_._internal_eventtype();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PublicIncreaseDepthsV3Api.eventType");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string version = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_version().empty()) {
      const ::std::string& _s = this_._internal_version();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PublicIncreaseDepthsV3Api.version");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PublicIncreaseDepthsV3Api)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PublicIncreaseDepthsV3Api::ByteSizeLong(const MessageLite& base) {
  const PublicIncreaseDepthsV3Api& this_ = static_cast<const PublicIncreaseDepthsV3Api&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PublicIncreaseDepthsV3Api::ByteSizeLong() const {
  const PublicIncreaseDepthsV3Api& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:PublicIncreaseDepthsV3Api)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // repeated .PublicIncreaseDepthV3ApiItem asks = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_asks_size();
      for (const auto& msg : this_._internal_asks()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .PublicIncreaseDepthV3ApiItem bids = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_bids_size();
      for (const auto& msg : this_._internal_bids()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // string eventType = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_eventtype().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_eventtype());
      }
    }
    // string version = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_version().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_version());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PublicIncreaseDepthsV3Api::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<PublicIncreaseDepthsV3Api*>(&to_msg);
  auto& from = static_cast<const PublicIncreaseDepthsV3Api&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:PublicIncreaseDepthsV3Api)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_asks()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_asks());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_bids()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_bids());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_eventtype().empty()) {
        _this->_internal_set_eventtype(from._internal_eventtype());
      } else {
        if (_this->_impl_.eventtype_.IsDefault()) {
          _this->_internal_set_eventtype("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_version().empty()) {
        _this->_internal_set_version(from._internal_version());
      } else {
        if (_this->_impl_.version_.IsDefault()) {
          _this->_internal_set_version("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PublicIncreaseDepthsV3Api::CopyFrom(const PublicIncreaseDepthsV3Api& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:PublicIncreaseDepthsV3Api)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PublicIncreaseDepthsV3Api::InternalSwap(PublicIncreaseDepthsV3Api* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.asks_.InternalSwap(&other->_impl_.asks_);
  _impl_.bids_.InternalSwap(&other->_impl_.bids_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.eventtype_, &other->_impl_.eventtype_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.version_, &other->_impl_.version_, arena);
}

::google::protobuf::Metadata PublicIncreaseDepthsV3Api::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

PublicIncreaseDepthV3ApiItem::PublicIncreaseDepthV3ApiItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PublicIncreaseDepthV3ApiItem_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PublicIncreaseDepthV3ApiItem)
}
PROTOBUF_NDEBUG_INLINE PublicIncreaseDepthV3ApiItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::PublicIncreaseDepthV3ApiItem& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        price_(arena, from.price_),
        quantity_(arena, from.quantity_) {}

PublicIncreaseDepthV3ApiItem::PublicIncreaseDepthV3ApiItem(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PublicIncreaseDepthV3ApiItem& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PublicIncreaseDepthV3ApiItem_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PublicIncreaseDepthV3ApiItem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:PublicIncreaseDepthV3ApiItem)
}
PROTOBUF_NDEBUG_INLINE PublicIncreaseDepthV3ApiItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        price_(arena),
        quantity_(arena) {}

inline void PublicIncreaseDepthV3ApiItem::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PublicIncreaseDepthV3ApiItem::~PublicIncreaseDepthV3ApiItem() {
  // @@protoc_insertion_point(destructor:PublicIncreaseDepthV3ApiItem)
  SharedDtor(*this);
}
inline void PublicIncreaseDepthV3ApiItem::SharedDtor(MessageLite& self) {
  PublicIncreaseDepthV3ApiItem& this_ = static_cast<PublicIncreaseDepthV3ApiItem&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.price_.Destroy();
  this_._impl_.quantity_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PublicIncreaseDepthV3ApiItem_class_data_ =
        PublicIncreaseDepthV3ApiItem::InternalGenerateClassData_(PublicIncreaseDepthV3ApiItem_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PublicIncreaseDepthV3ApiItem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PublicIncreaseDepthV3ApiItem_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PublicIncreaseDepthV3ApiItem_class_data_.tc_table);
  return PublicIncreaseDepthV3ApiItem_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PublicIncreaseDepthV3ApiItem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PublicIncreaseDepthV3ApiItem_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&PublicIncreaseDepthV3ApiItem_globals_));
  return PublicIncreaseDepthV3ApiItem_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const PublicIncreaseDepthV3ApiItem::ParseTableT_
    PublicIncreaseDepthV3ApiItem::_table_ =
        PublicIncreaseDepthV3ApiItem::InternalGenerateParseTable_(PublicIncreaseDepthV3ApiItem_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void PublicIncreaseDepthV3ApiItem::Clear() {
// @@protoc_insertion_point(message_clear_start:PublicIncreaseDepthV3ApiItem)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.price_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.quantity_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PublicIncreaseDepthV3ApiItem::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PublicIncreaseDepthV3ApiItem& this_ = static_cast<const PublicIncreaseDepthV3ApiItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PublicIncreaseDepthV3ApiItem::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PublicIncreaseDepthV3ApiItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:PublicIncreaseDepthV3ApiItem)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string price = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_price().empty()) {
      const ::std::string& _s = this_._internal_price();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PublicIncreaseDepthV3ApiItem.price");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string quantity = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_quantity().empty()) {
      const ::std::string& _s = this_._internal_quantity();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PublicIncreaseDepthV3ApiItem.quantity");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PublicIncreaseDepthV3ApiItem)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PublicIncreaseDepthV3ApiItem::ByteSizeLong(const MessageLite& base) {
  const PublicIncreaseDepthV3ApiItem& this_ = static_cast<const PublicIncreaseDepthV3ApiItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PublicIncreaseDepthV3ApiItem::ByteSizeLong() const {
  const PublicIncreaseDepthV3ApiItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:PublicIncreaseDepthV3ApiItem)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string price = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_price().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_price());
      }
    }
    // string quantity = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_quantity().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_quantity());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PublicIncreaseDepthV3ApiItem::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<PublicIncreaseDepthV3ApiItem*>(&to_msg);
  auto& from = static_cast<const PublicIncreaseDepthV3ApiItem&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:PublicIncreaseDepthV3ApiItem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_price().empty()) {
        _this->_internal_set_price(from._internal_price());
      } else {
        if (_this->_impl_.price_.IsDefault()) {
          _this->_internal_set_price("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_quantity().empty()) {
        _this->_internal_set_quantity(from._internal_quantity());
      } else {
        if (_this->_impl_.quantity_.IsDefault()) {
          _this->_internal_set_quantity("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PublicIncreaseDepthV3ApiItem::CopyFrom(const PublicIncreaseDepthV3ApiItem& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:PublicIncreaseDepthV3ApiItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PublicIncreaseDepthV3ApiItem::InternalSwap(PublicIncreaseDepthV3ApiItem* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.price_, &other->_impl_.price_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.quantity_, &other->_impl_.quantity_, arena);
}

::google::protobuf::Metadata PublicIncreaseDepthV3ApiItem::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_PublicIncreaseDepthsV3Api_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
