// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicBookTickerBatchV3Api.proto
// Protobuf C++ Version: 7.35.0

#include "PublicBookTickerBatchV3Api.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::PublicBookTickerBatchV3Api
        {&::_pbi::kDescriptorMethods, &::descriptor_table_PublicBookTickerBatchV3Api_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
class PublicBookTickerBatchV3Api::_Internal {
 public:
  using HasBits = decltype(::std::declval<PublicBookTickerBatchV3Api>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PublicBookTickerBatchV3Api, _impl_._has_bits_);
};

constexpr PublicBookTickerBatchV3Api::ParseTableT_ PublicBookTickerBatchV3Api::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(PublicBookTickerBatchV3Api, _impl_._has_bits_),
      0, // no _extensions_
      1, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967294,  // skipmap
      offsetof(ParseTableT_, field_entries),
      1,  // num_field_entries
      1,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::PublicBookTickerBatchV3Api>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // repeated .PublicBookTickerV3Api items = 1;
      {::_pbi::TcParser::FastMtR1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(PublicBookTickerBatchV3Api, _impl_.items_)}},
    }}, {{
      65535, 65535
    }}, {{
      // repeated .PublicBookTickerV3Api items = 1;
      {PROTOBUF_FIELD_OFFSET(PublicBookTickerBatchV3Api, _impl_.items_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicBookTickerV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicBookTickerV3Api_globals_},
        #endif
    }},
    {{
    }},
  };
}


inline constexpr PublicBookTickerBatchV3Api::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        items_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::PublicBookTickerBatchV3Api,
            PROTOBUF_FIELD_OFFSET(::PublicBookTickerBatchV3Api, _impl_.items_)>()
         }
     {}

template <typename>
constexpr PublicBookTickerBatchV3Api::PublicBookTickerBatchV3Api(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL PublicBookTickerBatchV3Api::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PublicBookTickerBatchV3Api(arena);
}
constexpr auto PublicBookTickerBatchV3Api::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PublicBookTickerBatchV3Api), alignof(PublicBookTickerBatchV3Api));
}
constexpr auto PublicBookTickerBatchV3Api::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &PublicBookTickerBatchV3Api::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PublicBookTickerBatchV3Api>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PublicBookTickerBatchV3Api::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PublicBookTickerBatchV3Api>(), &PublicBookTickerBatchV3Api::ByteSizeLong,
              &PublicBookTickerBatchV3Api::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PublicBookTickerBatchV3Api, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_PublicBookTickerBatchV3Api_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct PublicBookTickerBatchV3ApiGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr PublicBookTickerBatchV3ApiGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 PublicBookTickerBatchV3Api_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(PublicBookTickerBatchV3Api::InternalGenerateClassData_(
            _default, &PublicBookTickerBatchV3Api_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<PublicBookTickerBatchV3Api>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~PublicBookTickerBatchV3ApiGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) PublicBookTickerBatchV3Api _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<PublicBookTickerBatchV3Api>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(PublicBookTickerBatchV3ApiGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST PublicBookTickerBatchV3ApiGlobalsTypeInternal PublicBookTickerBatchV3Api_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* PublicBookTickerBatchV3Api_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return PublicBookTickerBatchV3Api_globals_.GetClassData();
#else
  return PublicBookTickerBatchV3Api_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_PublicBookTickerBatchV3Api_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_PublicBookTickerBatchV3Api_2eproto = nullptr;
const ::uint32_t
    TableStruct_PublicBookTickerBatchV3Api_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::PublicBookTickerBatchV3Api, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::PublicBookTickerBatchV3Api, _impl_.items_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::PublicBookTickerBatchV3Api)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::PublicBookTickerBatchV3Api_globals_,
};
const char descriptor_table_protodef_PublicBookTickerBatchV3Api_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n PublicBookTickerBatchV3Api.proto\032\033Publ"
    "icBookTickerV3Api.proto\"C\n\032PublicBookTic"
    "kerBatchV3Api\022%\n\005items\030\001 \003(\0132\026.PublicBoo"
    "kTickerV3ApiBC\n\034com.mxc.push.common.prot"
    "obufB\037PublicBookTickerBatchV3ApiProtoH\001P"
    "\001b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_PublicBookTickerBatchV3Api_2eproto_deps[1] = {
        &::descriptor_table_PublicBookTickerV3Api_2eproto,
};
static ::absl::once_flag descriptor_table_PublicBookTickerBatchV3Api_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_PublicBookTickerBatchV3Api_2eproto = {
    false,
    false,
    209,
    descriptor_table_protodef_PublicBookTickerBatchV3Api_2eproto,
    "PublicBookTickerBatchV3Api.proto",
    &descriptor_table_PublicBookTickerBatchV3Api_2eproto_once,
    descriptor_table_PublicBookTickerBatchV3Api_2eproto_deps,
    1,
    1,
    schemas,
    file_message_globals,
    TableStruct_PublicBookTickerBatchV3Api_2eproto::offsets,
    file_level_enum_descriptors_PublicBookTickerBatchV3Api_2eproto,
    file_level_service_descriptors_PublicBookTickerBatchV3Api_2eproto,
};
// ===================================================================

void PublicBookTickerBatchV3Api::clear_items() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.items_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
PublicBookTickerBatchV3Api::PublicBookTickerBatchV3Api(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PublicBookTickerBatchV3Api_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PublicBookTickerBatchV3Api)
}
PROTOBUF_NDEBUG_INLINE PublicBookTickerBatchV3Api::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::PublicBookTickerBatchV3Api& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        items_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::PublicBookTickerBatchV3Api,
              PROTOBUF_FIELD_OFFSET(::PublicBookTickerBatchV3Api, _impl_.items_)>()
          , from.items_
        }
     {}

PublicBookTickerBatchV3Api::PublicBookTickerBatchV3Api(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PublicBookTickerBatchV3Api& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PublicBookTickerBatchV3Api_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PublicBookTickerBatchV3Api* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:PublicBookTickerBatchV3Api)
}
PROTOBUF_NDEBUG_INLINE PublicBookTickerBatchV3Api::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        items_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::PublicBookTickerBatchV3Api,
            PROTOBUF_FIELD_OFFSET(::PublicBookTickerBatchV3Api, _impl_.items_)>()
         }
     {}

inline void PublicBookTickerBatchV3Api::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PublicBookTickerBatchV3Api::~PublicBookTickerBatchV3Api() {
  // @@protoc_insertion_point(destructor:PublicBookTickerBatchV3Api)
  SharedDtor(*this);
}
inline void PublicBookTickerBatchV3Api::SharedDtor(MessageLite& self) {
  PublicBookTickerBatchV3Api& this_ = static_cast<PublicBookTickerBatchV3Api&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PublicBookTickerBatchV3Api_class_data_ =
        PublicBookTickerBatchV3Api::InternalGenerateClassData_(PublicBookTickerBatchV3Api_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PublicBookTickerBatchV3Api::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PublicBookTickerBatchV3Api_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PublicBookTickerBatchV3Api_class_data_.tc_table);
  return PublicBookTickerBatchV3Api_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PublicBookTickerBatchV3Api::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PublicBookTickerBatchV3Api_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&PublicBookTickerBatchV3Api_globals_));
  return PublicBookTickerBatchV3Api_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const PublicBookTickerBatchV3Api::ParseTableT_
    PublicBookTickerBatchV3Api::_table_ =
        PublicBookTickerBatchV3Api::InternalGenerateParseTable_(PublicBookTickerBatchV3Api_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void PublicBookTickerBatchV3Api::Clear() {
// @@protoc_insertion_point(message_clear_start:PublicBookTickerBatchV3Api)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.items_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PublicBookTickerBatchV3Api::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PublicBookTickerBatchV3Api& this_ = static_cast<const PublicBookTickerBatchV3Api&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PublicBookTickerBatchV3Api::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PublicBookTickerBatchV3Api& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:PublicBookTickerBatchV3Api)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .PublicBookTickerV3Api items = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_items_size());
         i < n; i++) {
      const auto& repfield = this_._internal_items().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PublicBookTickerBatchV3Api)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PublicBookTickerBatchV3Api::ByteSizeLong(const MessageLite& base) {
  const PublicBookTickerBatchV3Api& this_ = static_cast<const PublicBookTickerBatchV3Api&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PublicBookTickerBatchV3Api::ByteSizeLong() const {
  const PublicBookTickerBatchV3Api& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:PublicBookTickerBatchV3Api)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .PublicBookTickerV3Api items = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_items_size();
      for (const auto& msg : this_._internal_items()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PublicBookTickerBatchV3Api::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<PublicBookTickerBatchV3Api*>(&to_msg);
  auto& from = static_cast<const PublicBookTickerBatchV3Api&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:PublicBookTickerBatchV3Api)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_items()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_items());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PublicBookTickerBatchV3Api::CopyFrom(const PublicBookTickerBatchV3Api& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:PublicBookTickerBatchV3Api)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PublicBookTickerBatchV3Api::InternalSwap(PublicBookTickerBatchV3Api* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.items_.InternalSwap(&other->_impl_.items_);
}

::google::protobuf::Metadata PublicBookTickerBatchV3Api::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_PublicBookTickerBatchV3Api_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
