// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicBookTickerV3Api.proto
// Protobuf C++ Version: 7.35.0

#ifndef PublicBookTickerV3Api_2eproto_2epb_2eh
#define PublicBookTickerV3Api_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_PublicBookTickerV3Api_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_PublicBookTickerV3Api_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_PublicBookTickerV3Api_2eproto;
}  // extern "C"
class PublicBookTickerV3Api;
struct PublicBookTickerV3ApiGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern PublicBookTickerV3ApiGlobalsTypeInternal PublicBookTickerV3Api_globals_;
extern const ::google::protobuf::internal::ClassDataFull PublicBookTickerV3Api_class_data_;
#else
extern const PublicBookTickerV3ApiGlobalsTypeInternal PublicBookTickerV3Api_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PublicBookTickerV3Api final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PublicBookTickerV3Api) */ {
 public:
  inline PublicBookTickerV3Api() : PublicBookTickerV3Api(nullptr) {}
  ~PublicBookTickerV3Api() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PublicBookTickerV3Api* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PublicBookTickerV3Api));
  }
#endif

  template <typename = void>
  explicit constexpr PublicBookTickerV3Api(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline PublicBookTickerV3Api(const PublicBookTickerV3Api& from) : PublicBookTickerV3Api(nullptr, from) {}
  inline PublicBookTickerV3Api(PublicBookTickerV3Api&& from) noexcept : PublicBookTickerV3Api(nullptr, ::std::move(from)) {}
  inline PublicBookTickerV3Api& operator=(const PublicBookTickerV3Api& from) {
    CopyFrom(from);
    return *this;
  }
  inline PublicBookTickerV3Api& operator=(PublicBookTickerV3Api&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const PublicBookTickerV3Api& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<PublicBookTickerV3Api>(&PublicBookTickerV3Api_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PublicBookTickerV3Api& a, PublicBookTickerV3Api& b) { a.Swap(&b); }
  inline void Swap(PublicBookTickerV3Api* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PublicBookTickerV3Api* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PublicBookTickerV3Api* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PublicBookTickerV3Api>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PublicBookTickerV3Api& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PublicBookTickerV3Api& from) { PublicBookTickerV3Api::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PublicBookTickerV3Api* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PublicBookTickerV3Api"; }

  explicit PublicBookTickerV3Api(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PublicBookTickerV3Api(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PublicBookTickerV3Api& from);
  PublicBookTickerV3Api(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PublicBookTickerV3Api&& from) noexcept
      : PublicBookTickerV3Api(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBidPriceFieldNumber = 1,
    kBidQuantityFieldNumber = 2,
    kAskPriceFieldNumber = 3,
    kAskQuantityFieldNumber = 4,
  };
  // string bidPrice = 1;
  void clear_bidprice() ;
  [[nodiscard]] const ::std::string& bidprice() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_bidprice(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_bidprice();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_bidprice();
  void set_allocated_bidprice(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_bidprice() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_bidprice(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_bidprice();

  public:
  // string bidQuantity = 2;
  void clear_bidquantity() ;
  [[nodiscard]] const ::std::string& bidquantity() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_bidquantity(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_bidquantity();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_bidquantity();
  void set_allocated_bidquantity(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_bidquantity() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_bidquantity(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_bidquantity();

  public:
  // string askPrice = 3;
  void clear_askprice() ;
  [[nodiscard]] const ::std::string& askprice() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_askprice(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_askprice();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_askprice();
  void set_allocated_askprice(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_askprice() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_askprice(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_askprice();

  public:
  // string askQuantity = 4;
  void clear_askquantity() ;
  [[nodiscard]] const ::std::string& askquantity() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_askquantity(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_askquantity();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_askquantity();
  void set_allocated_askquantity(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_askquantity() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_askquantity(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_askquantity();

  public:
  // @@protoc_insertion_point(class_scope:PublicBookTickerV3Api)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<2, 4,
                          0, 68,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PublicBookTickerV3Api& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr bidprice_;
    ::google::protobuf::internal::ArenaStringPtr bidquantity_;
    ::google::protobuf::internal::ArenaStringPtr askprice_;
    ::google::protobuf::internal::ArenaStringPtr askquantity_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_PublicBookTickerV3Api_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PublicBookTickerV3Api

// string bidPrice = 1;
inline void PublicBookTickerV3Api::clear_bidprice() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bidprice_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& PublicBookTickerV3Api::bidprice() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PublicBookTickerV3Api.bidPrice)
  return _internal_bidprice();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PublicBookTickerV3Api::set_bidprice(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.bidprice_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PublicBookTickerV3Api.bidPrice)
}
inline ::std::string* PROTOBUF_NONNULL PublicBookTickerV3Api::mutable_bidprice()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_bidprice();
  // @@protoc_insertion_point(field_mutable:PublicBookTickerV3Api.bidPrice)
  return _s;
}
inline const ::std::string& PublicBookTickerV3Api::_internal_bidprice() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bidprice_.Get();
}
inline void PublicBookTickerV3Api::_internal_set_bidprice(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bidprice_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PublicBookTickerV3Api::_internal_mutable_bidprice() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.bidprice_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PublicBookTickerV3Api::release_bidprice() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PublicBookTickerV3Api.bidPrice)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.bidprice_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.bidprice_.Set("", GetArena());
  }
  return released;
}
inline void PublicBookTickerV3Api::set_allocated_bidprice(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.bidprice_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.bidprice_.IsDefault()) {
    _impl_.bidprice_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:PublicBookTickerV3Api.bidPrice)
}

// string bidQuantity = 2;
inline void PublicBookTickerV3Api::clear_bidquantity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bidquantity_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& PublicBookTickerV3Api::bidquantity() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PublicBookTickerV3Api.bidQuantity)
  return _internal_bidquantity();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PublicBookTickerV3Api::set_bidquantity(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.bidquantity_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PublicBookTickerV3Api.bidQuantity)
}
inline ::std::string* PROTOBUF_NONNULL PublicBookTickerV3Api::mutable_bidquantity()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_bidquantity();
  // @@protoc_insertion_point(field_mutable:PublicBookTickerV3Api.bidQuantity)
  return _s;
}
inline const ::std::string& PublicBookTickerV3Api::_internal_bidquantity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bidquantity_.Get();
}
inline void PublicBookTickerV3Api::_internal_set_bidquantity(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bidquantity_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PublicBookTickerV3Api::_internal_mutable_bidquantity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.bidquantity_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PublicBookTickerV3Api::release_bidquantity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PublicBookTickerV3Api.bidQuantity)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.bidquantity_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.bidquantity_.Set("", GetArena());
  }
  return released;
}
inline void PublicBookTickerV3Api::set_allocated_bidquantity(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.bidquantity_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.bidquantity_.IsDefault()) {
    _impl_.bidquantity_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:PublicBookTickerV3Api.bidQuantity)
}

// string askPrice = 3;
inline void PublicBookTickerV3Api::clear_askprice() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.askprice_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline const ::std::string& PublicBookTickerV3Api::askprice() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PublicBookTickerV3Api.askPrice)
  return _internal_askprice();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PublicBookTickerV3Api::set_askprice(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.askprice_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PublicBookTickerV3Api.askPrice)
}
inline ::std::string* PROTOBUF_NONNULL PublicBookTickerV3Api::mutable_askprice()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_askprice();
  // @@protoc_insertion_point(field_mutable:PublicBookTickerV3Api.askPrice)
  return _s;
}
inline const ::std::string& PublicBookTickerV3Api::_internal_askprice() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.askprice_.Get();
}
inline void PublicBookTickerV3Api::_internal_set_askprice(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.askprice_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PublicBookTickerV3Api::_internal_mutable_askprice() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.askprice_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PublicBookTickerV3Api::release_askprice() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PublicBookTickerV3Api.askPrice)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.askprice_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.askprice_.Set("", GetArena());
  }
  return released;
}
inline void PublicBookTickerV3Api::set_allocated_askprice(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.askprice_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.askprice_.IsDefault()) {
    _impl_.askprice_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:PublicBookTickerV3Api.askPrice)
}

// string askQuantity = 4;
inline void PublicBookTickerV3Api::clear_askquantity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.askquantity_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline const ::std::string& PublicBookTickerV3Api::askquantity() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PublicBookTickerV3Api.askQuantity)
  return _internal_askquantity();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PublicBookTickerV3Api::set_askquantity(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.askquantity_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:PublicBookTickerV3Api.askQuantity)
}
inline ::std::string* PROTOBUF_NONNULL PublicBookTickerV3Api::mutable_askquantity()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_askquantity();
  // @@protoc_insertion_point(field_mutable:PublicBookTickerV3Api.askQuantity)
  return _s;
}
inline const ::std::string& PublicBookTickerV3Api::_internal_askquantity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.askquantity_.Get();
}
inline void PublicBookTickerV3Api::_internal_set_askquantity(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.askquantity_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PublicBookTickerV3Api::_internal_mutable_askquantity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.askquantity_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PublicBookTickerV3Api::release_askquantity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PublicBookTickerV3Api.askQuantity)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.askquantity_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.askquantity_.Set("", GetArena());
  }
  return released;
}
inline void PublicBookTickerV3Api::set_allocated_askquantity(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.askquantity_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.askquantity_.IsDefault()) {
    _impl_.askquantity_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:PublicBookTickerV3Api.askQuantity)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // PublicBookTickerV3Api_2eproto_2epb_2eh
