// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PublicAggreDepthsV3Api.proto
// Protobuf C++ Version: 7.35.0

#include "PublicAggreDepthsV3Api.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::PublicAggreDepthsV3Api
        {&::_pbi::kDescriptorMethods, &::descriptor_table_PublicAggreDepthsV3Api_2eproto, /* tracker*/ nullptr,},
        // ::PublicAggreDepthV3ApiItem
        {&::_pbi::kDescriptorMethods, &::descriptor_table_PublicAggreDepthsV3Api_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
class PublicAggreDepthV3ApiItem::_Internal {
 public:
  using HasBits = decltype(::std::declval<PublicAggreDepthV3ApiItem>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PublicAggreDepthV3ApiItem, _impl_._has_bits_);
};

constexpr PublicAggreDepthV3ApiItem::ParseTableT_ PublicAggreDepthV3ApiItem::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(PublicAggreDepthV3ApiItem, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::PublicAggreDepthV3ApiItem>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // string quantity = 2;
      {::_pbi::TcParser::FastUS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(PublicAggreDepthV3ApiItem, _impl_.quantity_)}},
      // string price = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(PublicAggreDepthV3ApiItem, _impl_.price_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string price = 1;
      {PROTOBUF_FIELD_OFFSET(PublicAggreDepthV3ApiItem, _impl_.price_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string quantity = 2;
      {PROTOBUF_FIELD_OFFSET(PublicAggreDepthV3ApiItem, _impl_.quantity_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
      "\31\5\10\0\0\0\0\0"
      "PublicAggreDepthV3ApiItem"
      "price"
      "quantity"
    }},
  };
}


inline constexpr PublicAggreDepthV3ApiItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        price_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        quantity_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr PublicAggreDepthV3ApiItem::PublicAggreDepthV3ApiItem(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL PublicAggreDepthV3ApiItem::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PublicAggreDepthV3ApiItem(arena);
}
constexpr auto PublicAggreDepthV3ApiItem::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PublicAggreDepthV3ApiItem), alignof(PublicAggreDepthV3ApiItem));
}
constexpr auto PublicAggreDepthV3ApiItem::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &PublicAggreDepthV3ApiItem::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PublicAggreDepthV3ApiItem>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PublicAggreDepthV3ApiItem::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PublicAggreDepthV3ApiItem>(), &PublicAggreDepthV3ApiItem::ByteSizeLong,
              &PublicAggreDepthV3ApiItem::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PublicAggreDepthV3ApiItem, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_PublicAggreDepthsV3Api_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct PublicAggreDepthV3ApiItemGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr PublicAggreDepthV3ApiItemGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 PublicAggreDepthV3ApiItem_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(PublicAggreDepthV3ApiItem::InternalGenerateClassData_(
            _default, &PublicAggreDepthV3ApiItem_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<PublicAggreDepthV3ApiItem>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~PublicAggreDepthV3ApiItemGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) PublicAggreDepthV3ApiItem _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<PublicAggreDepthV3ApiItem>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(PublicAggreDepthV3ApiItemGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST PublicAggreDepthV3ApiItemGlobalsTypeInternal PublicAggreDepthV3ApiItem_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* PublicAggreDepthV3ApiItem_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return PublicAggreDepthV3ApiItem_globals_.GetClassData();
#else
  return PublicAggreDepthV3ApiItem_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class PublicAggreDepthsV3Api::_Internal {
 public:
  using HasBits = decltype(::std::declval<PublicAggreDepthsV3Api>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PublicAggreDepthsV3Api, _impl_._has_bits_);
};

constexpr PublicAggreDepthsV3Api::ParseTableT_ PublicAggreDepthsV3Api::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(PublicAggreDepthsV3Api, _impl_._has_bits_),
      0, // no _extensions_
      5, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967264,  // skipmap
      offsetof(ParseTableT_, field_entries),
      5,  // num_field_entries
      2,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::PublicAggreDepthsV3Api>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // repeated .PublicAggreDepthV3ApiItem asks = 1;
      {::_pbi::TcParser::FastMtR1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(PublicAggreDepthsV3Api, _impl_.asks_)}},
      // repeated .PublicAggreDepthV3ApiItem bids = 2;
      {::_pbi::TcParser::FastMtR1,
       {18, 1, 1,
        PROTOBUF_FIELD_OFFSET(PublicAggreDepthsV3Api, _impl_.bids_)}},
      // string eventType = 3;
      {::_pbi::TcParser::FastUS1,
       {26, 2, 0,
        PROTOBUF_FIELD_OFFSET(PublicAggreDepthsV3Api, _impl_.eventtype_)}},
      // string fromVersion = 4;
      {::_pbi::TcParser::FastUS1,
       {34, 3, 0,
        PROTOBUF_FIELD_OFFSET(PublicAggreDepthsV3Api, _impl_.fromversion_)}},
      // string toVersion = 5;
      {::_pbi::TcParser::FastUS1,
       {42, 4, 0,
        PROTOBUF_FIELD_OFFSET(PublicAggreDepthsV3Api, _impl_.toversion_)}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, {{
      // repeated .PublicAggreDepthV3ApiItem asks = 1;
      {PROTOBUF_FIELD_OFFSET(PublicAggreDepthsV3Api, _impl_.asks_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
      // repeated .PublicAggreDepthV3ApiItem bids = 2;
      {PROTOBUF_FIELD_OFFSET(PublicAggreDepthsV3Api, _impl_.bids_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
      // string eventType = 3;
      {PROTOBUF_FIELD_OFFSET(PublicAggreDepthsV3Api, _impl_.eventtype_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string fromVersion = 4;
      {PROTOBUF_FIELD_OFFSET(PublicAggreDepthsV3Api, _impl_.fromversion_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string toVersion = 5;
      {PROTOBUF_FIELD_OFFSET(PublicAggreDepthsV3Api, _impl_.toversion_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicAggreDepthV3ApiItem>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicAggreDepthV3ApiItem_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicAggreDepthV3ApiItem>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicAggreDepthV3ApiItem_globals_},
        #endif
    }},
    {{
      "\26\0\0\11\13\11\0\0"
      "PublicAggreDepthsV3Api"
      "eventType"
      "fromVersion"
      "toVersion"
    }},
  };
}


inline constexpr PublicAggreDepthsV3Api::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        asks_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::PublicAggreDepthsV3Api,
            PROTOBUF_FIELD_OFFSET(::PublicAggreDepthsV3Api, _impl_.asks_)>()
         }
        ,
        bids_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::PublicAggreDepthsV3Api,
            PROTOBUF_FIELD_OFFSET(::PublicAggreDepthsV3Api, _impl_.bids_)>()
         }
        ,
        eventtype_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        fromversion_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        toversion_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
constexpr PublicAggreDepthsV3Api::PublicAggreDepthsV3Api(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL PublicAggreDepthsV3Api::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PublicAggreDepthsV3Api(arena);
}
constexpr auto PublicAggreDepthsV3Api::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PublicAggreDepthsV3Api), alignof(PublicAggreDepthsV3Api));
}
constexpr auto PublicAggreDepthsV3Api::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &PublicAggreDepthsV3Api::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PublicAggreDepthsV3Api>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PublicAggreDepthsV3Api::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PublicAggreDepthsV3Api>(), &PublicAggreDepthsV3Api::ByteSizeLong,
              &PublicAggreDepthsV3Api::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PublicAggreDepthsV3Api, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_PublicAggreDepthsV3Api_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct PublicAggreDepthsV3ApiGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr PublicAggreDepthsV3ApiGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 PublicAggreDepthsV3Api_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(PublicAggreDepthsV3Api::InternalGenerateClassData_(
            _default, &PublicAggreDepthsV3Api_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<PublicAggreDepthsV3Api>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~PublicAggreDepthsV3ApiGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) PublicAggreDepthsV3Api _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<PublicAggreDepthsV3Api>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(PublicAggreDepthsV3ApiGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST PublicAggreDepthsV3ApiGlobalsTypeInternal PublicAggreDepthsV3Api_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* PublicAggreDepthsV3Api_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return PublicAggreDepthsV3Api_globals_.GetClassData();
#else
  return PublicAggreDepthsV3Api_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_PublicAggreDepthsV3Api_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_PublicAggreDepthsV3Api_2eproto = nullptr;
const ::uint32_t
    TableStruct_PublicAggreDepthsV3Api_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::PublicAggreDepthsV3Api, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::PublicAggreDepthsV3Api, _impl_.asks_),
        PROTOBUF_FIELD_OFFSET(::PublicAggreDepthsV3Api, _impl_.bids_),
        PROTOBUF_FIELD_OFFSET(::PublicAggreDepthsV3Api, _impl_.eventtype_),
        PROTOBUF_FIELD_OFFSET(::PublicAggreDepthsV3Api, _impl_.fromversion_),
        PROTOBUF_FIELD_OFFSET(::PublicAggreDepthsV3Api, _impl_.toversion_),
        0,
        1,
        2,
        3,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::PublicAggreDepthV3ApiItem, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::PublicAggreDepthV3ApiItem, _impl_.price_),
        PROTOBUF_FIELD_OFFSET(::PublicAggreDepthV3ApiItem, _impl_.quantity_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::PublicAggreDepthsV3Api)},
        {13, sizeof(::PublicAggreDepthV3ApiItem)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::PublicAggreDepthsV3Api_globals_,
        &::PublicAggreDepthV3ApiItem_globals_,
};
const char descriptor_table_protodef_PublicAggreDepthsV3Api_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\034PublicAggreDepthsV3Api.proto\"\247\001\n\026Publi"
    "cAggreDepthsV3Api\022(\n\004asks\030\001 \003(\0132\032.Public"
    "AggreDepthV3ApiItem\022(\n\004bids\030\002 \003(\0132\032.Publ"
    "icAggreDepthV3ApiItem\022\021\n\teventType\030\003 \001(\t"
    "\022\023\n\013fromVersion\030\004 \001(\t\022\021\n\ttoVersion\030\005 \001(\t"
    "\"<\n\031PublicAggreDepthV3ApiItem\022\r\n\005price\030\001"
    " \001(\t\022\020\n\010quantity\030\002 \001(\tB\?\n\034com.mxc.push.c"
    "ommon.protobufB\033PublicAggreDepthsV3ApiPr"
    "otoH\001P\001b\006proto3"
};
static ::absl::once_flag descriptor_table_PublicAggreDepthsV3Api_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_PublicAggreDepthsV3Api_2eproto = {
    false,
    false,
    335,
    descriptor_table_protodef_PublicAggreDepthsV3Api_2eproto,
    "PublicAggreDepthsV3Api.proto",
    &descriptor_table_PublicAggreDepthsV3Api_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_message_globals,
    TableStruct_PublicAggreDepthsV3Api_2eproto::offsets,
    file_level_enum_descriptors_PublicAggreDepthsV3Api_2eproto,
    file_level_service_descriptors_PublicAggreDepthsV3Api_2eproto,
};
// ===================================================================

PublicAggreDepthsV3Api::PublicAggreDepthsV3Api(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PublicAggreDepthsV3Api_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PublicAggreDepthsV3Api)
}
PROTOBUF_NDEBUG_INLINE PublicAggreDepthsV3Api::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::PublicAggreDepthsV3Api& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        asks_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::PublicAggreDepthsV3Api,
              PROTOBUF_FIELD_OFFSET(::PublicAggreDepthsV3Api, _impl_.asks_)>()
          , from.asks_
        }
        ,
        bids_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::PublicAggreDepthsV3Api,
              PROTOBUF_FIELD_OFFSET(::PublicAggreDepthsV3Api, _impl_.bids_)>()
          , from.bids_
        }
        ,
        eventtype_(arena, from.eventtype_),
        fromversion_(arena, from.fromversion_),
        toversion_(arena, from.toversion_) {}

PublicAggreDepthsV3Api::PublicAggreDepthsV3Api(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PublicAggreDepthsV3Api& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PublicAggreDepthsV3Api_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PublicAggreDepthsV3Api* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:PublicAggreDepthsV3Api)
}
PROTOBUF_NDEBUG_INLINE PublicAggreDepthsV3Api::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        asks_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::PublicAggreDepthsV3Api,
            PROTOBUF_FIELD_OFFSET(::PublicAggreDepthsV3Api, _impl_.asks_)>()
         }
        ,
        bids_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::PublicAggreDepthsV3Api,
            PROTOBUF_FIELD_OFFSET(::PublicAggreDepthsV3Api, _impl_.bids_)>()
         }
        ,
        eventtype_(arena),
        fromversion_(arena),
        toversion_(arena) {}

inline void PublicAggreDepthsV3Api::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PublicAggreDepthsV3Api::~PublicAggreDepthsV3Api() {
  // @@protoc_insertion_point(destructor:PublicAggreDepthsV3Api)
  SharedDtor(*this);
}
inline void PublicAggreDepthsV3Api::SharedDtor(MessageLite& self) {
  PublicAggreDepthsV3Api& this_ = static_cast<PublicAggreDepthsV3Api&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.eventtype_.Destroy();
  this_._impl_.fromversion_.Destroy();
  this_._impl_.toversion_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PublicAggreDepthsV3Api_class_data_ =
        PublicAggreDepthsV3Api::InternalGenerateClassData_(PublicAggreDepthsV3Api_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PublicAggreDepthsV3Api::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PublicAggreDepthsV3Api_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PublicAggreDepthsV3Api_class_data_.tc_table);
  return PublicAggreDepthsV3Api_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PublicAggreDepthsV3Api::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PublicAggreDepthsV3Api_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&PublicAggreDepthsV3Api_globals_));
  return PublicAggreDepthsV3Api_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const PublicAggreDepthsV3Api::ParseTableT_
    PublicAggreDepthsV3Api::_table_ =
        PublicAggreDepthsV3Api::InternalGenerateParseTable_(PublicAggreDepthsV3Api_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void PublicAggreDepthsV3Api::Clear() {
// @@protoc_insertion_point(message_clear_start:PublicAggreDepthsV3Api)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.asks_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.bids_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.eventtype_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.fromversion_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.toversion_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PublicAggreDepthsV3Api::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PublicAggreDepthsV3Api& this_ = static_cast<const PublicAggreDepthsV3Api&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PublicAggreDepthsV3Api::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PublicAggreDepthsV3Api& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:PublicAggreDepthsV3Api)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .PublicAggreDepthV3ApiItem asks = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_asks_size());
         i < n; i++) {
      const auto& repfield = this_._internal_asks().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // repeated .PublicAggreDepthV3ApiItem bids = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_bids_size());
         i < n; i++) {
      const auto& repfield = this_._internal_bids().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // string eventType = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_eventtype().empty()) {
      const ::std::string& _s = this_._internal_eventtype();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PublicAggreDepthsV3Api.eventType");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string fromVersion = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_fromversion().empty()) {
      const ::std::string& _s = this_._internal_fromversion();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PublicAggreDepthsV3Api.fromVersion");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // string toVersion = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_toversion().empty()) {
      const ::std::string& _s = this_._internal_toversion();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PublicAggreDepthsV3Api.toVersion");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PublicAggreDepthsV3Api)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PublicAggreDepthsV3Api::ByteSizeLong(const MessageLite& base) {
  const PublicAggreDepthsV3Api& this_ = static_cast<const PublicAggreDepthsV3Api&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PublicAggreDepthsV3Api::ByteSizeLong() const {
  const PublicAggreDepthsV3Api& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:PublicAggreDepthsV3Api)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // repeated .PublicAggreDepthV3ApiItem asks = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_asks_size();
      for (const auto& msg : this_._internal_asks()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .PublicAggreDepthV3ApiItem bids = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_bids_size();
      for (const auto& msg : this_._internal_bids()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // string eventType = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_eventtype().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_eventtype());
      }
    }
    // string fromVersion = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_fromversion().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_fromversion());
      }
    }
    // string toVersion = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!this_._internal_toversion().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_toversion());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PublicAggreDepthsV3Api::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<PublicAggreDepthsV3Api*>(&to_msg);
  auto& from = static_cast<const PublicAggreDepthsV3Api&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:PublicAggreDepthsV3Api)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_asks()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_asks());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_bids()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_bids());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_eventtype().empty()) {
        _this->_internal_set_eventtype(from._internal_eventtype());
      } else {
        if (_this->_impl_.eventtype_.IsDefault()) {
          _this->_internal_set_eventtype("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_fromversion().empty()) {
        _this->_internal_set_fromversion(from._internal_fromversion());
      } else {
        if (_this->_impl_.fromversion_.IsDefault()) {
          _this->_internal_set_fromversion("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!from._internal_toversion().empty()) {
        _this->_internal_set_toversion(from._internal_toversion());
      } else {
        if (_this->_impl_.toversion_.IsDefault()) {
          _this->_internal_set_toversion("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PublicAggreDepthsV3Api::CopyFrom(const PublicAggreDepthsV3Api& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:PublicAggreDepthsV3Api)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PublicAggreDepthsV3Api::InternalSwap(PublicAggreDepthsV3Api* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.asks_.InternalSwap(&other->_impl_.asks_);
  _impl_.bids_.InternalSwap(&other->_impl_.bids_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.eventtype_, &other->_impl_.eventtype_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.fromversion_, &other->_impl_.fromversion_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.toversion_, &other->_impl_.toversion_, arena);
}

::google::protobuf::Metadata PublicAggreDepthsV3Api::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

PublicAggreDepthV3ApiItem::PublicAggreDepthV3ApiItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PublicAggreDepthV3ApiItem_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PublicAggreDepthV3ApiItem)
}
PROTOBUF_NDEBUG_INLINE PublicAggreDepthV3ApiItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::PublicAggreDepthV3ApiItem& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        price_(arena, from.price_),
        quantity_(arena, from.quantity_) {}

PublicAggreDepthV3ApiItem::PublicAggreDepthV3ApiItem(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PublicAggreDepthV3ApiItem& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PublicAggreDepthV3ApiItem_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PublicAggreDepthV3ApiItem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:PublicAggreDepthV3ApiItem)
}
PROTOBUF_NDEBUG_INLINE PublicAggreDepthV3ApiItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        price_(arena),
        quantity_(arena) {}

inline void PublicAggreDepthV3ApiItem::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PublicAggreDepthV3ApiItem::~PublicAggreDepthV3ApiItem() {
  // @@protoc_insertion_point(destructor:PublicAggreDepthV3ApiItem)
  SharedDtor(*this);
}
inline void PublicAggreDepthV3ApiItem::SharedDtor(MessageLite& self) {
  PublicAggreDepthV3ApiItem& this_ = static_cast<PublicAggreDepthV3ApiItem&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.price_.Destroy();
  this_._impl_.quantity_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PublicAggreDepthV3ApiItem_class_data_ =
        PublicAggreDepthV3ApiItem::InternalGenerateClassData_(PublicAggreDepthV3ApiItem_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PublicAggreDepthV3ApiItem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PublicAggreDepthV3ApiItem_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PublicAggreDepthV3ApiItem_class_data_.tc_table);
  return PublicAggreDepthV3ApiItem_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PublicAggreDepthV3ApiItem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PublicAggreDepthV3ApiItem_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&PublicAggreDepthV3ApiItem_globals_));
  return PublicAggreDepthV3ApiItem_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const PublicAggreDepthV3ApiItem::ParseTableT_
    PublicAggreDepthV3ApiItem::_table_ =
        PublicAggreDepthV3ApiItem::InternalGenerateParseTable_(PublicAggreDepthV3ApiItem_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void PublicAggreDepthV3ApiItem::Clear() {
// @@protoc_insertion_point(message_clear_start:PublicAggreDepthV3ApiItem)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.price_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.quantity_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PublicAggreDepthV3ApiItem::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PublicAggreDepthV3ApiItem& this_ = static_cast<const PublicAggreDepthV3ApiItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PublicAggreDepthV3ApiItem::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PublicAggreDepthV3ApiItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:PublicAggreDepthV3ApiItem)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string price = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_price().empty()) {
      const ::std::string& _s = this_._internal_price();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PublicAggreDepthV3ApiItem.price");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string quantity = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_quantity().empty()) {
      const ::std::string& _s = this_._internal_quantity();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PublicAggreDepthV3ApiItem.quantity");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PublicAggreDepthV3ApiItem)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PublicAggreDepthV3ApiItem::ByteSizeLong(const MessageLite& base) {
  const PublicAggreDepthV3ApiItem& this_ = static_cast<const PublicAggreDepthV3ApiItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PublicAggreDepthV3ApiItem::ByteSizeLong() const {
  const PublicAggreDepthV3ApiItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:PublicAggreDepthV3ApiItem)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string price = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_price().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_price());
      }
    }
    // string quantity = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_quantity().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_quantity());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PublicAggreDepthV3ApiItem::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<PublicAggreDepthV3ApiItem*>(&to_msg);
  auto& from = static_cast<const PublicAggreDepthV3ApiItem&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:PublicAggreDepthV3ApiItem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_price().empty()) {
        _this->_internal_set_price(from._internal_price());
      } else {
        if (_this->_impl_.price_.IsDefault()) {
          _this->_internal_set_price("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_quantity().empty()) {
        _this->_internal_set_quantity(from._internal_quantity());
      } else {
        if (_this->_impl_.quantity_.IsDefault()) {
          _this->_internal_set_quantity("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PublicAggreDepthV3ApiItem::CopyFrom(const PublicAggreDepthV3ApiItem& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:PublicAggreDepthV3ApiItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PublicAggreDepthV3ApiItem::InternalSwap(PublicAggreDepthV3ApiItem* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.price_, &other->_impl_.price_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.quantity_, &other->_impl_.quantity_, arena);
}

::google::protobuf::Metadata PublicAggreDepthV3ApiItem::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_PublicAggreDepthsV3Api_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
