// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicMiniTickerV3Api.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PublicMiniTickerV3Api_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PublicMiniTickerV3Api_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PublicMiniTickerV3Api_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PublicMiniTickerV3Api_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PublicMiniTickerV3Api_2eproto;
class PublicMiniTickerV3Api;
class PublicMiniTickerV3ApiDefaultTypeInternal;
extern PublicMiniTickerV3ApiDefaultTypeInternal _PublicMiniTickerV3Api_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PublicMiniTickerV3Api* Arena::CreateMaybeMessage<::PublicMiniTickerV3Api>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class PublicMiniTickerV3Api PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PublicMiniTickerV3Api) */ {
 public:
  inline PublicMiniTickerV3Api() : PublicMiniTickerV3Api(nullptr) {};
  virtual ~PublicMiniTickerV3Api();

  PublicMiniTickerV3Api(const PublicMiniTickerV3Api& from);
  PublicMiniTickerV3Api(PublicMiniTickerV3Api&& from) noexcept
    : PublicMiniTickerV3Api() {
    *this = ::std::move(from);
  }

  inline PublicMiniTickerV3Api& operator=(const PublicMiniTickerV3Api& from) {
    CopyFrom(from);
    return *this;
  }
  inline PublicMiniTickerV3Api& operator=(PublicMiniTickerV3Api&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PublicMiniTickerV3Api& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PublicMiniTickerV3Api* internal_default_instance() {
    return reinterpret_cast<const PublicMiniTickerV3Api*>(
               &_PublicMiniTickerV3Api_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PublicMiniTickerV3Api& a, PublicMiniTickerV3Api& b) {
    a.Swap(&b);
  }
  inline void Swap(PublicMiniTickerV3Api* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PublicMiniTickerV3Api* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PublicMiniTickerV3Api* New() const final {
    return CreateMaybeMessage<PublicMiniTickerV3Api>(nullptr);
  }

  PublicMiniTickerV3Api* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PublicMiniTickerV3Api>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PublicMiniTickerV3Api& from);
  void MergeFrom(const PublicMiniTickerV3Api& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PublicMiniTickerV3Api* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PublicMiniTickerV3Api";
  }
  protected:
  explicit PublicMiniTickerV3Api(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PublicMiniTickerV3Api_2eproto);
    return ::descriptor_table_PublicMiniTickerV3Api_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSymbolFieldNumber = 1,
    kPriceFieldNumber = 2,
    kRateFieldNumber = 3,
    kZonedRateFieldNumber = 4,
    kHighFieldNumber = 5,
    kLowFieldNumber = 6,
    kVolumeFieldNumber = 7,
    kQuantityFieldNumber = 8,
    kLastCloseRateFieldNumber = 9,
    kLastCloseZonedRateFieldNumber = 10,
    kLastCloseHighFieldNumber = 11,
    kLastCloseLowFieldNumber = 12,
  };
  // string symbol = 1;
  void clear_symbol();
  const std::string& symbol() const;
  void set_symbol(const std::string& value);
  void set_symbol(std::string&& value);
  void set_symbol(const char* value);
  void set_symbol(const char* value, size_t size);
  std::string* mutable_symbol();
  std::string* release_symbol();
  void set_allocated_symbol(std::string* symbol);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_symbol();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_symbol(
      std::string* symbol);
  private:
  const std::string& _internal_symbol() const;
  void _internal_set_symbol(const std::string& value);
  std::string* _internal_mutable_symbol();
  public:

  // string price = 2;
  void clear_price();
  const std::string& price() const;
  void set_price(const std::string& value);
  void set_price(std::string&& value);
  void set_price(const char* value);
  void set_price(const char* value, size_t size);
  std::string* mutable_price();
  std::string* release_price();
  void set_allocated_price(std::string* price);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_price();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_price(
      std::string* price);
  private:
  const std::string& _internal_price() const;
  void _internal_set_price(const std::string& value);
  std::string* _internal_mutable_price();
  public:

  // string rate = 3;
  void clear_rate();
  const std::string& rate() const;
  void set_rate(const std::string& value);
  void set_rate(std::string&& value);
  void set_rate(const char* value);
  void set_rate(const char* value, size_t size);
  std::string* mutable_rate();
  std::string* release_rate();
  void set_allocated_rate(std::string* rate);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_rate();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_rate(
      std::string* rate);
  private:
  const std::string& _internal_rate() const;
  void _internal_set_rate(const std::string& value);
  std::string* _internal_mutable_rate();
  public:

  // string zonedRate = 4;
  void clear_zonedrate();
  const std::string& zonedrate() const;
  void set_zonedrate(const std::string& value);
  void set_zonedrate(std::string&& value);
  void set_zonedrate(const char* value);
  void set_zonedrate(const char* value, size_t size);
  std::string* mutable_zonedrate();
  std::string* release_zonedrate();
  void set_allocated_zonedrate(std::string* zonedrate);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_zonedrate();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_zonedrate(
      std::string* zonedrate);
  private:
  const std::string& _internal_zonedrate() const;
  void _internal_set_zonedrate(const std::string& value);
  std::string* _internal_mutable_zonedrate();
  public:

  // string high = 5;
  void clear_high();
  const std::string& high() const;
  void set_high(const std::string& value);
  void set_high(std::string&& value);
  void set_high(const char* value);
  void set_high(const char* value, size_t size);
  std::string* mutable_high();
  std::string* release_high();
  void set_allocated_high(std::string* high);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_high();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_high(
      std::string* high);
  private:
  const std::string& _internal_high() const;
  void _internal_set_high(const std::string& value);
  std::string* _internal_mutable_high();
  public:

  // string low = 6;
  void clear_low();
  const std::string& low() const;
  void set_low(const std::string& value);
  void set_low(std::string&& value);
  void set_low(const char* value);
  void set_low(const char* value, size_t size);
  std::string* mutable_low();
  std::string* release_low();
  void set_allocated_low(std::string* low);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_low();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_low(
      std::string* low);
  private:
  const std::string& _internal_low() const;
  void _internal_set_low(const std::string& value);
  std::string* _internal_mutable_low();
  public:

  // string volume = 7;
  void clear_volume();
  const std::string& volume() const;
  void set_volume(const std::string& value);
  void set_volume(std::string&& value);
  void set_volume(const char* value);
  void set_volume(const char* value, size_t size);
  std::string* mutable_volume();
  std::string* release_volume();
  void set_allocated_volume(std::string* volume);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_volume();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_volume(
      std::string* volume);
  private:
  const std::string& _internal_volume() const;
  void _internal_set_volume(const std::string& value);
  std::string* _internal_mutable_volume();
  public:

  // string quantity = 8;
  void clear_quantity();
  const std::string& quantity() const;
  void set_quantity(const std::string& value);
  void set_quantity(std::string&& value);
  void set_quantity(const char* value);
  void set_quantity(const char* value, size_t size);
  std::string* mutable_quantity();
  std::string* release_quantity();
  void set_allocated_quantity(std::string* quantity);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_quantity();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_quantity(
      std::string* quantity);
  private:
  const std::string& _internal_quantity() const;
  void _internal_set_quantity(const std::string& value);
  std::string* _internal_mutable_quantity();
  public:

  // string lastCloseRate = 9;
  void clear_lastcloserate();
  const std::string& lastcloserate() const;
  void set_lastcloserate(const std::string& value);
  void set_lastcloserate(std::string&& value);
  void set_lastcloserate(const char* value);
  void set_lastcloserate(const char* value, size_t size);
  std::string* mutable_lastcloserate();
  std::string* release_lastcloserate();
  void set_allocated_lastcloserate(std::string* lastcloserate);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_lastcloserate();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_lastcloserate(
      std::string* lastcloserate);
  private:
  const std::string& _internal_lastcloserate() const;
  void _internal_set_lastcloserate(const std::string& value);
  std::string* _internal_mutable_lastcloserate();
  public:

  // string lastCloseZonedRate = 10;
  void clear_lastclosezonedrate();
  const std::string& lastclosezonedrate() const;
  void set_lastclosezonedrate(const std::string& value);
  void set_lastclosezonedrate(std::string&& value);
  void set_lastclosezonedrate(const char* value);
  void set_lastclosezonedrate(const char* value, size_t size);
  std::string* mutable_lastclosezonedrate();
  std::string* release_lastclosezonedrate();
  void set_allocated_lastclosezonedrate(std::string* lastclosezonedrate);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_lastclosezonedrate();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_lastclosezonedrate(
      std::string* lastclosezonedrate);
  private:
  const std::string& _internal_lastclosezonedrate() const;
  void _internal_set_lastclosezonedrate(const std::string& value);
  std::string* _internal_mutable_lastclosezonedrate();
  public:

  // string lastCloseHigh = 11;
  void clear_lastclosehigh();
  const std::string& lastclosehigh() const;
  void set_lastclosehigh(const std::string& value);
  void set_lastclosehigh(std::string&& value);
  void set_lastclosehigh(const char* value);
  void set_lastclosehigh(const char* value, size_t size);
  std::string* mutable_lastclosehigh();
  std::string* release_lastclosehigh();
  void set_allocated_lastclosehigh(std::string* lastclosehigh);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_lastclosehigh();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_lastclosehigh(
      std::string* lastclosehigh);
  private:
  const std::string& _internal_lastclosehigh() const;
  void _internal_set_lastclosehigh(const std::string& value);
  std::string* _internal_mutable_lastclosehigh();
  public:

  // string lastCloseLow = 12;
  void clear_lastcloselow();
  const std::string& lastcloselow() const;
  void set_lastcloselow(const std::string& value);
  void set_lastcloselow(std::string&& value);
  void set_lastcloselow(const char* value);
  void set_lastcloselow(const char* value, size_t size);
  std::string* mutable_lastcloselow();
  std::string* release_lastcloselow();
  void set_allocated_lastcloselow(std::string* lastcloselow);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_lastcloselow();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_lastcloselow(
      std::string* lastcloselow);
  private:
  const std::string& _internal_lastcloselow() const;
  void _internal_set_lastcloselow(const std::string& value);
  std::string* _internal_mutable_lastcloselow();
  public:

  // @@protoc_insertion_point(class_scope:PublicMiniTickerV3Api)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr symbol_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr price_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr rate_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr zonedrate_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr high_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr low_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr volume_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr quantity_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lastcloserate_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lastclosezonedrate_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lastclosehigh_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lastcloselow_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PublicMiniTickerV3Api_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PublicMiniTickerV3Api

// string symbol = 1;
inline void PublicMiniTickerV3Api::clear_symbol() {
  symbol_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicMiniTickerV3Api::symbol() const {
  // @@protoc_insertion_point(field_get:PublicMiniTickerV3Api.symbol)
  return _internal_symbol();
}
inline void PublicMiniTickerV3Api::set_symbol(const std::string& value) {
  _internal_set_symbol(value);
  // @@protoc_insertion_point(field_set:PublicMiniTickerV3Api.symbol)
}
inline std::string* PublicMiniTickerV3Api::mutable_symbol() {
  // @@protoc_insertion_point(field_mutable:PublicMiniTickerV3Api.symbol)
  return _internal_mutable_symbol();
}
inline const std::string& PublicMiniTickerV3Api::_internal_symbol() const {
  return symbol_.Get();
}
inline void PublicMiniTickerV3Api::_internal_set_symbol(const std::string& value) {
  
  symbol_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicMiniTickerV3Api::set_symbol(std::string&& value) {
  
  symbol_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicMiniTickerV3Api.symbol)
}
inline void PublicMiniTickerV3Api::set_symbol(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  symbol_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicMiniTickerV3Api.symbol)
}
inline void PublicMiniTickerV3Api::set_symbol(const char* value,
    size_t size) {
  
  symbol_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicMiniTickerV3Api.symbol)
}
inline std::string* PublicMiniTickerV3Api::_internal_mutable_symbol() {
  
  return symbol_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicMiniTickerV3Api::release_symbol() {
  // @@protoc_insertion_point(field_release:PublicMiniTickerV3Api.symbol)
  return symbol_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicMiniTickerV3Api::set_allocated_symbol(std::string* symbol) {
  if (symbol != nullptr) {
    
  } else {
    
  }
  symbol_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), symbol,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicMiniTickerV3Api.symbol)
}
inline std::string* PublicMiniTickerV3Api::unsafe_arena_release_symbol() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicMiniTickerV3Api.symbol)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return symbol_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicMiniTickerV3Api::unsafe_arena_set_allocated_symbol(
    std::string* symbol) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (symbol != nullptr) {
    
  } else {
    
  }
  symbol_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      symbol, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicMiniTickerV3Api.symbol)
}

// string price = 2;
inline void PublicMiniTickerV3Api::clear_price() {
  price_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicMiniTickerV3Api::price() const {
  // @@protoc_insertion_point(field_get:PublicMiniTickerV3Api.price)
  return _internal_price();
}
inline void PublicMiniTickerV3Api::set_price(const std::string& value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:PublicMiniTickerV3Api.price)
}
inline std::string* PublicMiniTickerV3Api::mutable_price() {
  // @@protoc_insertion_point(field_mutable:PublicMiniTickerV3Api.price)
  return _internal_mutable_price();
}
inline const std::string& PublicMiniTickerV3Api::_internal_price() const {
  return price_.Get();
}
inline void PublicMiniTickerV3Api::_internal_set_price(const std::string& value) {
  
  price_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicMiniTickerV3Api::set_price(std::string&& value) {
  
  price_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicMiniTickerV3Api.price)
}
inline void PublicMiniTickerV3Api::set_price(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  price_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicMiniTickerV3Api.price)
}
inline void PublicMiniTickerV3Api::set_price(const char* value,
    size_t size) {
  
  price_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicMiniTickerV3Api.price)
}
inline std::string* PublicMiniTickerV3Api::_internal_mutable_price() {
  
  return price_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicMiniTickerV3Api::release_price() {
  // @@protoc_insertion_point(field_release:PublicMiniTickerV3Api.price)
  return price_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicMiniTickerV3Api::set_allocated_price(std::string* price) {
  if (price != nullptr) {
    
  } else {
    
  }
  price_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), price,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicMiniTickerV3Api.price)
}
inline std::string* PublicMiniTickerV3Api::unsafe_arena_release_price() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicMiniTickerV3Api.price)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return price_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicMiniTickerV3Api::unsafe_arena_set_allocated_price(
    std::string* price) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (price != nullptr) {
    
  } else {
    
  }
  price_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      price, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicMiniTickerV3Api.price)
}

// string rate = 3;
inline void PublicMiniTickerV3Api::clear_rate() {
  rate_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicMiniTickerV3Api::rate() const {
  // @@protoc_insertion_point(field_get:PublicMiniTickerV3Api.rate)
  return _internal_rate();
}
inline void PublicMiniTickerV3Api::set_rate(const std::string& value) {
  _internal_set_rate(value);
  // @@protoc_insertion_point(field_set:PublicMiniTickerV3Api.rate)
}
inline std::string* PublicMiniTickerV3Api::mutable_rate() {
  // @@protoc_insertion_point(field_mutable:PublicMiniTickerV3Api.rate)
  return _internal_mutable_rate();
}
inline const std::string& PublicMiniTickerV3Api::_internal_rate() const {
  return rate_.Get();
}
inline void PublicMiniTickerV3Api::_internal_set_rate(const std::string& value) {
  
  rate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicMiniTickerV3Api::set_rate(std::string&& value) {
  
  rate_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicMiniTickerV3Api.rate)
}
inline void PublicMiniTickerV3Api::set_rate(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  rate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicMiniTickerV3Api.rate)
}
inline void PublicMiniTickerV3Api::set_rate(const char* value,
    size_t size) {
  
  rate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicMiniTickerV3Api.rate)
}
inline std::string* PublicMiniTickerV3Api::_internal_mutable_rate() {
  
  return rate_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicMiniTickerV3Api::release_rate() {
  // @@protoc_insertion_point(field_release:PublicMiniTickerV3Api.rate)
  return rate_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicMiniTickerV3Api::set_allocated_rate(std::string* rate) {
  if (rate != nullptr) {
    
  } else {
    
  }
  rate_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), rate,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicMiniTickerV3Api.rate)
}
inline std::string* PublicMiniTickerV3Api::unsafe_arena_release_rate() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicMiniTickerV3Api.rate)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return rate_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicMiniTickerV3Api::unsafe_arena_set_allocated_rate(
    std::string* rate) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (rate != nullptr) {
    
  } else {
    
  }
  rate_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      rate, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicMiniTickerV3Api.rate)
}

// string zonedRate = 4;
inline void PublicMiniTickerV3Api::clear_zonedrate() {
  zonedrate_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicMiniTickerV3Api::zonedrate() const {
  // @@protoc_insertion_point(field_get:PublicMiniTickerV3Api.zonedRate)
  return _internal_zonedrate();
}
inline void PublicMiniTickerV3Api::set_zonedrate(const std::string& value) {
  _internal_set_zonedrate(value);
  // @@protoc_insertion_point(field_set:PublicMiniTickerV3Api.zonedRate)
}
inline std::string* PublicMiniTickerV3Api::mutable_zonedrate() {
  // @@protoc_insertion_point(field_mutable:PublicMiniTickerV3Api.zonedRate)
  return _internal_mutable_zonedrate();
}
inline const std::string& PublicMiniTickerV3Api::_internal_zonedrate() const {
  return zonedrate_.Get();
}
inline void PublicMiniTickerV3Api::_internal_set_zonedrate(const std::string& value) {
  
  zonedrate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicMiniTickerV3Api::set_zonedrate(std::string&& value) {
  
  zonedrate_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicMiniTickerV3Api.zonedRate)
}
inline void PublicMiniTickerV3Api::set_zonedrate(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  zonedrate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicMiniTickerV3Api.zonedRate)
}
inline void PublicMiniTickerV3Api::set_zonedrate(const char* value,
    size_t size) {
  
  zonedrate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicMiniTickerV3Api.zonedRate)
}
inline std::string* PublicMiniTickerV3Api::_internal_mutable_zonedrate() {
  
  return zonedrate_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicMiniTickerV3Api::release_zonedrate() {
  // @@protoc_insertion_point(field_release:PublicMiniTickerV3Api.zonedRate)
  return zonedrate_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicMiniTickerV3Api::set_allocated_zonedrate(std::string* zonedrate) {
  if (zonedrate != nullptr) {
    
  } else {
    
  }
  zonedrate_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), zonedrate,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicMiniTickerV3Api.zonedRate)
}
inline std::string* PublicMiniTickerV3Api::unsafe_arena_release_zonedrate() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicMiniTickerV3Api.zonedRate)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return zonedrate_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicMiniTickerV3Api::unsafe_arena_set_allocated_zonedrate(
    std::string* zonedrate) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (zonedrate != nullptr) {
    
  } else {
    
  }
  zonedrate_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      zonedrate, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicMiniTickerV3Api.zonedRate)
}

// string high = 5;
inline void PublicMiniTickerV3Api::clear_high() {
  high_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicMiniTickerV3Api::high() const {
  // @@protoc_insertion_point(field_get:PublicMiniTickerV3Api.high)
  return _internal_high();
}
inline void PublicMiniTickerV3Api::set_high(const std::string& value) {
  _internal_set_high(value);
  // @@protoc_insertion_point(field_set:PublicMiniTickerV3Api.high)
}
inline std::string* PublicMiniTickerV3Api::mutable_high() {
  // @@protoc_insertion_point(field_mutable:PublicMiniTickerV3Api.high)
  return _internal_mutable_high();
}
inline const std::string& PublicMiniTickerV3Api::_internal_high() const {
  return high_.Get();
}
inline void PublicMiniTickerV3Api::_internal_set_high(const std::string& value) {
  
  high_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicMiniTickerV3Api::set_high(std::string&& value) {
  
  high_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicMiniTickerV3Api.high)
}
inline void PublicMiniTickerV3Api::set_high(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  high_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicMiniTickerV3Api.high)
}
inline void PublicMiniTickerV3Api::set_high(const char* value,
    size_t size) {
  
  high_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicMiniTickerV3Api.high)
}
inline std::string* PublicMiniTickerV3Api::_internal_mutable_high() {
  
  return high_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicMiniTickerV3Api::release_high() {
  // @@protoc_insertion_point(field_release:PublicMiniTickerV3Api.high)
  return high_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicMiniTickerV3Api::set_allocated_high(std::string* high) {
  if (high != nullptr) {
    
  } else {
    
  }
  high_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), high,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicMiniTickerV3Api.high)
}
inline std::string* PublicMiniTickerV3Api::unsafe_arena_release_high() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicMiniTickerV3Api.high)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return high_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicMiniTickerV3Api::unsafe_arena_set_allocated_high(
    std::string* high) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (high != nullptr) {
    
  } else {
    
  }
  high_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      high, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicMiniTickerV3Api.high)
}

// string low = 6;
inline void PublicMiniTickerV3Api::clear_low() {
  low_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicMiniTickerV3Api::low() const {
  // @@protoc_insertion_point(field_get:PublicMiniTickerV3Api.low)
  return _internal_low();
}
inline void PublicMiniTickerV3Api::set_low(const std::string& value) {
  _internal_set_low(value);
  // @@protoc_insertion_point(field_set:PublicMiniTickerV3Api.low)
}
inline std::string* PublicMiniTickerV3Api::mutable_low() {
  // @@protoc_insertion_point(field_mutable:PublicMiniTickerV3Api.low)
  return _internal_mutable_low();
}
inline const std::string& PublicMiniTickerV3Api::_internal_low() const {
  return low_.Get();
}
inline void PublicMiniTickerV3Api::_internal_set_low(const std::string& value) {
  
  low_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicMiniTickerV3Api::set_low(std::string&& value) {
  
  low_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicMiniTickerV3Api.low)
}
inline void PublicMiniTickerV3Api::set_low(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  low_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicMiniTickerV3Api.low)
}
inline void PublicMiniTickerV3Api::set_low(const char* value,
    size_t size) {
  
  low_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicMiniTickerV3Api.low)
}
inline std::string* PublicMiniTickerV3Api::_internal_mutable_low() {
  
  return low_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicMiniTickerV3Api::release_low() {
  // @@protoc_insertion_point(field_release:PublicMiniTickerV3Api.low)
  return low_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicMiniTickerV3Api::set_allocated_low(std::string* low) {
  if (low != nullptr) {
    
  } else {
    
  }
  low_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), low,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicMiniTickerV3Api.low)
}
inline std::string* PublicMiniTickerV3Api::unsafe_arena_release_low() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicMiniTickerV3Api.low)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return low_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicMiniTickerV3Api::unsafe_arena_set_allocated_low(
    std::string* low) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (low != nullptr) {
    
  } else {
    
  }
  low_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      low, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicMiniTickerV3Api.low)
}

// string volume = 7;
inline void PublicMiniTickerV3Api::clear_volume() {
  volume_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicMiniTickerV3Api::volume() const {
  // @@protoc_insertion_point(field_get:PublicMiniTickerV3Api.volume)
  return _internal_volume();
}
inline void PublicMiniTickerV3Api::set_volume(const std::string& value) {
  _internal_set_volume(value);
  // @@protoc_insertion_point(field_set:PublicMiniTickerV3Api.volume)
}
inline std::string* PublicMiniTickerV3Api::mutable_volume() {
  // @@protoc_insertion_point(field_mutable:PublicMiniTickerV3Api.volume)
  return _internal_mutable_volume();
}
inline const std::string& PublicMiniTickerV3Api::_internal_volume() const {
  return volume_.Get();
}
inline void PublicMiniTickerV3Api::_internal_set_volume(const std::string& value) {
  
  volume_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicMiniTickerV3Api::set_volume(std::string&& value) {
  
  volume_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicMiniTickerV3Api.volume)
}
inline void PublicMiniTickerV3Api::set_volume(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  volume_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicMiniTickerV3Api.volume)
}
inline void PublicMiniTickerV3Api::set_volume(const char* value,
    size_t size) {
  
  volume_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicMiniTickerV3Api.volume)
}
inline std::string* PublicMiniTickerV3Api::_internal_mutable_volume() {
  
  return volume_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicMiniTickerV3Api::release_volume() {
  // @@protoc_insertion_point(field_release:PublicMiniTickerV3Api.volume)
  return volume_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicMiniTickerV3Api::set_allocated_volume(std::string* volume) {
  if (volume != nullptr) {
    
  } else {
    
  }
  volume_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), volume,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicMiniTickerV3Api.volume)
}
inline std::string* PublicMiniTickerV3Api::unsafe_arena_release_volume() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicMiniTickerV3Api.volume)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return volume_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicMiniTickerV3Api::unsafe_arena_set_allocated_volume(
    std::string* volume) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (volume != nullptr) {
    
  } else {
    
  }
  volume_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      volume, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicMiniTickerV3Api.volume)
}

// string quantity = 8;
inline void PublicMiniTickerV3Api::clear_quantity() {
  quantity_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicMiniTickerV3Api::quantity() const {
  // @@protoc_insertion_point(field_get:PublicMiniTickerV3Api.quantity)
  return _internal_quantity();
}
inline void PublicMiniTickerV3Api::set_quantity(const std::string& value) {
  _internal_set_quantity(value);
  // @@protoc_insertion_point(field_set:PublicMiniTickerV3Api.quantity)
}
inline std::string* PublicMiniTickerV3Api::mutable_quantity() {
  // @@protoc_insertion_point(field_mutable:PublicMiniTickerV3Api.quantity)
  return _internal_mutable_quantity();
}
inline const std::string& PublicMiniTickerV3Api::_internal_quantity() const {
  return quantity_.Get();
}
inline void PublicMiniTickerV3Api::_internal_set_quantity(const std::string& value) {
  
  quantity_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicMiniTickerV3Api::set_quantity(std::string&& value) {
  
  quantity_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicMiniTickerV3Api.quantity)
}
inline void PublicMiniTickerV3Api::set_quantity(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  quantity_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicMiniTickerV3Api.quantity)
}
inline void PublicMiniTickerV3Api::set_quantity(const char* value,
    size_t size) {
  
  quantity_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicMiniTickerV3Api.quantity)
}
inline std::string* PublicMiniTickerV3Api::_internal_mutable_quantity() {
  
  return quantity_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicMiniTickerV3Api::release_quantity() {
  // @@protoc_insertion_point(field_release:PublicMiniTickerV3Api.quantity)
  return quantity_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicMiniTickerV3Api::set_allocated_quantity(std::string* quantity) {
  if (quantity != nullptr) {
    
  } else {
    
  }
  quantity_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), quantity,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicMiniTickerV3Api.quantity)
}
inline std::string* PublicMiniTickerV3Api::unsafe_arena_release_quantity() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicMiniTickerV3Api.quantity)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return quantity_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicMiniTickerV3Api::unsafe_arena_set_allocated_quantity(
    std::string* quantity) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (quantity != nullptr) {
    
  } else {
    
  }
  quantity_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      quantity, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicMiniTickerV3Api.quantity)
}

// string lastCloseRate = 9;
inline void PublicMiniTickerV3Api::clear_lastcloserate() {
  lastcloserate_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicMiniTickerV3Api::lastcloserate() const {
  // @@protoc_insertion_point(field_get:PublicMiniTickerV3Api.lastCloseRate)
  return _internal_lastcloserate();
}
inline void PublicMiniTickerV3Api::set_lastcloserate(const std::string& value) {
  _internal_set_lastcloserate(value);
  // @@protoc_insertion_point(field_set:PublicMiniTickerV3Api.lastCloseRate)
}
inline std::string* PublicMiniTickerV3Api::mutable_lastcloserate() {
  // @@protoc_insertion_point(field_mutable:PublicMiniTickerV3Api.lastCloseRate)
  return _internal_mutable_lastcloserate();
}
inline const std::string& PublicMiniTickerV3Api::_internal_lastcloserate() const {
  return lastcloserate_.Get();
}
inline void PublicMiniTickerV3Api::_internal_set_lastcloserate(const std::string& value) {
  
  lastcloserate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicMiniTickerV3Api::set_lastcloserate(std::string&& value) {
  
  lastcloserate_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicMiniTickerV3Api.lastCloseRate)
}
inline void PublicMiniTickerV3Api::set_lastcloserate(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  lastcloserate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicMiniTickerV3Api.lastCloseRate)
}
inline void PublicMiniTickerV3Api::set_lastcloserate(const char* value,
    size_t size) {
  
  lastcloserate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicMiniTickerV3Api.lastCloseRate)
}
inline std::string* PublicMiniTickerV3Api::_internal_mutable_lastcloserate() {
  
  return lastcloserate_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicMiniTickerV3Api::release_lastcloserate() {
  // @@protoc_insertion_point(field_release:PublicMiniTickerV3Api.lastCloseRate)
  return lastcloserate_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicMiniTickerV3Api::set_allocated_lastcloserate(std::string* lastcloserate) {
  if (lastcloserate != nullptr) {
    
  } else {
    
  }
  lastcloserate_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), lastcloserate,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicMiniTickerV3Api.lastCloseRate)
}
inline std::string* PublicMiniTickerV3Api::unsafe_arena_release_lastcloserate() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicMiniTickerV3Api.lastCloseRate)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return lastcloserate_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicMiniTickerV3Api::unsafe_arena_set_allocated_lastcloserate(
    std::string* lastcloserate) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (lastcloserate != nullptr) {
    
  } else {
    
  }
  lastcloserate_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      lastcloserate, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicMiniTickerV3Api.lastCloseRate)
}

// string lastCloseZonedRate = 10;
inline void PublicMiniTickerV3Api::clear_lastclosezonedrate() {
  lastclosezonedrate_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicMiniTickerV3Api::lastclosezonedrate() const {
  // @@protoc_insertion_point(field_get:PublicMiniTickerV3Api.lastCloseZonedRate)
  return _internal_lastclosezonedrate();
}
inline void PublicMiniTickerV3Api::set_lastclosezonedrate(const std::string& value) {
  _internal_set_lastclosezonedrate(value);
  // @@protoc_insertion_point(field_set:PublicMiniTickerV3Api.lastCloseZonedRate)
}
inline std::string* PublicMiniTickerV3Api::mutable_lastclosezonedrate() {
  // @@protoc_insertion_point(field_mutable:PublicMiniTickerV3Api.lastCloseZonedRate)
  return _internal_mutable_lastclosezonedrate();
}
inline const std::string& PublicMiniTickerV3Api::_internal_lastclosezonedrate() const {
  return lastclosezonedrate_.Get();
}
inline void PublicMiniTickerV3Api::_internal_set_lastclosezonedrate(const std::string& value) {
  
  lastclosezonedrate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicMiniTickerV3Api::set_lastclosezonedrate(std::string&& value) {
  
  lastclosezonedrate_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicMiniTickerV3Api.lastCloseZonedRate)
}
inline void PublicMiniTickerV3Api::set_lastclosezonedrate(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  lastclosezonedrate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicMiniTickerV3Api.lastCloseZonedRate)
}
inline void PublicMiniTickerV3Api::set_lastclosezonedrate(const char* value,
    size_t size) {
  
  lastclosezonedrate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicMiniTickerV3Api.lastCloseZonedRate)
}
inline std::string* PublicMiniTickerV3Api::_internal_mutable_lastclosezonedrate() {
  
  return lastclosezonedrate_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicMiniTickerV3Api::release_lastclosezonedrate() {
  // @@protoc_insertion_point(field_release:PublicMiniTickerV3Api.lastCloseZonedRate)
  return lastclosezonedrate_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicMiniTickerV3Api::set_allocated_lastclosezonedrate(std::string* lastclosezonedrate) {
  if (lastclosezonedrate != nullptr) {
    
  } else {
    
  }
  lastclosezonedrate_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), lastclosezonedrate,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicMiniTickerV3Api.lastCloseZonedRate)
}
inline std::string* PublicMiniTickerV3Api::unsafe_arena_release_lastclosezonedrate() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicMiniTickerV3Api.lastCloseZonedRate)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return lastclosezonedrate_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicMiniTickerV3Api::unsafe_arena_set_allocated_lastclosezonedrate(
    std::string* lastclosezonedrate) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (lastclosezonedrate != nullptr) {
    
  } else {
    
  }
  lastclosezonedrate_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      lastclosezonedrate, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicMiniTickerV3Api.lastCloseZonedRate)
}

// string lastCloseHigh = 11;
inline void PublicMiniTickerV3Api::clear_lastclosehigh() {
  lastclosehigh_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicMiniTickerV3Api::lastclosehigh() const {
  // @@protoc_insertion_point(field_get:PublicMiniTickerV3Api.lastCloseHigh)
  return _internal_lastclosehigh();
}
inline void PublicMiniTickerV3Api::set_lastclosehigh(const std::string& value) {
  _internal_set_lastclosehigh(value);
  // @@protoc_insertion_point(field_set:PublicMiniTickerV3Api.lastCloseHigh)
}
inline std::string* PublicMiniTickerV3Api::mutable_lastclosehigh() {
  // @@protoc_insertion_point(field_mutable:PublicMiniTickerV3Api.lastCloseHigh)
  return _internal_mutable_lastclosehigh();
}
inline const std::string& PublicMiniTickerV3Api::_internal_lastclosehigh() const {
  return lastclosehigh_.Get();
}
inline void PublicMiniTickerV3Api::_internal_set_lastclosehigh(const std::string& value) {
  
  lastclosehigh_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicMiniTickerV3Api::set_lastclosehigh(std::string&& value) {
  
  lastclosehigh_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicMiniTickerV3Api.lastCloseHigh)
}
inline void PublicMiniTickerV3Api::set_lastclosehigh(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  lastclosehigh_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicMiniTickerV3Api.lastCloseHigh)
}
inline void PublicMiniTickerV3Api::set_lastclosehigh(const char* value,
    size_t size) {
  
  lastclosehigh_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicMiniTickerV3Api.lastCloseHigh)
}
inline std::string* PublicMiniTickerV3Api::_internal_mutable_lastclosehigh() {
  
  return lastclosehigh_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicMiniTickerV3Api::release_lastclosehigh() {
  // @@protoc_insertion_point(field_release:PublicMiniTickerV3Api.lastCloseHigh)
  return lastclosehigh_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicMiniTickerV3Api::set_allocated_lastclosehigh(std::string* lastclosehigh) {
  if (lastclosehigh != nullptr) {
    
  } else {
    
  }
  lastclosehigh_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), lastclosehigh,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicMiniTickerV3Api.lastCloseHigh)
}
inline std::string* PublicMiniTickerV3Api::unsafe_arena_release_lastclosehigh() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicMiniTickerV3Api.lastCloseHigh)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return lastclosehigh_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicMiniTickerV3Api::unsafe_arena_set_allocated_lastclosehigh(
    std::string* lastclosehigh) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (lastclosehigh != nullptr) {
    
  } else {
    
  }
  lastclosehigh_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      lastclosehigh, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicMiniTickerV3Api.lastCloseHigh)
}

// string lastCloseLow = 12;
inline void PublicMiniTickerV3Api::clear_lastcloselow() {
  lastcloselow_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicMiniTickerV3Api::lastcloselow() const {
  // @@protoc_insertion_point(field_get:PublicMiniTickerV3Api.lastCloseLow)
  return _internal_lastcloselow();
}
inline void PublicMiniTickerV3Api::set_lastcloselow(const std::string& value) {
  _internal_set_lastcloselow(value);
  // @@protoc_insertion_point(field_set:PublicMiniTickerV3Api.lastCloseLow)
}
inline std::string* PublicMiniTickerV3Api::mutable_lastcloselow() {
  // @@protoc_insertion_point(field_mutable:PublicMiniTickerV3Api.lastCloseLow)
  return _internal_mutable_lastcloselow();
}
inline const std::string& PublicMiniTickerV3Api::_internal_lastcloselow() const {
  return lastcloselow_.Get();
}
inline void PublicMiniTickerV3Api::_internal_set_lastcloselow(const std::string& value) {
  
  lastcloselow_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicMiniTickerV3Api::set_lastcloselow(std::string&& value) {
  
  lastcloselow_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicMiniTickerV3Api.lastCloseLow)
}
inline void PublicMiniTickerV3Api::set_lastcloselow(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  lastcloselow_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicMiniTickerV3Api.lastCloseLow)
}
inline void PublicMiniTickerV3Api::set_lastcloselow(const char* value,
    size_t size) {
  
  lastcloselow_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicMiniTickerV3Api.lastCloseLow)
}
inline std::string* PublicMiniTickerV3Api::_internal_mutable_lastcloselow() {
  
  return lastcloselow_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicMiniTickerV3Api::release_lastcloselow() {
  // @@protoc_insertion_point(field_release:PublicMiniTickerV3Api.lastCloseLow)
  return lastcloselow_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicMiniTickerV3Api::set_allocated_lastcloselow(std::string* lastcloselow) {
  if (lastcloselow != nullptr) {
    
  } else {
    
  }
  lastcloselow_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), lastcloselow,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicMiniTickerV3Api.lastCloseLow)
}
inline std::string* PublicMiniTickerV3Api::unsafe_arena_release_lastcloselow() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicMiniTickerV3Api.lastCloseLow)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return lastcloselow_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicMiniTickerV3Api::unsafe_arena_set_allocated_lastcloselow(
    std::string* lastcloselow) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (lastcloselow != nullptr) {
    
  } else {
    
  }
  lastcloselow_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      lastcloselow, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicMiniTickerV3Api.lastCloseLow)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PublicMiniTickerV3Api_2eproto
