// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PublicBookTickerV3Api.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PublicBookTickerV3Api_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PublicBookTickerV3Api_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PublicBookTickerV3Api_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PublicBookTickerV3Api_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PublicBookTickerV3Api_2eproto;
class PublicBookTickerV3Api;
class PublicBookTickerV3ApiDefaultTypeInternal;
extern PublicBookTickerV3ApiDefaultTypeInternal _PublicBookTickerV3Api_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PublicBookTickerV3Api* Arena::CreateMaybeMessage<::PublicBookTickerV3Api>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class PublicBookTickerV3Api PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PublicBookTickerV3Api) */ {
 public:
  inline PublicBookTickerV3Api() : PublicBookTickerV3Api(nullptr) {};
  virtual ~PublicBookTickerV3Api();

  PublicBookTickerV3Api(const PublicBookTickerV3Api& from);
  PublicBookTickerV3Api(PublicBookTickerV3Api&& from) noexcept
    : PublicBookTickerV3Api() {
    *this = ::std::move(from);
  }

  inline PublicBookTickerV3Api& operator=(const PublicBookTickerV3Api& from) {
    CopyFrom(from);
    return *this;
  }
  inline PublicBookTickerV3Api& operator=(PublicBookTickerV3Api&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PublicBookTickerV3Api& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PublicBookTickerV3Api* internal_default_instance() {
    return reinterpret_cast<const PublicBookTickerV3Api*>(
               &_PublicBookTickerV3Api_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PublicBookTickerV3Api& a, PublicBookTickerV3Api& b) {
    a.Swap(&b);
  }
  inline void Swap(PublicBookTickerV3Api* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PublicBookTickerV3Api* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PublicBookTickerV3Api* New() const final {
    return CreateMaybeMessage<PublicBookTickerV3Api>(nullptr);
  }

  PublicBookTickerV3Api* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PublicBookTickerV3Api>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PublicBookTickerV3Api& from);
  void MergeFrom(const PublicBookTickerV3Api& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PublicBookTickerV3Api* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PublicBookTickerV3Api";
  }
  protected:
  explicit PublicBookTickerV3Api(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_PublicBookTickerV3Api_2eproto);
    return ::descriptor_table_PublicBookTickerV3Api_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBidPriceFieldNumber = 1,
    kBidQuantityFieldNumber = 2,
    kAskPriceFieldNumber = 3,
    kAskQuantityFieldNumber = 4,
  };
  // string bidPrice = 1;
  void clear_bidprice();
  const std::string& bidprice() const;
  void set_bidprice(const std::string& value);
  void set_bidprice(std::string&& value);
  void set_bidprice(const char* value);
  void set_bidprice(const char* value, size_t size);
  std::string* mutable_bidprice();
  std::string* release_bidprice();
  void set_allocated_bidprice(std::string* bidprice);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_bidprice();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_bidprice(
      std::string* bidprice);
  private:
  const std::string& _internal_bidprice() const;
  void _internal_set_bidprice(const std::string& value);
  std::string* _internal_mutable_bidprice();
  public:

  // string bidQuantity = 2;
  void clear_bidquantity();
  const std::string& bidquantity() const;
  void set_bidquantity(const std::string& value);
  void set_bidquantity(std::string&& value);
  void set_bidquantity(const char* value);
  void set_bidquantity(const char* value, size_t size);
  std::string* mutable_bidquantity();
  std::string* release_bidquantity();
  void set_allocated_bidquantity(std::string* bidquantity);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_bidquantity();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_bidquantity(
      std::string* bidquantity);
  private:
  const std::string& _internal_bidquantity() const;
  void _internal_set_bidquantity(const std::string& value);
  std::string* _internal_mutable_bidquantity();
  public:

  // string askPrice = 3;
  void clear_askprice();
  const std::string& askprice() const;
  void set_askprice(const std::string& value);
  void set_askprice(std::string&& value);
  void set_askprice(const char* value);
  void set_askprice(const char* value, size_t size);
  std::string* mutable_askprice();
  std::string* release_askprice();
  void set_allocated_askprice(std::string* askprice);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_askprice();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_askprice(
      std::string* askprice);
  private:
  const std::string& _internal_askprice() const;
  void _internal_set_askprice(const std::string& value);
  std::string* _internal_mutable_askprice();
  public:

  // string askQuantity = 4;
  void clear_askquantity();
  const std::string& askquantity() const;
  void set_askquantity(const std::string& value);
  void set_askquantity(std::string&& value);
  void set_askquantity(const char* value);
  void set_askquantity(const char* value, size_t size);
  std::string* mutable_askquantity();
  std::string* release_askquantity();
  void set_allocated_askquantity(std::string* askquantity);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_askquantity();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_askquantity(
      std::string* askquantity);
  private:
  const std::string& _internal_askquantity() const;
  void _internal_set_askquantity(const std::string& value);
  std::string* _internal_mutable_askquantity();
  public:

  // @@protoc_insertion_point(class_scope:PublicBookTickerV3Api)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bidprice_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bidquantity_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr askprice_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr askquantity_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_PublicBookTickerV3Api_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PublicBookTickerV3Api

// string bidPrice = 1;
inline void PublicBookTickerV3Api::clear_bidprice() {
  bidprice_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicBookTickerV3Api::bidprice() const {
  // @@protoc_insertion_point(field_get:PublicBookTickerV3Api.bidPrice)
  return _internal_bidprice();
}
inline void PublicBookTickerV3Api::set_bidprice(const std::string& value) {
  _internal_set_bidprice(value);
  // @@protoc_insertion_point(field_set:PublicBookTickerV3Api.bidPrice)
}
inline std::string* PublicBookTickerV3Api::mutable_bidprice() {
  // @@protoc_insertion_point(field_mutable:PublicBookTickerV3Api.bidPrice)
  return _internal_mutable_bidprice();
}
inline const std::string& PublicBookTickerV3Api::_internal_bidprice() const {
  return bidprice_.Get();
}
inline void PublicBookTickerV3Api::_internal_set_bidprice(const std::string& value) {
  
  bidprice_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicBookTickerV3Api::set_bidprice(std::string&& value) {
  
  bidprice_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicBookTickerV3Api.bidPrice)
}
inline void PublicBookTickerV3Api::set_bidprice(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  bidprice_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicBookTickerV3Api.bidPrice)
}
inline void PublicBookTickerV3Api::set_bidprice(const char* value,
    size_t size) {
  
  bidprice_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicBookTickerV3Api.bidPrice)
}
inline std::string* PublicBookTickerV3Api::_internal_mutable_bidprice() {
  
  return bidprice_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicBookTickerV3Api::release_bidprice() {
  // @@protoc_insertion_point(field_release:PublicBookTickerV3Api.bidPrice)
  return bidprice_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicBookTickerV3Api::set_allocated_bidprice(std::string* bidprice) {
  if (bidprice != nullptr) {
    
  } else {
    
  }
  bidprice_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), bidprice,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicBookTickerV3Api.bidPrice)
}
inline std::string* PublicBookTickerV3Api::unsafe_arena_release_bidprice() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicBookTickerV3Api.bidPrice)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return bidprice_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicBookTickerV3Api::unsafe_arena_set_allocated_bidprice(
    std::string* bidprice) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (bidprice != nullptr) {
    
  } else {
    
  }
  bidprice_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      bidprice, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicBookTickerV3Api.bidPrice)
}

// string bidQuantity = 2;
inline void PublicBookTickerV3Api::clear_bidquantity() {
  bidquantity_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicBookTickerV3Api::bidquantity() const {
  // @@protoc_insertion_point(field_get:PublicBookTickerV3Api.bidQuantity)
  return _internal_bidquantity();
}
inline void PublicBookTickerV3Api::set_bidquantity(const std::string& value) {
  _internal_set_bidquantity(value);
  // @@protoc_insertion_point(field_set:PublicBookTickerV3Api.bidQuantity)
}
inline std::string* PublicBookTickerV3Api::mutable_bidquantity() {
  // @@protoc_insertion_point(field_mutable:PublicBookTickerV3Api.bidQuantity)
  return _internal_mutable_bidquantity();
}
inline const std::string& PublicBookTickerV3Api::_internal_bidquantity() const {
  return bidquantity_.Get();
}
inline void PublicBookTickerV3Api::_internal_set_bidquantity(const std::string& value) {
  
  bidquantity_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicBookTickerV3Api::set_bidquantity(std::string&& value) {
  
  bidquantity_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicBookTickerV3Api.bidQuantity)
}
inline void PublicBookTickerV3Api::set_bidquantity(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  bidquantity_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicBookTickerV3Api.bidQuantity)
}
inline void PublicBookTickerV3Api::set_bidquantity(const char* value,
    size_t size) {
  
  bidquantity_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicBookTickerV3Api.bidQuantity)
}
inline std::string* PublicBookTickerV3Api::_internal_mutable_bidquantity() {
  
  return bidquantity_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicBookTickerV3Api::release_bidquantity() {
  // @@protoc_insertion_point(field_release:PublicBookTickerV3Api.bidQuantity)
  return bidquantity_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicBookTickerV3Api::set_allocated_bidquantity(std::string* bidquantity) {
  if (bidquantity != nullptr) {
    
  } else {
    
  }
  bidquantity_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), bidquantity,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicBookTickerV3Api.bidQuantity)
}
inline std::string* PublicBookTickerV3Api::unsafe_arena_release_bidquantity() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicBookTickerV3Api.bidQuantity)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return bidquantity_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicBookTickerV3Api::unsafe_arena_set_allocated_bidquantity(
    std::string* bidquantity) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (bidquantity != nullptr) {
    
  } else {
    
  }
  bidquantity_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      bidquantity, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicBookTickerV3Api.bidQuantity)
}

// string askPrice = 3;
inline void PublicBookTickerV3Api::clear_askprice() {
  askprice_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicBookTickerV3Api::askprice() const {
  // @@protoc_insertion_point(field_get:PublicBookTickerV3Api.askPrice)
  return _internal_askprice();
}
inline void PublicBookTickerV3Api::set_askprice(const std::string& value) {
  _internal_set_askprice(value);
  // @@protoc_insertion_point(field_set:PublicBookTickerV3Api.askPrice)
}
inline std::string* PublicBookTickerV3Api::mutable_askprice() {
  // @@protoc_insertion_point(field_mutable:PublicBookTickerV3Api.askPrice)
  return _internal_mutable_askprice();
}
inline const std::string& PublicBookTickerV3Api::_internal_askprice() const {
  return askprice_.Get();
}
inline void PublicBookTickerV3Api::_internal_set_askprice(const std::string& value) {
  
  askprice_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicBookTickerV3Api::set_askprice(std::string&& value) {
  
  askprice_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicBookTickerV3Api.askPrice)
}
inline void PublicBookTickerV3Api::set_askprice(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  askprice_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicBookTickerV3Api.askPrice)
}
inline void PublicBookTickerV3Api::set_askprice(const char* value,
    size_t size) {
  
  askprice_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicBookTickerV3Api.askPrice)
}
inline std::string* PublicBookTickerV3Api::_internal_mutable_askprice() {
  
  return askprice_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicBookTickerV3Api::release_askprice() {
  // @@protoc_insertion_point(field_release:PublicBookTickerV3Api.askPrice)
  return askprice_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicBookTickerV3Api::set_allocated_askprice(std::string* askprice) {
  if (askprice != nullptr) {
    
  } else {
    
  }
  askprice_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), askprice,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicBookTickerV3Api.askPrice)
}
inline std::string* PublicBookTickerV3Api::unsafe_arena_release_askprice() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicBookTickerV3Api.askPrice)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return askprice_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicBookTickerV3Api::unsafe_arena_set_allocated_askprice(
    std::string* askprice) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (askprice != nullptr) {
    
  } else {
    
  }
  askprice_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      askprice, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicBookTickerV3Api.askPrice)
}

// string askQuantity = 4;
inline void PublicBookTickerV3Api::clear_askquantity() {
  askquantity_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PublicBookTickerV3Api::askquantity() const {
  // @@protoc_insertion_point(field_get:PublicBookTickerV3Api.askQuantity)
  return _internal_askquantity();
}
inline void PublicBookTickerV3Api::set_askquantity(const std::string& value) {
  _internal_set_askquantity(value);
  // @@protoc_insertion_point(field_set:PublicBookTickerV3Api.askQuantity)
}
inline std::string* PublicBookTickerV3Api::mutable_askquantity() {
  // @@protoc_insertion_point(field_mutable:PublicBookTickerV3Api.askQuantity)
  return _internal_mutable_askquantity();
}
inline const std::string& PublicBookTickerV3Api::_internal_askquantity() const {
  return askquantity_.Get();
}
inline void PublicBookTickerV3Api::_internal_set_askquantity(const std::string& value) {
  
  askquantity_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PublicBookTickerV3Api::set_askquantity(std::string&& value) {
  
  askquantity_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PublicBookTickerV3Api.askQuantity)
}
inline void PublicBookTickerV3Api::set_askquantity(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  askquantity_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:PublicBookTickerV3Api.askQuantity)
}
inline void PublicBookTickerV3Api::set_askquantity(const char* value,
    size_t size) {
  
  askquantity_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PublicBookTickerV3Api.askQuantity)
}
inline std::string* PublicBookTickerV3Api::_internal_mutable_askquantity() {
  
  return askquantity_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PublicBookTickerV3Api::release_askquantity() {
  // @@protoc_insertion_point(field_release:PublicBookTickerV3Api.askQuantity)
  return askquantity_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PublicBookTickerV3Api::set_allocated_askquantity(std::string* askquantity) {
  if (askquantity != nullptr) {
    
  } else {
    
  }
  askquantity_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), askquantity,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PublicBookTickerV3Api.askQuantity)
}
inline std::string* PublicBookTickerV3Api::unsafe_arena_release_askquantity() {
  // @@protoc_insertion_point(field_unsafe_arena_release:PublicBookTickerV3Api.askQuantity)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return askquantity_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PublicBookTickerV3Api::unsafe_arena_set_allocated_askquantity(
    std::string* askquantity) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (askquantity != nullptr) {
    
  } else {
    
  }
  askquantity_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      askquantity, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PublicBookTickerV3Api.askQuantity)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PublicBookTickerV3Api_2eproto
