// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PushDataV3ApiWrapper.proto
// Protobuf C++ Version: 7.35.0

#include "PushDataV3ApiWrapper.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::PushDataV3ApiWrapper
        {&::_pbi::kDescriptorMethods, &::descriptor_table_PushDataV3ApiWrapper_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
class PushDataV3ApiWrapper::_Internal {
 public:
  using HasBits = decltype(::std::declval<PushDataV3ApiWrapper>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_._oneof_case_);
};

constexpr PushDataV3ApiWrapper::ParseTableT_ PushDataV3ApiWrapper::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_._has_bits_),
      0, // no _extensions_
      315, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967234,  // skipmap
      offsetof(ParseTableT_, field_entries),
      20,  // num_field_entries
      15,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::PushDataV3ApiWrapper>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // string channel = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.channel_)}},
      {::_pbi::TcParser::MiniParse, {}},
      // optional string symbol = 3;
      {::_pbi::TcParser::FastUS1,
       {26, 1, 0,
        PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.symbol_)}},
      // optional string symbolId = 4;
      {::_pbi::TcParser::FastUS1,
       {34, 2, 0,
        PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.symbolid_)}},
      // optional int64 createTime = 5;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PushDataV3ApiWrapper, _impl_.createtime_), 3>(),
       {40, 3, 0,
        PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.createtime_)}},
      // optional int64 sendTime = 6;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PushDataV3ApiWrapper, _impl_.sendtime_), 4>(),
       {48, 4, 0,
        PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.sendtime_)}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      301, 0, 1,
      32768, 5,
      65535, 65535
    }}, {{
      // string channel = 1;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.channel_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // optional string symbol = 3;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.symbol_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // optional string symbolId = 4;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.symbolid_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // optional int64 createTime = 5;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.createtime_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // optional int64 sendTime = 6;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.sendtime_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // .PublicDealsV3Api publicDeals = 301;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.publicdeals_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
      // .PublicIncreaseDepthsV3Api publicIncreaseDepths = 302;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.publicincreasedepths_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
      // .PublicLimitDepthsV3Api publicLimitDepths = 303;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.publiclimitdepths_), _Internal::kOneofCaseOffset + 0, 2, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
      // .PrivateOrdersV3Api privateOrders = 304;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.privateorders_), _Internal::kOneofCaseOffset + 0, 3, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
      // .PublicBookTickerV3Api publicBookTicker = 305;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.publicbookticker_), _Internal::kOneofCaseOffset + 0, 4, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
      // .PrivateDealsV3Api privateDeals = 306;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.privatedeals_), _Internal::kOneofCaseOffset + 0, 5, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
      // .PrivateAccountV3Api privateAccount = 307;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.privateaccount_), _Internal::kOneofCaseOffset + 0, 6, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
      // .PublicSpotKlineV3Api publicSpotKline = 308;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.publicspotkline_), _Internal::kOneofCaseOffset + 0, 7, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
      // .PublicMiniTickerV3Api publicMiniTicker = 309;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.publicminiticker_), _Internal::kOneofCaseOffset + 0, 8, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
      // .PublicMiniTickersV3Api publicMiniTickers = 310;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.publicminitickers_), _Internal::kOneofCaseOffset + 0, 9, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
      // .PublicBookTickerBatchV3Api publicBookTickerBatch = 311;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.publicbooktickerbatch_), _Internal::kOneofCaseOffset + 0, 10, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
      // .PublicIncreaseDepthsBatchV3Api publicIncreaseDepthsBatch = 312;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.publicincreasedepthsbatch_), _Internal::kOneofCaseOffset + 0, 11, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
      // .PublicAggreDepthsV3Api publicAggreDepths = 313;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.publicaggredepths_), _Internal::kOneofCaseOffset + 0, 12, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
      // .PublicAggreDealsV3Api publicAggreDeals = 314;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.publicaggredeals_), _Internal::kOneofCaseOffset + 0, 13, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
      // .PublicAggreBookTickerV3Api publicAggreBookTicker = 315;
      {PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.body_.publicaggrebookticker_), _Internal::kOneofCaseOffset + 0, 14, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicDealsV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicDealsV3Api_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicIncreaseDepthsV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicIncreaseDepthsV3Api_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicLimitDepthsV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicLimitDepthsV3Api_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PrivateOrdersV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PrivateOrdersV3Api_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicBookTickerV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicBookTickerV3Api_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PrivateDealsV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PrivateDealsV3Api_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PrivateAccountV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PrivateAccountV3Api_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicSpotKlineV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicSpotKlineV3Api_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicMiniTickerV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicMiniTickerV3Api_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicMiniTickersV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicMiniTickersV3Api_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicBookTickerBatchV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicBookTickerBatchV3Api_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicIncreaseDepthsBatchV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicIncreaseDepthsBatchV3Api_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicAggreDepthsV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicAggreDepthsV3Api_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicAggreDealsV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicAggreDealsV3Api_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::PublicAggreBookTickerV3Api>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::PublicAggreBookTickerV3Api_globals_},
        #endif
    }},
    {{
      "\24\7\6\10\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
      "PushDataV3ApiWrapper"
      "channel"
      "symbol"
      "symbolId"
    }},
  };
}


inline constexpr PushDataV3ApiWrapper::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        channel_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        symbol_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        symbolid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        createtime_{::int64_t{0}},
        sendtime_{::int64_t{0}},
        body_{},
        _oneof_case_{} {}

template <typename>
constexpr PushDataV3ApiWrapper::PushDataV3ApiWrapper(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL PushDataV3ApiWrapper::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PushDataV3ApiWrapper(arena);
}
constexpr auto PushDataV3ApiWrapper::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PushDataV3ApiWrapper), alignof(PushDataV3ApiWrapper));
}
constexpr auto PushDataV3ApiWrapper::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &PushDataV3ApiWrapper::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PushDataV3ApiWrapper>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PushDataV3ApiWrapper::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PushDataV3ApiWrapper>(), &PushDataV3ApiWrapper::ByteSizeLong,
              &PushDataV3ApiWrapper::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_PushDataV3ApiWrapper_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct PushDataV3ApiWrapperGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr PushDataV3ApiWrapperGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 PushDataV3ApiWrapper_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(PushDataV3ApiWrapper::InternalGenerateClassData_(
            _default, &PushDataV3ApiWrapper_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<PushDataV3ApiWrapper>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~PushDataV3ApiWrapperGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) PushDataV3ApiWrapper _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<PushDataV3ApiWrapper>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapperGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST PushDataV3ApiWrapperGlobalsTypeInternal PushDataV3ApiWrapper_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* PushDataV3ApiWrapper_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return PushDataV3ApiWrapper_globals_.GetClassData();
#else
  return PushDataV3ApiWrapper_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_PushDataV3ApiWrapper_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_PushDataV3ApiWrapper_2eproto = nullptr;
const ::uint32_t
    TableStruct_PushDataV3ApiWrapper_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x085, // bitmap
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_._oneof_case_[0]),
        25, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.channel_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.symbol_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.symbolid_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.createtime_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.sendtime_),
        PROTOBUF_FIELD_OFFSET(::PushDataV3ApiWrapper, _impl_.body_),
        0,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        1,
        2,
        3,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::PushDataV3ApiWrapper)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::PushDataV3ApiWrapper_globals_,
};
const char descriptor_table_protodef_PushDataV3ApiWrapper_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032PushDataV3ApiWrapper.proto\032\026PublicDeal"
    "sV3Api.proto\032\037PublicIncreaseDepthsV3Api."
    "proto\032\034PublicLimitDepthsV3Api.proto\032\030Pri"
    "vateOrdersV3Api.proto\032\033PublicBookTickerV"
    "3Api.proto\032\027PrivateDealsV3Api.proto\032\031Pri"
    "vateAccountV3Api.proto\032\032PublicSpotKlineV"
    "3Api.proto\032\033PublicMiniTickerV3Api.proto\032"
    "\034PublicMiniTickersV3Api.proto\032 PublicBoo"
    "kTickerBatchV3Api.proto\032$PublicIncreaseD"
    "epthsBatchV3Api.proto\032\034PublicAggreDepths"
    "V3Api.proto\032\033PublicAggreDealsV3Api.proto"
    "\032 PublicAggreBookTickerV3Api.proto\"\360\007\n\024P"
    "ushDataV3ApiWrapper\022\017\n\007channel\030\001 \001(\t\022)\n\013"
    "publicDeals\030\255\002 \001(\0132\021.PublicDealsV3ApiH\000\022"
    ";\n\024publicIncreaseDepths\030\256\002 \001(\0132\032.PublicI"
    "ncreaseDepthsV3ApiH\000\0225\n\021publicLimitDepth"
    "s\030\257\002 \001(\0132\027.PublicLimitDepthsV3ApiH\000\022-\n\rp"
    "rivateOrders\030\260\002 \001(\0132\023.PrivateOrdersV3Api"
    "H\000\0223\n\020publicBookTicker\030\261\002 \001(\0132\026.PublicBo"
    "okTickerV3ApiH\000\022+\n\014privateDeals\030\262\002 \001(\0132\022"
    ".PrivateDealsV3ApiH\000\022/\n\016privateAccount\030\263"
    "\002 \001(\0132\024.PrivateAccountV3ApiH\000\0221\n\017publicS"
    "potKline\030\264\002 \001(\0132\025.PublicSpotKlineV3ApiH\000"
    "\0223\n\020publicMiniTicker\030\265\002 \001(\0132\026.PublicMini"
    "TickerV3ApiH\000\0225\n\021publicMiniTickers\030\266\002 \001("
    "\0132\027.PublicMiniTickersV3ApiH\000\022=\n\025publicBo"
    "okTickerBatch\030\267\002 \001(\0132\033.PublicBookTickerB"
    "atchV3ApiH\000\022E\n\031publicIncreaseDepthsBatch"
    "\030\270\002 \001(\0132\037.PublicIncreaseDepthsBatchV3Api"
    "H\000\0225\n\021publicAggreDepths\030\271\002 \001(\0132\027.PublicA"
    "ggreDepthsV3ApiH\000\0223\n\020publicAggreDeals\030\272\002"
    " \001(\0132\026.PublicAggreDealsV3ApiH\000\022=\n\025public"
    "AggreBookTicker\030\273\002 \001(\0132\033.PublicAggreBook"
    "TickerV3ApiH\000\022\023\n\006symbol\030\003 \001(\tH\001\210\001\001\022\025\n\010sy"
    "mbolId\030\004 \001(\tH\002\210\001\001\022\027\n\ncreateTime\030\005 \001(\003H\003\210"
    "\001\001\022\025\n\010sendTime\030\006 \001(\003H\004\210\001\001B\006\n\004bodyB\t\n\007_sy"
    "mbolB\013\n\t_symbolIdB\r\n\013_createTimeB\013\n\t_sen"
    "dTimeB=\n\034com.mxc.push.common.protobufB\031P"
    "ushDataV3ApiWrapperProtoH\001P\001b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_PushDataV3ApiWrapper_2eproto_deps[15] = {
        &::descriptor_table_PrivateAccountV3Api_2eproto,
        &::descriptor_table_PrivateDealsV3Api_2eproto,
        &::descriptor_table_PrivateOrdersV3Api_2eproto,
        &::descriptor_table_PublicAggreBookTickerV3Api_2eproto,
        &::descriptor_table_PublicAggreDealsV3Api_2eproto,
        &::descriptor_table_PublicAggreDepthsV3Api_2eproto,
        &::descriptor_table_PublicBookTickerBatchV3Api_2eproto,
        &::descriptor_table_PublicBookTickerV3Api_2eproto,
        &::descriptor_table_PublicDealsV3Api_2eproto,
        &::descriptor_table_PublicIncreaseDepthsBatchV3Api_2eproto,
        &::descriptor_table_PublicIncreaseDepthsV3Api_2eproto,
        &::descriptor_table_PublicLimitDepthsV3Api_2eproto,
        &::descriptor_table_PublicMiniTickerV3Api_2eproto,
        &::descriptor_table_PublicMiniTickersV3Api_2eproto,
        &::descriptor_table_PublicSpotKlineV3Api_2eproto,
};
static ::absl::once_flag descriptor_table_PushDataV3ApiWrapper_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_PushDataV3ApiWrapper_2eproto = {
    false,
    false,
    1556,
    descriptor_table_protodef_PushDataV3ApiWrapper_2eproto,
    "PushDataV3ApiWrapper.proto",
    &descriptor_table_PushDataV3ApiWrapper_2eproto_once,
    descriptor_table_PushDataV3ApiWrapper_2eproto_deps,
    15,
    1,
    schemas,
    file_message_globals,
    TableStruct_PushDataV3ApiWrapper_2eproto::offsets,
    file_level_enum_descriptors_PushDataV3ApiWrapper_2eproto,
    file_level_service_descriptors_PushDataV3ApiWrapper_2eproto,
};
// ===================================================================

void PushDataV3ApiWrapper::set_allocated_publicdeals(::PublicDealsV3Api* PROTOBUF_NULLABLE publicdeals) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (publicdeals) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(publicdeals)->GetArena();
    if (message_arena != submessage_arena) {
      publicdeals = ::google::protobuf::internal::GetOwnedMessage(message_arena, publicdeals, submessage_arena);
    }
    set_has_publicdeals();
    _impl_.body_.publicdeals_ = publicdeals;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicDeals)
}
void PushDataV3ApiWrapper::clear_publicdeals() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPublicDeals) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.publicdeals_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicdeals_);
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicincreasedepths(::PublicIncreaseDepthsV3Api* PROTOBUF_NULLABLE publicincreasedepths) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (publicincreasedepths) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(publicincreasedepths)->GetArena();
    if (message_arena != submessage_arena) {
      publicincreasedepths = ::google::protobuf::internal::GetOwnedMessage(message_arena, publicincreasedepths, submessage_arena);
    }
    set_has_publicincreasedepths();
    _impl_.body_.publicincreasedepths_ = publicincreasedepths;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicIncreaseDepths)
}
void PushDataV3ApiWrapper::clear_publicincreasedepths() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPublicIncreaseDepths) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.publicincreasedepths_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicincreasedepths_);
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publiclimitdepths(::PublicLimitDepthsV3Api* PROTOBUF_NULLABLE publiclimitdepths) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (publiclimitdepths) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(publiclimitdepths)->GetArena();
    if (message_arena != submessage_arena) {
      publiclimitdepths = ::google::protobuf::internal::GetOwnedMessage(message_arena, publiclimitdepths, submessage_arena);
    }
    set_has_publiclimitdepths();
    _impl_.body_.publiclimitdepths_ = publiclimitdepths;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicLimitDepths)
}
void PushDataV3ApiWrapper::clear_publiclimitdepths() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPublicLimitDepths) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.publiclimitdepths_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publiclimitdepths_);
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_privateorders(::PrivateOrdersV3Api* PROTOBUF_NULLABLE privateorders) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (privateorders) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(privateorders)->GetArena();
    if (message_arena != submessage_arena) {
      privateorders = ::google::protobuf::internal::GetOwnedMessage(message_arena, privateorders, submessage_arena);
    }
    set_has_privateorders();
    _impl_.body_.privateorders_ = privateorders;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.privateOrders)
}
void PushDataV3ApiWrapper::clear_privateorders() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPrivateOrders) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.privateorders_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.privateorders_);
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicbookticker(::PublicBookTickerV3Api* PROTOBUF_NULLABLE publicbookticker) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (publicbookticker) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(publicbookticker)->GetArena();
    if (message_arena != submessage_arena) {
      publicbookticker = ::google::protobuf::internal::GetOwnedMessage(message_arena, publicbookticker, submessage_arena);
    }
    set_has_publicbookticker();
    _impl_.body_.publicbookticker_ = publicbookticker;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicBookTicker)
}
void PushDataV3ApiWrapper::clear_publicbookticker() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPublicBookTicker) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.publicbookticker_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicbookticker_);
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_privatedeals(::PrivateDealsV3Api* PROTOBUF_NULLABLE privatedeals) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (privatedeals) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(privatedeals)->GetArena();
    if (message_arena != submessage_arena) {
      privatedeals = ::google::protobuf::internal::GetOwnedMessage(message_arena, privatedeals, submessage_arena);
    }
    set_has_privatedeals();
    _impl_.body_.privatedeals_ = privatedeals;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.privateDeals)
}
void PushDataV3ApiWrapper::clear_privatedeals() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPrivateDeals) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.privatedeals_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.privatedeals_);
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_privateaccount(::PrivateAccountV3Api* PROTOBUF_NULLABLE privateaccount) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (privateaccount) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(privateaccount)->GetArena();
    if (message_arena != submessage_arena) {
      privateaccount = ::google::protobuf::internal::GetOwnedMessage(message_arena, privateaccount, submessage_arena);
    }
    set_has_privateaccount();
    _impl_.body_.privateaccount_ = privateaccount;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.privateAccount)
}
void PushDataV3ApiWrapper::clear_privateaccount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPrivateAccount) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.privateaccount_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.privateaccount_);
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicspotkline(::PublicSpotKlineV3Api* PROTOBUF_NULLABLE publicspotkline) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (publicspotkline) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(publicspotkline)->GetArena();
    if (message_arena != submessage_arena) {
      publicspotkline = ::google::protobuf::internal::GetOwnedMessage(message_arena, publicspotkline, submessage_arena);
    }
    set_has_publicspotkline();
    _impl_.body_.publicspotkline_ = publicspotkline;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicSpotKline)
}
void PushDataV3ApiWrapper::clear_publicspotkline() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPublicSpotKline) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.publicspotkline_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicspotkline_);
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicminiticker(::PublicMiniTickerV3Api* PROTOBUF_NULLABLE publicminiticker) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (publicminiticker) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(publicminiticker)->GetArena();
    if (message_arena != submessage_arena) {
      publicminiticker = ::google::protobuf::internal::GetOwnedMessage(message_arena, publicminiticker, submessage_arena);
    }
    set_has_publicminiticker();
    _impl_.body_.publicminiticker_ = publicminiticker;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicMiniTicker)
}
void PushDataV3ApiWrapper::clear_publicminiticker() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPublicMiniTicker) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.publicminiticker_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicminiticker_);
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicminitickers(::PublicMiniTickersV3Api* PROTOBUF_NULLABLE publicminitickers) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (publicminitickers) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(publicminitickers)->GetArena();
    if (message_arena != submessage_arena) {
      publicminitickers = ::google::protobuf::internal::GetOwnedMessage(message_arena, publicminitickers, submessage_arena);
    }
    set_has_publicminitickers();
    _impl_.body_.publicminitickers_ = publicminitickers;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicMiniTickers)
}
void PushDataV3ApiWrapper::clear_publicminitickers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPublicMiniTickers) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.publicminitickers_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicminitickers_);
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicbooktickerbatch(::PublicBookTickerBatchV3Api* PROTOBUF_NULLABLE publicbooktickerbatch) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (publicbooktickerbatch) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(publicbooktickerbatch)->GetArena();
    if (message_arena != submessage_arena) {
      publicbooktickerbatch = ::google::protobuf::internal::GetOwnedMessage(message_arena, publicbooktickerbatch, submessage_arena);
    }
    set_has_publicbooktickerbatch();
    _impl_.body_.publicbooktickerbatch_ = publicbooktickerbatch;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicBookTickerBatch)
}
void PushDataV3ApiWrapper::clear_publicbooktickerbatch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPublicBookTickerBatch) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.publicbooktickerbatch_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicbooktickerbatch_);
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicincreasedepthsbatch(::PublicIncreaseDepthsBatchV3Api* PROTOBUF_NULLABLE publicincreasedepthsbatch) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (publicincreasedepthsbatch) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(publicincreasedepthsbatch)->GetArena();
    if (message_arena != submessage_arena) {
      publicincreasedepthsbatch = ::google::protobuf::internal::GetOwnedMessage(message_arena, publicincreasedepthsbatch, submessage_arena);
    }
    set_has_publicincreasedepthsbatch();
    _impl_.body_.publicincreasedepthsbatch_ = publicincreasedepthsbatch;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicIncreaseDepthsBatch)
}
void PushDataV3ApiWrapper::clear_publicincreasedepthsbatch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPublicIncreaseDepthsBatch) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.publicincreasedepthsbatch_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicincreasedepthsbatch_);
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicaggredepths(::PublicAggreDepthsV3Api* PROTOBUF_NULLABLE publicaggredepths) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (publicaggredepths) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(publicaggredepths)->GetArena();
    if (message_arena != submessage_arena) {
      publicaggredepths = ::google::protobuf::internal::GetOwnedMessage(message_arena, publicaggredepths, submessage_arena);
    }
    set_has_publicaggredepths();
    _impl_.body_.publicaggredepths_ = publicaggredepths;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicAggreDepths)
}
void PushDataV3ApiWrapper::clear_publicaggredepths() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPublicAggreDepths) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.publicaggredepths_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicaggredepths_);
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicaggredeals(::PublicAggreDealsV3Api* PROTOBUF_NULLABLE publicaggredeals) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (publicaggredeals) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(publicaggredeals)->GetArena();
    if (message_arena != submessage_arena) {
      publicaggredeals = ::google::protobuf::internal::GetOwnedMessage(message_arena, publicaggredeals, submessage_arena);
    }
    set_has_publicaggredeals();
    _impl_.body_.publicaggredeals_ = publicaggredeals;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicAggreDeals)
}
void PushDataV3ApiWrapper::clear_publicaggredeals() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPublicAggreDeals) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.publicaggredeals_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicaggredeals_);
    }
    clear_has_body();
  }
}
void PushDataV3ApiWrapper::set_allocated_publicaggrebookticker(::PublicAggreBookTickerV3Api* PROTOBUF_NULLABLE publicaggrebookticker) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (publicaggrebookticker) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(publicaggrebookticker)->GetArena();
    if (message_arena != submessage_arena) {
      publicaggrebookticker = ::google::protobuf::internal::GetOwnedMessage(message_arena, publicaggrebookticker, submessage_arena);
    }
    set_has_publicaggrebookticker();
    _impl_.body_.publicaggrebookticker_ = publicaggrebookticker;
  }
  // @@protoc_insertion_point(field_set_allocated:PushDataV3ApiWrapper.publicAggreBookTicker)
}
void PushDataV3ApiWrapper::clear_publicaggrebookticker() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPublicAggreBookTicker) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.publicaggrebookticker_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicaggrebookticker_);
    }
    clear_has_body();
  }
}
PushDataV3ApiWrapper::PushDataV3ApiWrapper(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PushDataV3ApiWrapper_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PushDataV3ApiWrapper)
}
PROTOBUF_NDEBUG_INLINE PushDataV3ApiWrapper::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::PushDataV3ApiWrapper& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        channel_(arena, from.channel_),
        symbol_(arena, from.symbol_),
        symbolid_(arena, from.symbolid_),
        body_{},
        _oneof_case_{from._oneof_case_[0]} {}

PushDataV3ApiWrapper::PushDataV3ApiWrapper(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PushDataV3ApiWrapper& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PushDataV3ApiWrapper_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PushDataV3ApiWrapper* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, createtime_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, createtime_),
           offsetof(Impl_, sendtime_) -
               offsetof(Impl_, createtime_) +
               sizeof(Impl_::sendtime_));
  switch (body_case()) {
    case BODY_NOT_SET:
      break;
      case kPublicDeals:
        _impl_.body_.publicdeals_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicdeals_);
        break;
      case kPublicIncreaseDepths:
        _impl_.body_.publicincreasedepths_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicincreasedepths_);
        break;
      case kPublicLimitDepths:
        _impl_.body_.publiclimitdepths_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publiclimitdepths_);
        break;
      case kPrivateOrders:
        _impl_.body_.privateorders_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.privateorders_);
        break;
      case kPublicBookTicker:
        _impl_.body_.publicbookticker_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicbookticker_);
        break;
      case kPrivateDeals:
        _impl_.body_.privatedeals_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.privatedeals_);
        break;
      case kPrivateAccount:
        _impl_.body_.privateaccount_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.privateaccount_);
        break;
      case kPublicSpotKline:
        _impl_.body_.publicspotkline_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicspotkline_);
        break;
      case kPublicMiniTicker:
        _impl_.body_.publicminiticker_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicminiticker_);
        break;
      case kPublicMiniTickers:
        _impl_.body_.publicminitickers_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicminitickers_);
        break;
      case kPublicBookTickerBatch:
        _impl_.body_.publicbooktickerbatch_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicbooktickerbatch_);
        break;
      case kPublicIncreaseDepthsBatch:
        _impl_.body_.publicincreasedepthsbatch_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicincreasedepthsbatch_);
        break;
      case kPublicAggreDepths:
        _impl_.body_.publicaggredepths_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicaggredepths_);
        break;
      case kPublicAggreDeals:
        _impl_.body_.publicaggredeals_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicaggredeals_);
        break;
      case kPublicAggreBookTicker:
        _impl_.body_.publicaggrebookticker_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicaggrebookticker_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:PushDataV3ApiWrapper)
}
PROTOBUF_NDEBUG_INLINE PushDataV3ApiWrapper::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        channel_(arena),
        symbol_(arena),
        symbolid_(arena),
        body_{},
        _oneof_case_{} {}

inline void PushDataV3ApiWrapper::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, createtime_),
           0,
           offsetof(Impl_, sendtime_) -
               offsetof(Impl_, createtime_) +
               sizeof(Impl_::sendtime_));
}
PushDataV3ApiWrapper::~PushDataV3ApiWrapper() {
  // @@protoc_insertion_point(destructor:PushDataV3ApiWrapper)
  SharedDtor(*this);
}
inline void PushDataV3ApiWrapper::SharedDtor(MessageLite& self) {
  PushDataV3ApiWrapper& this_ = static_cast<PushDataV3ApiWrapper&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.channel_.Destroy();
  this_._impl_.symbol_.Destroy();
  this_._impl_.symbolid_.Destroy();
  if (this_.has_body()) {
    this_.clear_body();
  }
  this_._impl_.~Impl_();
}

void PushDataV3ApiWrapper::clear_body() {
// @@protoc_insertion_point(one_of_clear_start:PushDataV3ApiWrapper)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (body_case()) {
    case kPublicDeals: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.publicdeals_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicdeals_);
      }
      break;
    }
    case kPublicIncreaseDepths: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.publicincreasedepths_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicincreasedepths_);
      }
      break;
    }
    case kPublicLimitDepths: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.publiclimitdepths_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publiclimitdepths_);
      }
      break;
    }
    case kPrivateOrders: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.privateorders_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.privateorders_);
      }
      break;
    }
    case kPublicBookTicker: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.publicbookticker_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicbookticker_);
      }
      break;
    }
    case kPrivateDeals: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.privatedeals_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.privatedeals_);
      }
      break;
    }
    case kPrivateAccount: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.privateaccount_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.privateaccount_);
      }
      break;
    }
    case kPublicSpotKline: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.publicspotkline_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicspotkline_);
      }
      break;
    }
    case kPublicMiniTicker: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.publicminiticker_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicminiticker_);
      }
      break;
    }
    case kPublicMiniTickers: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.publicminitickers_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicminitickers_);
      }
      break;
    }
    case kPublicBookTickerBatch: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.publicbooktickerbatch_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicbooktickerbatch_);
      }
      break;
    }
    case kPublicIncreaseDepthsBatch: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.publicincreasedepthsbatch_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicincreasedepthsbatch_);
      }
      break;
    }
    case kPublicAggreDepths: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.publicaggredepths_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicaggredepths_);
      }
      break;
    }
    case kPublicAggreDeals: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.publicaggredeals_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicaggredeals_);
      }
      break;
    }
    case kPublicAggreBookTicker: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.publicaggrebookticker_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.publicaggrebookticker_);
      }
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = BODY_NOT_SET;
}


#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PushDataV3ApiWrapper_class_data_ =
        PushDataV3ApiWrapper::InternalGenerateClassData_(PushDataV3ApiWrapper_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PushDataV3ApiWrapper::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PushDataV3ApiWrapper_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PushDataV3ApiWrapper_class_data_.tc_table);
  return PushDataV3ApiWrapper_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PushDataV3ApiWrapper::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PushDataV3ApiWrapper_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&PushDataV3ApiWrapper_globals_));
  return PushDataV3ApiWrapper_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const PushDataV3ApiWrapper::ParseTableT_
    PushDataV3ApiWrapper::_table_ =
        PushDataV3ApiWrapper::InternalGenerateParseTable_(PushDataV3ApiWrapper_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void PushDataV3ApiWrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:PushDataV3ApiWrapper)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.channel_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.symbol_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.symbolid_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000018U)) {
    ::memset(&_impl_.createtime_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.sendtime_) -
        reinterpret_cast<char*>(&_impl_.createtime_)) + sizeof(_impl_.sendtime_));
  }
  clear_body();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PushDataV3ApiWrapper::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PushDataV3ApiWrapper& this_ = static_cast<const PushDataV3ApiWrapper&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PushDataV3ApiWrapper::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PushDataV3ApiWrapper& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:PushDataV3ApiWrapper)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string channel = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_channel().empty()) {
      const ::std::string& _s = this_._internal_channel();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PushDataV3ApiWrapper.channel");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // optional string symbol = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_symbol();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PushDataV3ApiWrapper.symbol");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional string symbolId = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::std::string& _s = this_._internal_symbolid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PushDataV3ApiWrapper.symbolId");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // optional int64 createTime = 5;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<5>(
            stream, this_._internal_createtime(), target);
  }

  // optional int64 sendTime = 6;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<6>(
            stream, this_._internal_sendtime(), target);
  }

  switch (this_.body_case()) {
    case kPublicDeals: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          301, *this_._impl_.body_.publicdeals_, this_._impl_.body_.publicdeals_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPublicIncreaseDepths: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          302, *this_._impl_.body_.publicincreasedepths_, this_._impl_.body_.publicincreasedepths_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPublicLimitDepths: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          303, *this_._impl_.body_.publiclimitdepths_, this_._impl_.body_.publiclimitdepths_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPrivateOrders: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          304, *this_._impl_.body_.privateorders_, this_._impl_.body_.privateorders_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPublicBookTicker: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          305, *this_._impl_.body_.publicbookticker_, this_._impl_.body_.publicbookticker_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPrivateDeals: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          306, *this_._impl_.body_.privatedeals_, this_._impl_.body_.privatedeals_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPrivateAccount: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          307, *this_._impl_.body_.privateaccount_, this_._impl_.body_.privateaccount_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPublicSpotKline: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          308, *this_._impl_.body_.publicspotkline_, this_._impl_.body_.publicspotkline_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPublicMiniTicker: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          309, *this_._impl_.body_.publicminiticker_, this_._impl_.body_.publicminiticker_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPublicMiniTickers: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          310, *this_._impl_.body_.publicminitickers_, this_._impl_.body_.publicminitickers_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPublicBookTickerBatch: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          311, *this_._impl_.body_.publicbooktickerbatch_, this_._impl_.body_.publicbooktickerbatch_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPublicIncreaseDepthsBatch: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          312, *this_._impl_.body_.publicincreasedepthsbatch_, this_._impl_.body_.publicincreasedepthsbatch_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPublicAggreDepths: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          313, *this_._impl_.body_.publicaggredepths_, this_._impl_.body_.publicaggredepths_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPublicAggreDeals: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          314, *this_._impl_.body_.publicaggredeals_, this_._impl_.body_.publicaggredeals_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPublicAggreBookTicker: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          315, *this_._impl_.body_.publicaggrebookticker_, this_._impl_.body_.publicaggrebookticker_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PushDataV3ApiWrapper)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PushDataV3ApiWrapper::ByteSizeLong(const MessageLite& base) {
  const PushDataV3ApiWrapper& this_ = static_cast<const PushDataV3ApiWrapper&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PushDataV3ApiWrapper::ByteSizeLong() const {
  const PushDataV3ApiWrapper& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:PushDataV3ApiWrapper)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // string channel = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_channel().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_channel());
      }
    }
    // optional string symbol = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_symbol());
    }
    // optional string symbolId = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_symbolid());
    }
    // optional int64 createTime = 5;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_createtime());
    }
    // optional int64 sendTime = 6;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_sendtime());
    }
  }
  switch (this_.body_case()) {
    // .PublicDealsV3Api publicDeals = 301;
    case kPublicDeals: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.publicdeals_);
      break;
    }
    // .PublicIncreaseDepthsV3Api publicIncreaseDepths = 302;
    case kPublicIncreaseDepths: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.publicincreasedepths_);
      break;
    }
    // .PublicLimitDepthsV3Api publicLimitDepths = 303;
    case kPublicLimitDepths: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.publiclimitdepths_);
      break;
    }
    // .PrivateOrdersV3Api privateOrders = 304;
    case kPrivateOrders: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.privateorders_);
      break;
    }
    // .PublicBookTickerV3Api publicBookTicker = 305;
    case kPublicBookTicker: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.publicbookticker_);
      break;
    }
    // .PrivateDealsV3Api privateDeals = 306;
    case kPrivateDeals: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.privatedeals_);
      break;
    }
    // .PrivateAccountV3Api privateAccount = 307;
    case kPrivateAccount: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.privateaccount_);
      break;
    }
    // .PublicSpotKlineV3Api publicSpotKline = 308;
    case kPublicSpotKline: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.publicspotkline_);
      break;
    }
    // .PublicMiniTickerV3Api publicMiniTicker = 309;
    case kPublicMiniTicker: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.publicminiticker_);
      break;
    }
    // .PublicMiniTickersV3Api publicMiniTickers = 310;
    case kPublicMiniTickers: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.publicminitickers_);
      break;
    }
    // .PublicBookTickerBatchV3Api publicBookTickerBatch = 311;
    case kPublicBookTickerBatch: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.publicbooktickerbatch_);
      break;
    }
    // .PublicIncreaseDepthsBatchV3Api publicIncreaseDepthsBatch = 312;
    case kPublicIncreaseDepthsBatch: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.publicincreasedepthsbatch_);
      break;
    }
    // .PublicAggreDepthsV3Api publicAggreDepths = 313;
    case kPublicAggreDepths: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.publicaggredepths_);
      break;
    }
    // .PublicAggreDealsV3Api publicAggreDeals = 314;
    case kPublicAggreDeals: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.publicaggredeals_);
      break;
    }
    // .PublicAggreBookTickerV3Api publicAggreBookTicker = 315;
    case kPublicAggreBookTicker: {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.publicaggrebookticker_);
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PushDataV3ApiWrapper::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<PushDataV3ApiWrapper*>(&to_msg);
  auto& from = static_cast<const PushDataV3ApiWrapper&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:PushDataV3ApiWrapper)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_channel().empty()) {
        _this->_internal_set_channel(from._internal_channel());
      } else {
        if (_this->_impl_.channel_.IsDefault()) {
          _this->_internal_set_channel("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_symbol(from._internal_symbol());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_symbolid(from._internal_symbolid());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.createtime_ = from._impl_.createtime_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.sendtime_ = from._impl_.sendtime_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case =
          from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_body();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kPublicDeals: {
        if (oneof_needs_init) {
          _this->_impl_.body_.publicdeals_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicdeals_);
        } else {
          _this->_impl_.body_.publicdeals_->MergeFrom(*from._impl_.body_.publicdeals_);
        }
        break;
      }
      case kPublicIncreaseDepths: {
        if (oneof_needs_init) {
          _this->_impl_.body_.publicincreasedepths_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicincreasedepths_);
        } else {
          _this->_impl_.body_.publicincreasedepths_->MergeFrom(*from._impl_.body_.publicincreasedepths_);
        }
        break;
      }
      case kPublicLimitDepths: {
        if (oneof_needs_init) {
          _this->_impl_.body_.publiclimitdepths_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publiclimitdepths_);
        } else {
          _this->_impl_.body_.publiclimitdepths_->MergeFrom(*from._impl_.body_.publiclimitdepths_);
        }
        break;
      }
      case kPrivateOrders: {
        if (oneof_needs_init) {
          _this->_impl_.body_.privateorders_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.privateorders_);
        } else {
          _this->_impl_.body_.privateorders_->MergeFrom(*from._impl_.body_.privateorders_);
        }
        break;
      }
      case kPublicBookTicker: {
        if (oneof_needs_init) {
          _this->_impl_.body_.publicbookticker_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicbookticker_);
        } else {
          _this->_impl_.body_.publicbookticker_->MergeFrom(*from._impl_.body_.publicbookticker_);
        }
        break;
      }
      case kPrivateDeals: {
        if (oneof_needs_init) {
          _this->_impl_.body_.privatedeals_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.privatedeals_);
        } else {
          _this->_impl_.body_.privatedeals_->MergeFrom(*from._impl_.body_.privatedeals_);
        }
        break;
      }
      case kPrivateAccount: {
        if (oneof_needs_init) {
          _this->_impl_.body_.privateaccount_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.privateaccount_);
        } else {
          _this->_impl_.body_.privateaccount_->MergeFrom(*from._impl_.body_.privateaccount_);
        }
        break;
      }
      case kPublicSpotKline: {
        if (oneof_needs_init) {
          _this->_impl_.body_.publicspotkline_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicspotkline_);
        } else {
          _this->_impl_.body_.publicspotkline_->MergeFrom(*from._impl_.body_.publicspotkline_);
        }
        break;
      }
      case kPublicMiniTicker: {
        if (oneof_needs_init) {
          _this->_impl_.body_.publicminiticker_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicminiticker_);
        } else {
          _this->_impl_.body_.publicminiticker_->MergeFrom(*from._impl_.body_.publicminiticker_);
        }
        break;
      }
      case kPublicMiniTickers: {
        if (oneof_needs_init) {
          _this->_impl_.body_.publicminitickers_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicminitickers_);
        } else {
          _this->_impl_.body_.publicminitickers_->MergeFrom(*from._impl_.body_.publicminitickers_);
        }
        break;
      }
      case kPublicBookTickerBatch: {
        if (oneof_needs_init) {
          _this->_impl_.body_.publicbooktickerbatch_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicbooktickerbatch_);
        } else {
          _this->_impl_.body_.publicbooktickerbatch_->MergeFrom(*from._impl_.body_.publicbooktickerbatch_);
        }
        break;
      }
      case kPublicIncreaseDepthsBatch: {
        if (oneof_needs_init) {
          _this->_impl_.body_.publicincreasedepthsbatch_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicincreasedepthsbatch_);
        } else {
          _this->_impl_.body_.publicincreasedepthsbatch_->MergeFrom(*from._impl_.body_.publicincreasedepthsbatch_);
        }
        break;
      }
      case kPublicAggreDepths: {
        if (oneof_needs_init) {
          _this->_impl_.body_.publicaggredepths_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicaggredepths_);
        } else {
          _this->_impl_.body_.publicaggredepths_->MergeFrom(*from._impl_.body_.publicaggredepths_);
        }
        break;
      }
      case kPublicAggreDeals: {
        if (oneof_needs_init) {
          _this->_impl_.body_.publicaggredeals_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicaggredeals_);
        } else {
          _this->_impl_.body_.publicaggredeals_->MergeFrom(*from._impl_.body_.publicaggredeals_);
        }
        break;
      }
      case kPublicAggreBookTicker: {
        if (oneof_needs_init) {
          _this->_impl_.body_.publicaggrebookticker_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.publicaggrebookticker_);
        } else {
          _this->_impl_.body_.publicaggrebookticker_->MergeFrom(*from._impl_.body_.publicaggrebookticker_);
        }
        break;
      }
      case BODY_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PushDataV3ApiWrapper::CopyFrom(const PushDataV3ApiWrapper& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:PushDataV3ApiWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PushDataV3ApiWrapper::InternalSwap(PushDataV3ApiWrapper* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.channel_, &other->_impl_.channel_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.symbol_, &other->_impl_.symbol_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.symbolid_, &other->_impl_.symbolid_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.sendtime_)
      + sizeof(PushDataV3ApiWrapper::_impl_.sendtime_)
      - PROTOBUF_FIELD_OFFSET(PushDataV3ApiWrapper, _impl_.createtime_)>(
          reinterpret_cast<char*>(&_impl_.createtime_),
          reinterpret_cast<char*>(&other->_impl_.createtime_));
  swap(_impl_.body_, other->_impl_.body_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata PushDataV3ApiWrapper::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_PushDataV3ApiWrapper_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
