# /***************************
# *
# *
# *
# *
# ***************************

MACRO(NOVA_MESSAGE MSG)
    MESSAGE(STATUS ${MSG})
ENDMACRO()

MACRO(NOVA_WARNING MSG)
    MESSAGE(WARNING ${MSG})
ENDMACRO()

MACRO(NOVA_ERROR MSG)
    MESSAGE(FATAL_ERROR ${MSG})
ENDMACRO()

MACRO(NOVA_GET_HEADERS DIR HEADERS)
    FILE(GLOB _tmp_h "${DIR}/*.h")
    SET(${HEADERS} ${_tmp_h})
ENDMACRO()

MACRO(NOVA_GET_SOURCES DIR SOURCES)
    FILE(GLOB _tmp_cxx "${DIR}/*.c*")
    SET(${SOURCES} ${_tmp_cxx})
ENDMACRO()

MACRO(NOVA_GET_ALL_SOURCES DIR SOURCES)
    FILE(GLOB _tmp_h "${DIR}/*.h")
    FILE(GLOB _tmp_cxx "${DIR}/*.c*")
    SET(${SOURCES} "${_tmp_h};${_tmp_cxx}")
ENDMACRO()

MACRO(NOVA_GET_SUBDIRS DIR SUBDIRS)
    FILE(GLOB _tmp "${DIR}/*")
    SET(_subdirs "")

    FOREACH(_file ${_tmp})
        IF(IS_DIRECTORY ${_file})
            SET(_subdirs "${_subdirs};${_file}")
        ENDIF()
    ENDFOREACH()

    SET(${SUBDIRS} ${_subdirs})
ENDMACRO()

MACRO(NOVA_PARSE_ARGUMENTS prefix arg_names option_names)
    SET(DEFAULT_ARGS)

    FOREACH(arg_name ${arg_names})
        SET(${prefix}_${arg_name})
    ENDFOREACH(arg_name)

    FOREACH(option ${option_names})
        SET(${prefix}_${option} FALSE)
    ENDFOREACH(option)

    SET(currenct_arg_name DEFAULT_ARGS)
    SET(currenct_arg_list)

    FOREACH(arg ${ARGN})
        SET(larg_names ${arg_names})
        LIST(FIND larg_names "${arg}" is_arg_name)

        IF(is_arg_name GREATER -1)
            SET(${prefix}_${currenct_arg_name} ${currenct_arg_list})
            SET(currenct_arg_name ${arg})
            SET(currenct_arg_list)
        ELSE()
            SET(loption_names ${option_names})
            LIST(FIND loption_names "${arg}" is_option)

            IF(is_option GREATER -1)
                SET(${prefix}_${arg} TRUE)
            ELSE()
                SET(currenct_arg_list ${currenct_arg_list} ${arg})
            ENDIF(is_option GREATER -1)
        ENDIF(is_arg_name GREATER -1)
    ENDFOREACH(arg)

    SET(${prefix}_${currenct_arg_name} ${currenct_arg_list})
ENDMACRO()

MACRO(NOVA_GET_LIBS)
    NOVA_PARSE_ARGUMENTS(ARG "PATHS;NAMES" , "" , ${ARGN})

    IF(NOT ARG_DEFAULT_ARGS)
        MESSAGE(FATAL_ERROR "Dst cant empty")
    ENDIF()

    IF(NOT ARG_PATHS OR NOT ARG_NAMES)
        MESSAGE(FATAL_ERROR "Invalid arguments")
    ENDIF()

    SET(ret_libs "")

    FOREACH(tmp_lib ${ARG_NAMES})
        FIND_LIBRARY(ret_lib ${tmp_lib} PATHS ${ARG_PATHS} NO_DEFAULT_PATH)
        SET(ret_libs "${ret_libs};${ret_lib}")

        IF(ret_lib)
        ELSE()
            NOVA_ERROR("${tmp_lib} not found!")
        ENDIF()

        UNSET(ret_lib CACHE)
    ENDFOREACH()

    LIST(GET ARG_DEFAULT_ARGS 0 _target)
    SET(${_target} ${ret_libs})
ENDMACRO()

MACRO(NOVA_SET_COMMON_DIRECTORIES src_dir)
    SET(_tmp_inc_dir ${src_dir}/include)
    SET(_tmp_lib_dir ${src_dir}/lib)
    SET(NOVA_COMMON_INC_DIRS ${NOVA_COMMON_INC_DIRS} ${src_dir}/include)
    NOVA_GET_SUBDIRS(${_tmp_inc_dir} _subdirs)

    IF(_subdirs)
        SET(NOVA_COMMON_INC_DIRS ${NOVA_COMMON_INC_DIRS} ${_subdirs})
    ENDIF()

    IF(CMAKE_SYSTEM_NAME MATCHES "Windows")
        SET(NOVA_COMMON_LIB_DIRS ${NOVA_COMMON_LIB_DIRS} ${_tmp_lib_dir} ${_tmp_lib_dir}/win)
    ELSEIF(CMAKE_SYSTEM_NAME MATCHES "Linux")
        SET(NOVA_COMMON_LIB_DIRS ${NOVA_COMMON_LIB_DIRS} ${_tmp_lib_dir} ${_tmp_lib_dir}/linux)
    ENDIF()

    LINK_DIRECTORIES(${NOVA_COMMON_LIB_DIRS})
ENDMACRO()

include(CheckCSourceCompiles)
include(CheckCXXSourceCompiles)

SET(_CMAKE_DEEP 0)
SET(_CMAKE_DEEP_LIST)

MACRO(NOVA_CMAKE_ENTER)
    SET(_tmp ${CMAKE_CURRENT_LIST_DIR}/CMakeList.txt)

    IF(_tmp STREQUAL CMAKE_CURRENT_LIST_FILE)
        LIST(FIND _CMAKE_DEEP_LIST ${CMAKE_CURRENT_LIST_DIR} _index)

        IF(_index GREATER -1)
            NOVA_ERROR("The NOVA_CMAKE_ENTER() is called repeatedly.(${CMAKE_CURRENT_LIST_FILE})")
        ENDIF()

        IF(${CMAKE_CURRENT_LIST_FILE}_DEEP)
            NOVA_ERROR("The CMake File is called repeatedly.(${CMAKE_CURRENT_LIST_FILE})")
        ENDIF()

        NOVA_MESSAGE("CMAKE ENTER : ${CMAKE_CURRENT_LIST_FILE}")
        MATH(EXPR _CMAKE_DEEP "${_CMAKE_DEEP} + 1")
        SET(${CMAKE_CURRENT_LIST_FILE}_DEEP ON)
        LIST(INSERT _CMAKE_DEEP_LIST 0 ${CMAKE_CURRENT_LIST_DIR})
    ENDIF()
ENDMACRO()

MACRO(NOVA_CMAKE_LEAVE)
    SET(_tmp ${CMAKE_CURRENT_LIST_DIR}/CMakeList.txt)

    IF(_tmp STREQUAL CMAKE_CURRENT_LIST_FILE)
        LIST(FIND _CMAKE_DEEP_LIST ${CMAKE_CURRENT_LIST_DIR} _index)

        IF(_index EQUAL -1)
            NOVA_ERROR("The NOVA_CMAKE_LEAVE() is called repeatedly.(${CMAKE_CURRENT_LIST_FILE})")
        ELSE()
            NOVA_ERROR("The NOVA_CMAKE_ENTER() must be thre first called by an CMake File.(${CMAKE_CURRENT_LIST_FILE})")
        ENDIF()

        IF(_index GREATER 0)
            LIST(GET _CMAKE_DEEP_LIST 0 _tmp)
            NOVA_ERROR("The NOVA_CMAKE_LEAVE() has not been calledd in the end of CMake File.(${_tmp})")
        ENDIF()

        NOVA_MESSAGE("CMAKE LEAVE : ${CMAKE_CURRENT_LIST_FILE}")
        LIST(REMOVE_AT _CMAKE_DEEP_LIST 0)
        MATH(EXPR _CMAKE_DEEP "${_CMAKE_DEEP} - 1")
    ENDIF()
ENDMACRO()

MACRO(NOVA_ADD_LIB)
    NOVA_PARSE_ARGUMENTS(ARG
        "OUTPUT;HEADER;SOURCE;PACKAGE;PATH;INSTALL_DIR"
        "SHARE"
        ${ARGN}
    )

    IF(NOT ARG_DEFAULT_ARGS)
        MESSAGE(FATAL_ERROR "target cant empty.")
    ENDIF()

    IF(NOT ARG_HEADER AND NOT ARG_SOURCE)
        MESSAGE(FATAL_ERROR "To produce a library we need at least one source file.")
    ENDIF()

    LIST(GET ARG_DEFAULT_ARGS 0 TARGET)

    IF(NOT ARG_OUTPUT)
        SET(ARG_OUTPUT ${NOVA_LIB_DIR})
    ENDIF()

    ADD_LIBRARY(${TARGET} STATIC ${ARG_HEADER} ${ARG_SOURCE})
    TARGET_INCLUDE_DIRECTORIES(${TARGET} PRIVATE ${NOVA_COMMON_INC_DIRS})
    TARGET_LINK_LIBRARIES(${TARGET} ${ARG_PACKAGE})

    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES ARCHIVE_OUTPUT_NAME_DEBUG ${ARG_OUTPUT}D)
    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES ARCHIVE_OUTPUT_NAME_RELEASE ${ARG_OUTPUT})
    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${ARG_PATH})
    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${ARG_PATH})

    IF(ARG_SHARE AND CMAKE_SYSTEM_NAME MATCHES "Linux")
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES COMPILE_FLAGS
            "${CMAKE_SHARED_LIBRARY_C_FLAGS}")
    ENDIF()

    IF(NOT ARG_INSTALL_DIR)
        IF(${ARG_PATH} STREQUAL ${NOVA_LIB_DIR})
            INSTALL(TARGETS ${TRRGET}
                RUNTIME DESTINATION "${NOVA_INSTALL_DIR}/bin"
                LIBRARY DESTINATION "${NOVA_INSTALL_DIR}/lib"
                ARCHIVE DESTINATION "${NOVA_INSTALL_DIR}/lib"
            )
        ELSE()
            FILE(RELATIVE_PATH INSTALL_DIR ${NOVA_LIB_DIR} ${ARG_PATH})
            INSTALL(DIRECTORY ${ARG_PATH} DESTINATION ${NOVA_INSTALL_DIR}/lib)
        ENDIF()
    ELSE()
        IF(${ARG_INSTALL_DIR} STREQUAL "NULL")
        ELSE()
            INSTALL(TARGETS ${TARGET} DESTINATION ${ARG_INSTALL_DIR})
        ENDIF()
    ENDIF()
ENDMACRO()

MACRO(NOVA_ADD_DLL)
    NOVA_PARSE_ARGUMENTS(ARG
        "OUTPUT;HEADER;SOURCE;PACKAGE;PATH;INSTALL_DIR"
        "MODULE"
        ${ARGN}
    )

    IF(CMAKE_SYSTEM_NAME MATCHES "Windows")
        ADD_DEFINITIONS("-D_WIN_DLL_")
    ENDIF()

    IF(NOT ARG_HEADER AND NOT ARG_SOURCE)
        MESSAGE(FATAL_ERROR "To produce a library we need at least one source file.")
    ENDIF()

    LIST(GET ARG_DEFAULT_ARGS 0 TARGET)

    IF(NOT ARG_OUTPUT)
        SET(ARG_OUTPUT ${TARGET})
    ENDIF()

    IF(NOT ARG_PATH)
        SET(ARG_PATH ${NOVA_LIB_DIR})
    ENDIF()

    ADD_LIBRARY(${TARGET} SHARED ${ARG_HEADER} ${ARG_SOURCE})
    TARGET_INCLUDE_DIRECTORIES(${TARGET} PRIVATE ${NOVA_COMMON_INC_DIRS})
    TARGET_LINK_LIBRARIES(${TARGET} ${ARG_PACKAGE})

    IF(CMAKE_SYSTEM_NAME MATCHES "Windows")
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES RUNTIME_OUTPUT_NAME_DEBUG ${ARG_OUTPUT}D)
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES RUNTIME_OUTPUT_NAME_RELEASE ${ARG_OUTPUT})
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG ${ARG_PATH})
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE ${ARG_PATH})
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES ARCHIVE_OUTPUT_NAME_DEBUG ${ARG_OUTPUT}D)
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES ARCHIVE_OUTPUT_NAME_RELEASE ${ARG_OUTPUT})
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_DEBUG ${ARG_PATH})
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY_RELEASE ${ARG_PATH})
    ELSEIF(CMAKE_SYSTEM_NAME MATCHES "Darwin")
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_NAME_DEBUG ${ARG_OUTPUT}D)
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_NAME_RELEASE ${ARG_OUTPUT})
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_DEBUG ${ARG_PATH})
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_RELEASE ${ARG_PATH})
    ELSEIF(CMAKE_SYSTEM_NAME MATCHES "Linux")
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_NAME_DEBUG ${ARG_OUTPUT}D)
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_NAME_RELEASE ${ARG_OUTPUT})
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_DEBUG ${ARG_PATH})
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_RELEASE ${ARG_PATH})
    ENDIF()

    IF(NOT ARG_INSTALL_DIR)
        IF(${ARG_PATH} STREQUAL ${NOVA_LIB_DIR})
            INSTALL(TARGETS ${TARGET}
                RUNTIME DESTINATION "${NOVA_INSTALL_DIR}/bin"
                LIBRARY DESTINATION "${NOVA_INSTALL_DIR}/lib"
                ARCHIVE DESTINATION "${NOVA_INSTALL_DIR}/lib"
            )
        ELSE()
            FILE(RELATIVE_PATH INSTALL_DIR ${NOVA_LIB_DIR} ${ARG_PATH})
            INSTALL(DIRECTORY ${ARG_PATH} DESTINATION ${NOVA_INSTALL_DIR}/lib)
        ENDIF()
    ELSE()
        IF(${ARG_INSTALL_DIR} STREQUAL "NULL")
        ELSE()
            INSTALL(TARGETS ${TARGET} DESTINATION ${ARG_INSTALL_DIR})
        ENDIF()
    ENDIF()
ENDMACRO()

MACRO(NOVA_ADD_PYLIB)
    NOVA_PARSE_ARGUMENTS(ARG
        "OUTPUT;HEADER;SOURCE;PACKAGE;PATH;INSTALL_DIR"
        "SHARE"
        ${ARGN}
    )

    IF(NOT ARG_DEFAULT_ARGS)
        MESSAGE(FATAL_ERROR "target cant empty.")
    ENDIF()

    IF(NOT ARG_HEADER AND NOT ARG_SOURCE)
        MESSAGE(FATAL_ERROR "To produce a library we need at least one source file.")
    ENDIF()

    LIST(GET ARG_DEFAULT_ARGS 0 TARGET)

    IF(NOT ARG_OUTPUT)
        SET(ARG_OUTPUT ${TARGET})
    ENDIF()

    IF(NOT ARG_PATH)
        SET(ARG_PATH ${NOVA_LIB_DIR})
    ENDIF()

    PYTHON_ADD_MODULE(${TARGET} ${ARG_HEADER} ${ARG_SOURCE})
    TARGET_INCLUDE_DIRECTORIES(${TARGET} PRIVATE ${NOVA_COMMON_INC_DIRS})
    TARGET_LINK_LIBRARIES(${TARGET} ${PRIVATE} ${ARG_PACKAGE})

    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_NAME_DEBUG ${ARG_OUTPUT}D)
    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_NAME_RELEASE ${ARG_OUTPUT})
    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_DEBUG ${ARG_PATH})
    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_RELEASE ${ARG_PATH})

    IF(ARG_SHARE AND CMAKE_SYSTEM_NAME MATCHES "Linux")
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES COMPILE_FLAGS
            "${CMAKE_SHARED_LIBRARY_C_FLAGS}")
    ENDIF()

    IF(NOT ARG_INSTALL_DIR)
        IF(${ARG_PATH} STREQUAL ${NOVA_LIB_DIR})
            INSTALL(TARGETS ${TRRGET}
                RUNTIME DESTINATION "${NOVA_INSTALL_DIR}/bin"
                LIBRARY DESTINATION "${NOVA_INSTALL_DIR}/lib"
                ARCHIVE DESTINATION "${NOVA_INSTALL_DIR}/lib"
            )
        ELSE()
            FILE(RELATIVE_PATH INSTALL_DIR ${NOVA_LIB_DIR} ${ARG_PATH})
            INSTALL(DIRECTORY ${ARG_PATH} DESTINATION ${NOVA_INSTALL_DIR}/lib)
        ENDIF()
    ELSE()
        IF(${ARG_INSTALL_DIR} STREQUAL "NULL")
        ELSE()
            INSTALL(TARGETS ${TARGET} DESTINATION ${ARG_INSTALL_DIR})
        ENDIF()
    ENDIF()
ENDMACRO()

MACRO(NOVA_ADD_PY11LIB)
    NOVA_PARSE_ARGUMENTS(ARG
        "OUTPUT;HEADER;SOURCE;PACKAGE;PATH;INSTALL_DIR"
        "SHARE"
        ${ARGN}
    )

    IF(NOT ARG_DEFAULT_ARGS)
        MESSAGE(FATAL_ERROR "target cant empty.")
    ENDIF()

    IF(NOT ARG_HEADER AND NOT ARG_SOURCE)
        MESSAGE(FATAL_ERROR "To produce a library we need at least one source file.")
    ENDIF()

    LIST(GET ARG_DEFAULT_ARGS 0 TARGET)

    IF(NOT ARG_OUTPUT)
        SET(ARG_OUTPUT ${TARGET})
    ENDIF()

    IF(NOT ARG_PATH)
        SET(ARG_PATH ${NOVA_LIB_DIR})
    ENDIF()

    PYBIND11_ADD_MODULE(${TARGET} SHARED ${ARG_HEADER} ${ARG_SOURCE})
    TARGET_INCLUDE_DIRECTORIES(${TARGET} PRIVATE ${NOVA_COMMON_INC_DIRS})
    TARGET_LINK_LIBRARIES(${TARGET} PRIVATE ${ARG_PACKAGE})

    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_NAME_DEBUG ${ARG_OUTPUT}D)
    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_NAME_RELEASE ${ARG_OUTPUT})
    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_DEBUG ${ARG_PATH})
    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_RELEASE ${ARG_PATH})

    IF(ARG_SHARE AND CMAKE_SYSTEM_NAME MATCHES "Linux")
        SET_TARGET_PROPERTIES(${TARGET} PROPERTIES COMPILE_FLAGS
            "${CMAKE_SHARED_LIBRARY_C_FLAGS}")
    ENDIF()

    IF(NOT ARG_INSTALL_DIR)
        IF(${ARG_PATH} STREQUAL ${NOVA_LIB_DIR})
            INSTALL(TARGETS ${TRRGET}
                RUNTIME DESTINATION "${NOVA_INSTALL_DIR}/bin"
                LIBRARY DESTINATION "${NOVA_INSTALL_DIR}/lib"
                ARCHIVE DESTINATION "${NOVA_INSTALL_DIR}/lib"
            )
        ELSE()
            FILE(RELATIVE_PATH INSTALL_DIR ${NOVA_LIB_DIR} ${ARG_PATH})
            INSTALL(DIRECTORY ${ARG_PATH} DESTINATION ${NOVA_INSTALL_DIR}/lib)
        ENDIF()
    ELSE()
        IF(${ARG_INSTALL_DIR} STREQUAL "NULL")
        ELSE()
            INSTALL(TARGETS ${TARGET} DESTINATION ${ARG_INSTALL_DIR})
        ENDIF()
    ENDIF()
ENDMACRO()

MACRO(NOVA_ADD_EXE)
    NOVA_PARSE_ARGUMENTS(ARG
        "OUTPUT;HEADER;SOURCE;PACKAGE;PATH;INSTALL_DIR"
        ""
        ${ARGN}
    )

    IF(NOT ARG_DEFAULT_ARGS)
        MESSAGE(FATAL_ERROR "target cant empty.")
    ENDIF()

    IF(NOT ARG_HEADER AND NOT ARG_SOURCE)
        MESSAGE(FATAL_ERROR "To produce a library we need at least one source file.")
    ENDIF()

    LIST(GET ARG_DEFAULT_ARGS 0 TARGET)

    IF(NOT ARG_OUTPUT)
        SET(ARG_OUTPUT ${TARGET})
    ENDIF()

    IF(NOT ARG_PATH)
        SET(ARG_PATH ${NOVA_LIB_DIR})
    ENDIF()

    ADD_EXECUTABLE(${TARGET} ${ARG_HEADER} ${ARG_SOURCE})
    TARGET_INCLUDE_DIRECTORIES(${TARGET} PRIVATE ${NOVA_COMMON_INC_DIRS})
    TARGET_LINK_LIBRARIES(${TARGET} ${ARG_PACKAGE})

    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_NAME_DEBUG ${ARG_OUTPUT}D)
    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_NAME_RELEASE ${ARG_OUTPUT})
    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_DEBUG ${ARG_PATH})
    SET_TARGET_PROPERTIES(${TARGET} PROPERTIES LIBRARY_OUTPUT_DIRECTORY_RELEASE ${ARG_PATH})

    IF(NOT ARG_INSTALL_DIR)
        IF(${ARG_PATH} STREQUAL ${NOVA_LIB_DIR})
            INSTALL(TARGETS ${TRRGET}
                RUNTIME DESTINATION "${NOVA_INSTALL_DIR}/bin"
                LIBRARY DESTINATION "${NOVA_INSTALL_DIR}/lib"
                ARCHIVE DESTINATION "${NOVA_INSTALL_DIR}/lib"
            )
        ELSE()
            FILE(RELATIVE_PATH INSTALL_DIR ${NOVA_LIB_DIR} ${ARG_PATH})
            INSTALL(DIRECTORY ${ARG_PATH} DESTINATION ${NOVA_INSTALL_DIR}/BIN/${INSTALL_DIR})
        ENDIF()
    ELSE()
        IF(${ARG_INSTALL_DIR} STREQUAL "NULL")
        ELSE()
            INSTALL(TARGETS ${TARGET} DESTINATION ${ARG_INSTALL_DIR})
        ENDIF()
    ENDIF()
ENDMACRO()

MACRO(NOVA_LINK_LIB)
    NOVA_PARSE_ARGUMENTS(ARG
        "DEBUG;RELEASE"
        ""
        ${ARGN}
    )
    LIST(GET ARG_DEFAULT_ARGS 0 TARGET)
    SET(LIBS ${ARG_DEFAULT_ARGS})
    LIST(REMOVE_AT LIBS 0)

    IF(ARG_DEBUG)
        FOREACH(_tmp ${ARG_DEBUG})
            SET(LIBS ${LIBS} debug ${_tmp})
        ENDFOREACH()
    ENDIF()

    TARGET_LINK_LIBRARIES(${TARGET} ${LIBS})
ENDMACRO()

MACRO(NOVA_INSTALL_PROJECT)
    ADD_CUSTOM_TARGET(Install${CMAKE_PROJECT_NAME}
        "${CMAKE_COMMAND}" --build "${CMAKE_BINARY_DIR}" --target install
        COMMENT "Install and Distribute ${CMAKE_PROJECT_NAME}")
ENDMACRO()

MACRO(NOVA_ADD_SUBDIRS)
    NOVA_GET_SUBDIRS(${CMAKE_CURRENT_SOURCE_DIR} tmp_subdirs)

    FOREACH(_base ${tmp_subdirs})
        IF(EXISTS "${_base}/CMakeLists.txt")
            ADD_SUBDIRECTORY(${_base})
        ENDIF()
    ENDFOREACH()
ENDMACRO()

MACRO(COPY_FILE_IF_EXISTS src dst)
    IF(EXISTS "${src}")
        CONFIGURE_FILE(${src} ${dst} COPYONLY)
    ENDIF()
ENDMACRO()

MACRO(ADD_DEPENDENCY_IF_EXISTS tgt dep)
    IF(TARGET "${dep}")
        ADD_DEPENDENCIES(${tgt} ${dep})
    ENDIF()
ENDMACRO()