USDT:
  "balance_quantity": 9709
  "max_percentage": 1.5
  "fp_adjust_1": 2.0
  "fp_adjust_2": 2.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 0.0
  "slop_2": 0.0
  "spread_1": 0.0
  "spread_2": 0.0
  "sell_open_slop": 1.0
  "buy_open_slop": 1.0
  "sell_close_slop": 0.25
  "buy_close_slop": 0.25
  "spread": 0.0
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.1
  "customer_balance": 9709
USDC:
  "balance_quantity": 2356
  "max_percentage": 3.0
  "fp_adjust_1": 2.0
  "fp_adjust_2": 2.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 3.0
  "slop_1": 0.0
  "slop_2": 0.0
  "spread_1": 0.0
  "spread_2": 0.0
  "sell_open_slop": 2.0
  "buy_open_slop": 0.5
  "sell_close_slop": 0.15
  "buy_close_slop": 0.25
  "spread": 0.0
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.0
  "customer_balance": 2356
USD:
  "balance_quantity": 21682
  "max_percentage": 3.0
  "fp_adjust_1": 2.0
  "fp_adjust_2": 2.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 4.0
  "slop_1": 0.0
  "slop_2": 0.0
  "spread_1": 0.0
  "spread_2": 0.0
  "sell_open_slop": 1.0
  "buy_open_slop": 0.3
  "sell_close_slop": 0.1
  "buy_close_slop": 0.25
  "spread": 0.0
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.0
  "customer_balance": 21682
DAI:
  "balance_quantity": 1.0
  "max_percentage": 2.0
  "fp_adjust_1": 2.0
  "fp_adjust_2": 2.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 0.0
  "slop_2": 2.0
  "spread_1": 0.0
  "spread_2": 0.0
  "sell_open_slop": 0.0
  "buy_open_slop": 0.0
  "sell_close_slop": 0.0
  "buy_close_slop": 0.0
  "spread": 0.0
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.1
  "customer_balance": 7360
EUR:
  "balance_quantity": 12369
  "max_percentage": 1.5
  "fp_adjust_1": 2.0
  "fp_adjust_2": 2.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 0.0
  "slop_2": 0.0
  "spread_1": 0.0
  "spread_2": 0.0
  "sell_open_slop": 1.5
  "buy_open_slop": 1.5
  "sell_close_slop": 0.4
  "buy_close_slop": 0.4
  "spread": 0.0
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.0
  "customer_balance": 12369
CHF:
  "balance_quantity": 49775.0
  "max_percentage": 1.5
  "fp_adjust_1": 5.0
  "fp_adjust_2": 5.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 0.0
  "slop_2": 0.0
  "spread_1": 0.0
  "spread_2": 0.0
  "sell_open_slop": 3.0
  "buy_open_slop": 3.0
  "sell_close_slop": 0.6
  "buy_close_slop": 0.6
  "spread": 0.0
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.0
  "customer_balance": 7360
GBP:
  "balance_quantity": 5999
  "max_percentage": 1.5
  "fp_adjust_1": 3.0
  "fp_adjust_2": 3.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 0.0
  "slop_2": 0.0
  "spread_1": 0.0
  "spread_2": 0.0
  "sell_open_slop": 1.5
  "buy_open_slop": 1.5
  "sell_close_slop": 0.4
  "buy_close_slop": 0.4
  "spread": 0.0
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.0
  "customer_balance": 5999
CAD:
  "balance_quantity": 60253.6
  "max_percentage": 1.5
  "fp_adjust_1": 8.0
  "fp_adjust_2": 8.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 0.0
  "slop_2": 0.0
  "spread_1": 0.0
  "spread_2": 0.0
  "sell_open_slop": 5.0
  "buy_open_slop": 5.0
  "sell_close_slop": 1.0
  "buy_close_slop": 1.0
  "spread": 1.0
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.0
  "customer_balance": 7360
AUD:
  "balance_quantity": 86418.2
  "max_percentage": 1.5
  "fp_adjust_1": 10.0
  "fp_adjust_2": 10.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 0.0
  "slop_2": 0.0
  "spread_1": 0.0
  "spread_2": 0.0
  "sell_open_slop": 7.0
  "buy_open_slop": 7.0
  "sell_close_slop": 1.5
  "buy_close_slop": 1.5
  "spread": 1.0
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.0
  "customer_balance": 7360
PAXG:
  "balance_quantity": 5.5
  "max_percentage": 1.5
  "fp_adjust_1": 10.0
  "fp_adjust_2": 10.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 0.0
  "slop_2": 0.0
  "spread_1": 0.0
  "spread_2": 0.0
  "sell_open_slop": 7.0
  "buy_open_slop": 7.0
  "sell_close_slop": 1.5
  "buy_close_slop": 1.5
  "spread": 1.0
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.1
  "customer_balance": 7360
BTC:
  "balance_quantity": 0.2253
  "max_percentage": 0.5
  "fp_adjust_1": 7.0
  "fp_adjust_2": 7.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 3.0
  "slop_2": 3.0
  "spread_1": 1.0
  "spread_2": 0.0
  "sell_open_slop": 3.0
  "buy_open_slop": 3.0
  "sell_close_slop": 0.5
  "buy_close_slop": 0.5
  "spread": 0.3
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.0
  "customer_balance": 0.2253
ETH:
  "balance_quantity": 3.45
  "max_percentage": 0.5
  "fp_adjust_1": 7.0
  "fp_adjust_2": 7.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 3.0
  "slop_2": 3.0
  "spread_1": 1.0
  "spread_2": 0.0
  "sell_open_slop": 3.0
  "buy_open_slop": 3.0
  "sell_close_slop": 0.5
  "buy_close_slop": 0.5
  "spread": 0.5
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.0
  "customer_balance": 3.45
SOL:
  "balance_quantity": 82.6
  "max_percentage": 0.5
  "fp_adjust_1": 9.0
  "fp_adjust_2": 9.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 3.0
  "slop_2": 3.0
  "spread_1": 1.0
  "spread_2": 0.0
  "sell_open_slop": 6.0
  "buy_open_slop": 6.0
  "sell_close_slop": 1.5
  "buy_close_slop": 1.5
  "spread": 1.5
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.1
  "customer_balance": 82.6
DOT:
  "balance_quantity": 24.97
  "max_percentage": 1.5
  "fp_adjust_1": 9.0
  "fp_adjust_2": 9.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 3.0
  "slop_2": 3.0
  "spread_1": 1.0
  "spread_2": 0.0
  "sell_open_slop": 5.0
  "buy_open_slop": 5.0
  "sell_close_slop": 1.0
  "buy_close_slop": 1.0
  "spread": 1.5
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.1
  "customer_balance": 7360
MATIC:
  "balance_quantity": 82346.0
  "max_percentage": 1.5
  "fp_adjust_1": 9.0
  "fp_adjust_2": 9.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 3.0
  "slop_2": 3.0
  "spread_1": 1.0
  "spread_2": 0.0
  "sell_open_slop": 6.0
  "buy_open_slop": 6.0
  "sell_close_slop": 1.5
  "buy_close_slop": 1.5
  "spread": 1.5
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.3
  "customer_balance": 7360
DOGE:
  "balance_quantity": 742581.4
  "max_percentage": 1.5
  "fp_adjust_1": 9.0
  "fp_adjust_2": 9.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 3.0
  "slop_2": 3.0
  "spread_1": 1.0
  "spread_2": 0.0
  "sell_open_slop": 6.0
  "buy_open_slop": 6.0
  "sell_close_slop": 1.5
  "buy_close_slop": 1.5
  "spread": 1.5
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 1.0
  "customer_balance": 7360
LTC:
  "balance_quantity": 2.1825
  "max_percentage": 1.5
  "fp_adjust_1": 9.0
  "fp_adjust_2": 9.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 3.0
  "slop_2": 3.0
  "spread_1": 1.0
  "spread_2": 0.0
  "sell_open_slop": 3.0
  "buy_open_slop": 3.0
  "sell_close_slop": 0.5
  "buy_close_slop": 0.5
  "spread": 0.5
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.3
  "customer_balance": 7360
XRP:
  "balance_quantity": 3908
  "max_percentage": 0.5
  "fp_adjust_1": 9.0
  "fp_adjust_2": 9.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 3.0
  "slop_2": 3.0
  "spread_1": 1.0
  "spread_2": 0.0
  "sell_open_slop": 5.0
  "buy_open_slop": 5.0
  "sell_close_slop": 1.0
  "buy_close_slop": 1.0
  "spread": 0.7
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 1.0
  "customer_balance": 3908
ADA:
  "balance_quantity": 625.532
  "max_percentage": 1.5
  "fp_adjust_1": 9.0
  "fp_adjust_2": 9.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 3.0
  "slop_2": 3.0
  "spread_1": 1.0
  "spread_2": 0.0
  "sell_open_slop": 5.0
  "buy_open_slop": 5.0
  "sell_close_slop": 1.0
  "buy_close_slop": 1.0
  "spread": 1.5
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.1
  "customer_balance": 7360
LINK:
  "balance_quantity": 7051.28
  "max_percentage": 1.5
  "fp_adjust_1": 9.0
  "fp_adjust_2": 9.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 3.0
  "slop_2": 3.0
  "spread_1": 1.0
  "spread_2": 0.0
  "sell_open_slop": 6.0
  "buy_open_slop": 6.0
  "sell_close_slop": 1.55
  "buy_close_slop": 1.5
  "spread": 1.5
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.3
  "customer_balance": 7360
ATOM:
  "balance_quantity": 2565.2
  "max_percentage": 1.5
  "fp_adjust_1": 9.0
  "fp_adjust_2": 9.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 3.0
  "slop_2": 3.0
  "spread_1": 1.0
  "spread_2": 0.0
  "sell_open_slop": 6.0
  "buy_open_slop": 6.0
  "sell_close_slop": 1.5
  "buy_close_slop": 1.5
  "spread": 1.5
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.0
  "customer_balance": 7360
AVAX:
  "balance_quantity": 391.6
  "max_percentage": 1.5
  "fp_adjust_1": 9.0
  "fp_adjust_2": 9.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 3.0
  "slop_2": 3.0
  "spread_1": 1.0
  "spread_2": 0.0
  "sell_open_slop": 6.0
  "buy_open_slop": 6.0
  "sell_close_slop": 1.5
  "buy_close_slop": 1.5
  "spread": 1.5
  "sell_close_extension": 0.3
  "buy_close_extension": 0.3
  "credit": 0.0
  "collateral_haircut": 0.0
  "customer_balance": 7360
PENGU:
  "balance_quantity": 168602.0
  "max_percentage": 2.0
  "fp_adjust_1": 9.0
  "fp_adjust_2": 9.0
  "balance_adjust_1": 2.0
  "balance_adjust_2": 2.0
  "slop_1": 3.0
  "slop_2": 3.0
  "spread_1": 1.0
  "spread_2": 0.0
  "sell_open_slop": 8.0
  "buy_open_slop": 8.0
  "sell_close_slop": 2.0
  "buy_close_slop": 2.0
  "spread": 2.0
  "sell_close_extension": 0.2
  "buy_close_extension": 0.2
  "credit": 0.0
  "collateral_haircut": 0.0
  "customer_balance": 168602.0
