#pragma once

#include "base_util.h"
#include "nova_api_exch.h"

#include "nova_api_config.h"

enum NOVA_PRICE_TYPE : uint8_t
{
    NOVA_PRICE_INIT = 0,
    NOVA_PRICE_LIMIT = 1,
    NOVA_PRICE_LIMIT_FAK = 2,
    NOVA_PRICE_LIMITFOK = 3,
    NOVA_PRICE_POST_ONLY = 4,

    NOVA_PRICE_MARGIN_SETTLE = 5,

    NOVA_PRICE_UNKNOWN,
};

enum NOVA_SIDE_TYPE : uint8_t
{
    NOVA_SIDE_INIT = 0,
    NOVA_SIDE_BUY = 1,
    NOVA_SIDE_SELL = 2,

    NOVA_SIDE_MARGIN_BUY = 4,
    NOVA_SIDE_MARGIN_SELL = 5,

    NOVA_SIDE_UNKNOWN,
};

enum NOVA_POSITION_EFFECT_TYPE : uint8_t
{
    NOVA_POSITION_EFFECT_INIT = 0,
    NOVA_POSITION_EFFECT_OPEN = 1,
    NOVA_POSITION_EFFECT_CLOSE = 2,
    NOVA_POSITION_EFFECT_REDUCE_ONLY = 3,
    NOVA_POSITION_EFFECT_UNKNOWN
};

enum NOVA_POSITION_SIDE_TYPE : uint8_t
{
    NOVA_POSITION_SIDE_INIT = 0,
    NOVA_POSITION_SIDE_LONG,
    NOVA_POSITION_SIDE_SHORT,
    NOVA_POSITION_SIDE_UNKNOWN
};

enum NOVA_ORDER_STATUS : uint8_t
{
    NOVA_ORDER_STATUS_INIT = 0,
    NOVA_ORDER_STATUS_ACCEPTED,
    NOVA_ORDER_STATUS_REJECTED,
    NOVA_ORDER_STATUS_PARTIALLY_FILLED,
    NOVA_ORDER_STATUS_FILLED,
    NOVA_ORDER_STATUS_CANCELLED,
    NOVA_ORDER_STATUS_UNKNOWN,
};

enum NOVA_ORDER_EVENT_STATUS : uint8_t
{
    NOVA_ORDER_EVENT_STATUS_ACCEPTED,
    NOVA_ORDER_EVENT_STATUS_REJECTED,
    NOVA_ORDER_EVENT_STATUS_FILLED,
    NOVA_ORDER_EVENT_STATUS_CANCELLED,
    NOVA_ORDER_EVENT_STATUS_CANCELL_FAILED,

    NOVA_ORDER_EVENT_STATUS_AMENDED,
    NOVA_ORDER_EVENT_STATUS_AMEND_FAILED,
};

enum OrderRejectReason : uint32_t
{
    REJECT_INIT = 0,
    REJECT_INSUFFICIENT_FUND = 1,
    REJECT_INSUFFICIENT_POS = 2,
    REJECT_ORDER_QTY = 3,
    REJECT_ORDER_PRICE = 4,
    REJECT_POST_ONLY_FAILED = 5,
    REJECT_RISK_CONTROL = 10,
    REJECT_FLOW_CONTROL = 20,
    REJECT_CANCEL_INVALID_ID = 100,
    REJECT_CANCEL_FINISHED = 101,
    REJECT_CANCEL_INVALID_TYPE = 102,
    REJECT_CANCEL_LIMIT = 110,
    REJECT_UNKNOWN_ORDER = 200,
    REJECT_NETWORK_ISSUE = 254,
    REJECT_OTHER = 255
};

enum QUERY_PROXY_TYPE : uint8_t
{
    QUERY_HTTP_REST,
    QUERY_WS,
};
